### ISSUE TITLE
There is any way to distinguish between an instance that boot from volume and Image from Openstack4j?

### ISSUE THREAD

**Issue by anhdenday** [gondor/openstack4j#104]
Dear Gondor,
A/ Whenever I create an instance, I make two options.
1- Boot from image
2- Booot from volume
Can you make a option by the way add an attribute to distinguish it, something like "bootOption" filed with 2 values (Example: Image or Volume), so that I can list only server that boot only from image or list only server that boot from volume?
Actually I can do it by the way make a filed bootOption and save it in my database, so I can list the instance depend on list  of all server that boot from volume/image on my database, but I prefer to have this one from core of openstack4j.
B/ When I create a server that boot from Volume. As you already know, the flavor's disk it's not using. The hard disk of instance is the volume that boot from. So can you make a flag or something like signal to notify that flavor's disk is zero or something like that. because now the configuration of server is CPU, RAM and Volume (HDD disk is get from volume not Flavor's disk) 

Thanks you so much

**Comment by gondor** [comment]
Closing this due to length of time.  Might suggest posting this in the OpenStack4j Group.
