### ISSUE TITLE
Support for network extensions: Load Balancer, Firewall & VPN

### ISSUE THREAD

**Issue by lizepeng201021** [gondor/openstack4j#137]
Dear @gondor ,
I can not find the api for network application ..
eg . openstack horizon has the function below

load balance,firewall,vpn like below

![qq 20141121221455](https://cloud.githubusercontent.com/assets/7960468/5143527/e6b4ef42-71cb-11e4-92fe-0438481dad05.png)

**Comment by liujunpengwork** [comment]
Should I write the code about Lbaas？

**Comment by gondor** [comment]
I haven't had time to tackle this.  If you end up wanting to write it let me know so I don't do the same :)

**Comment by liujunpengwork** [comment]
I write the code about Lbaas。I will test the code in my openstack enviroment installed by devstack.
I will finish it ,then request a pull  to you.Then you review it

**Comment by gondor** [comment]
@liujunpengwork Excellent! Thank you.  Can you track against Issue #208.  When you do you pull request use that issue.

**Comment by gondor** [comment]
Everyone, @liujunpengwork has done a great job and contributed the LBaaS implementation.  This is tracked under Issue #208.  I have just deployed the latest SNAPSHOT with this enhancement.

**Comment by gondor** [comment]
LBaaS supported.  FWaaS will be another future issue create.  Closing for 2.0.2 release happening tonight
