### ISSUE TITLE
how to update subnet

### ISSUE THREAD

**Issue by lizepeng201021** [gondor/openstack4j#176]
Dear @gondor 

How to update subnet 

below is my code (want to update subnet's name and gateway)
SubnetBuilder  subNetBuilder=Builders.subnet()
		        .name("subnet1")
		        .networkId("2d2b585f-30d0-47ac-9377-715ba1f3a428")
		        .gateway("192.168.1.1");

os.networking().subnet().update(subNet.toBuilder().gateway("192.168.12").build());

it return this error 

Caused by: ClientResponseException{message=Bad Request, status=400, status-code=BAD_REQUEST}

**Comment by gondor** [comment]
Closing this due to length of time.
