### ISSUE TITLE
Error retrieving keypair list

### ISSUE THREAD

**Issue by bassimatteo** [gondor/openstack4j#185]
Hi,

using this function: 
```
      os.compute().keypairs().list();
```
I receive an empty list.

Debugging your code I found a error in the uri in the execute method of the class org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor:

```
String uri = request.getUri();
```

The value of the uri is:  uri = https://****:8787//os-keypairs

probably you add the "/" character  two times

My pom:

```
<dependency>
	<groupId>org.pacesys</groupId>
	<artifactId>openstack4j-core</artifactId>
	<version>2.0.0</version>
</dependency>
		
<dependency>
	<groupId>org.pacesys.openstack4j.connectors</groupId>
	<artifactId>openstack4j-resteasy</artifactId>
	<version>2.0.0</version>
</dependency> 
```

Thanks

**Comment by bassimatteo** [comment]
```
OSFactory.enableHttpLoggingFilter(true);
OSClient os = OSFactory.builder().endpoint("http://***:5000/v2.0/").
    credentials("***", "***").tenantName("***").authenticate();
    	
String response = os.compute().keypairs().list().toString();
```

If I configure the *openstack4j-resteasy* connector in my pom.xml neither the requests nor the responses are printed. But, if I use the default setup(Jersey2) I can see either the requests and the responses.

In my project I must to use resteasy.

**Comment by gondor** [comment]
This is odd.  So your testing with two different "server" installs? One HTTP and HTTPS?  I don't quite understand the setup.

**Comment by bassimatteo** [comment]
Yes, I've two server installs.

I summarize a partial list of the service endpoints to better understand:

Server 1 with HTTPS (Openstack Icehouse):
```
Identity        https://xxxx:5000/v2.0
Compute         http://xxxx:8774/v2/f1b4e9b1ee574cb0b726150f41a3d091
Network         http://xxxx:9696
Orchestration	http://xxxx:8004/v1/f1b4e9b1ee574cb0b726150f41a3d091
```
Only the Identity service is HTTPS.

The server 2(Openstack Havana) with HTTP configuration is: 
```
Identity         http://yyyy:5000/v2.0
Compute          http://yyyy:8774/v2/dd0eca7c59ca479caf6d1e166622a478
Network          http://yyyy:9696
Orchestration	 http://xxxx:8004/v1/dd0eca7c59ca479caf6d1e166622a478
```
All services are HTTP.

With server 2 (HTTP) the compute service works.

**Comment by gondor** [comment]
Do me a favor.  Since I don't have any info on the Access object being returned by your deployment could you turn this on and see if it resolves it.  If it doesn't I'll probably want you to email me the toString of the Access object which can be done by System.out.println(os.getAccess());

Before you authenticate turn on Legacy endpoint resolution:

```java
OSFactory.enableLegacyEndpointHandling(true);
OSClient os = OSFactory.builder // etc - normal code
```

**Comment by bassimatteo** [comment]
I have attached a file containing the access object.

2015-01-08 18:50 GMT+01:00 Jeremy Unruh <notifications@github.com>:

> Do me a favor. Since I don't have any info on the Access object being
> returned by your deployment could you turn this on and see if it resolves
> it. If it doesn't I'll probably want you to email me the toString of the
> Access object which can be done by System.out.println(os.getAccess());
>
> Before you authenticate turn on Legacy endpoint resolution:
>
> OSFactory.enableLegacyEndpointHandling(true);OSClient os = OSFactory.builder // etc - normal code
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gondor/openstack4j/issues/185#issuecomment-69218777>.
>
OSFactory.enableHttpLoggingFilter(true);
OSFactory.enableLegacyEndpointHandling(true);
OSClient os = OSFactory.builder().endpoint(identityURL + "/v2.0")
				.credentials(username, pwd).tenantName(tenant).authenticate();
		
LOG.debug(os.getAccess().toString());



DEBUG - [
			AccessService{
				name=nova, type=compute, endpoints=[ 
					KeystoneEndpoint{
						id=32f452bed6b8473baa5eb28dec6a4802, region=regionOne, 
						publicURL=http://****:8774/v2/f1b4e9b1ee574cb0b726150f41a3d091, 
						internalURL=http://192.168.230.16:8774/v2/f1b4e9b1ee574cb0b726150f41a3d091, 
						adminURL=http://192.168.230.16:8774/v2/f1b4e9b1ee574cb0b726150f41a3d091}
				]
			}, 
			AccessService{
				name=neutron, type=network, endpoints=[
					KeystoneEndpoint{
						id=0e2b16076228460da68196e3c9567a70, region=regionOne, 
						publicURL=http://****:9696, 
						internalURL=http://192.168.230.17:9696, 
						adminURL=http://192.168.230.17:9696}
				]
			}, 
			AccessService{
				name=cinderv2, type=volumev2, endpoints=[
					KeystoneEndpoint{
					id=0c83343e57cb41b1b9e3ba54f7c48168, region=regionOne, 
					publicURL=http://*****:8776/v2/f1b4e9b1ee574cb0b726150f41a3d091, 
					internalURL=http://192.168.230.16:8776/v2/f1b4e9b1ee574cb0b726150f41a3d091, 
					adminURL=http://192.168.230.16:8776/v2/f1b4e9b1ee574cb0b726150f41a3d091}
				]
			}, 
			AccessService{
				name=s3, type=s3, endpoints=[
					KeystoneEndpoint{
						id=a4ac1e8c461140b19fd140a3e35a42c1, region=regionOne, 
						publicURL=http://******:8080, 
						internalURL=http://*****:8080, 
						adminURL=http://*****:8080}
				]
			}, 
			AccessService{
				name=glance, type=image, endpoints=[
					KeystoneEndpoint{
						id=094026bffdc54e96bd89efcf51c92151, region=regionOne, 
						publicURL=http://****:9292, 
						internalURL=http://192.168.230.16:9292, 
						adminURL=http://192.168.230.16:9292}
				]
			}, 
			AccessService{
				name=ceilometer, type=metering, endpoints=[
					KeystoneEndpoint{
						id=0d153cc8b8bb4d57bfbd7ae74cded64e, region=regionOne, 
						publicURL=http://*****:8777, 
						internalURL=http://****:8777, 
						adminURL=http://*****
					}
				]
			}, 
			AccessService{
				name=heat-cfn, type=cloudformation, endpoints=[
					KeystoneEndpoint{
						id=1641b536b59e477caf8e374c516764b8, region=regionOne, 
						publicURL=http://****:8000/v1, 
						internalURL=http://******:8000/v1, 
						adminURL=http://******:8000/v1}
				]
			}, 
			AccessService{
				name=cinder, type=volume, endpoints=[
					KeystoneEndpoint{
						id=1a1524a047574cb794b390b51116568e, region=regionOne, 
						publicURL=http://******:8776/v1/f1b4e9b1ee574cb0b726150f41a3d091, 
						internalURL=http://192.168.230.16:8776/v1/f1b4e9b1ee574cb0b726150f41a3d091, 
						adminURL=http://192.168.230.16:8776/v1/f1b4e9b1ee574cb0b726150f41a3d091}
				]
			}, 
			AccessService{
				name=ec2, type=ec2, endpoints=[
					KeystoneEndpoint{
						id=191f55d4c45f46e086a8a6d52d953875, region=regionOne, 
						publicURL=http://******:8773/services/Cloud, 
						internalURL=http://192.168.230.16:8773/services/Cloud, 
						adminURL=http://*******:8773/services/Admin}
				]
			}, 
			AccessService{
				name=heat, type=orchestration, endpoints=[
					KeystoneEndpoint{
						id=7b58c5a4b5e947ff859df9b435b33ed9, region=regionOne, 
						publicURL=http://******:8004/v1/f1b4e9b1ee574cb0b726150f41a3d091, 
						internalURL=http://*****:8004/v1/f1b4e9b1ee574cb0b726150f41a3d091, 
						adminURL=http://******:8004/v1/f1b4e9b1ee574cb0b726150f41a3d091}
				]
			}, 
			AccessService{
			name=swift, type=object-store, endpoints=[
				KeystoneEndpoint{
					id=14dd34f01f2b4e1b896302e370a26a65, region=regionOne, 
					publicURL=https://****:8080/v1/AUTH_f1b4e9b1ee574cb0b726150f41a3d091, 
					internalURL=https://****:8080/v1/AUTH_f1b4e9b1ee574cb0b726150f41a3d091, 
					adminURL=https://****:8080}
				]
			}, 
			AccessService{
				name=keystone, type=identity, endpoints=[
					KeystoneEndpoint{
						id=19dc2df15e504209b3dca1fcdb956522, region=regionOne, 
						publicURL=https://****:5000/v2.0, 
						internalURL=https://****:5000/v2.0, 
						adminURL=https://****:35357/v2.0}
					]
				}
			]

**Comment by bassimatteo** [comment]
I solved the problem by changing the configuration of the service OCCI from "name=nova, type=occi" to "name=nova-occi, type=occi".

**Comment by gondor** [comment]
Good catch. We generically don't know if a service type is something other than nova, etc so we stick to the standards.  Glad you found the issue.
