### ISSUE TITLE
How to issue a volume transfer call

### ISSUE THREAD

**Issue by nirajdp** [gondor/openstack4j#189]
Openstack python client (cinder) provides a api to able to transfer a volume from one tenant to another. How to achieve this using openstack4j?

**Comment by gondor** [comment]
What command do you normally use via the python client?  An example with the -debug output could expedite adding this to os4j if we don't support it.

**Comment by nirajdp** [comment]
The relevant cinder commands are:
- cinder transfer-create
- cinder transfer-accept
- cinder transfer-delete
- cinder transfer-list
- cinder transfer-show

Here is --debug output for each of these commands:
$ cinder --debug transfer-create --display-name "test-xfer1" a8a8f546-a795-46ac-b9af-441a54906ca4
DEBUG:keystoneclient.session:REQ: curl -i -X GET https://192.168.101.10:5000/v2.0 -H "Accept: application/json" -H "User-Agent: python-keystoneclient"
DEBUG:keystoneclient.session:RESP: [200] date: Tue, 06 Jan 2015 03:58:02 GMT vary: X-Auth-Token content-length: 618 content-type: application/json connection: keep-alive
RESP BODY: {"version": {"status": "stable", "updated": "2014-04-17T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v2.0+json"}, {"base": "application/xml", "type": "application/vnd.openstack.identity-v2.0+xml"}], "id": "v2.0", "links": [{"href": "https://192.168.101.10:5000/v2.0/", "rel": "self"}, {"href": "http://docs.openstack.org/api/openstack-identity-service/2.0/content/", "type": "text/html", "rel": "describedby"}, {"href": "http://docs.openstack.org/api/openstack-identity-service/2.0/identity-dev-guide-2.0.pdf", "type": "application/pdf", "rel": "describedby"}]}}

DEBUG:keystoneclient.auth.identity.v2:Making authentication request to https://192.168.101.10:5000/v2.0/tokens
DEBUG:keystoneclient.session:REQ: curl -i -X GET https://192.168.101.10:8776/v1/a0cf15f2c1b64f8fa1494047ba758f1c/volumes/a8a8f546-a795-46ac-b9af-441a54906ca4 -H "User-Agent: python-cinderclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}67d575fb435d22ec6a5700ae7c80f2edcf6106e1"
DEBUG:keystoneclient.session:RESP: [200] date: Tue, 06 Jan 2015 03:58:03 GMT connection: keep-alive content-type: application/json x-compute-request-id: req-700d72e9-caa3-487b-84e7-26a179f054a5 content-length: 432
RESP BODY: {"volume": {"status": "available", "display_name": "tesvol1", "attachments": [], "availability_zone": "nova", "bootable": "false", "encrypted": false, "created_at": "2015-01-06T03:50:46.266480", "os-vol-tenant-attr:tenant_id": "a0cf15f2c1b64f8fa1494047ba758f1c", "display_description": null, "volume_type": "None", "snapshot_id": null, "source_volid": null, "metadata": {}, "id": "a8a8f546-a795-46ac-b9af-441a54906ca4", "size": 10}}

DEBUG:keystoneclient.session:REQ: curl -i -X POST https://192.168.101.10:8776/v1/a0cf15f2c1b64f8fa1494047ba758f1c/os-volume-transfer -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}67d575fb435d22ec6a5700ae7c80f2edcf6106e1" -d '{"transfer": {"name": "test-xfer1", "volume_id": "a8a8f546-a795-46ac-b9af-441a54906ca4"}}'
DEBUG:keystoneclient.session:RESP: [202] date: Tue, 06 Jan 2015 03:58:03 GMT connection: keep-alive content-type: application/json x-compute-request-id: req-8e579498-c17f-4dbb-87f3-075bf3220ce4 content-length: 519
RESP BODY: {"transfer": {"auth_key": "df7aba616293e5bc", "links": [{"href": "https://192.168.101.10:8776/v1/a0cf15f2c1b64f8fa1494047ba758f1c/os-volume-transfer/e428d14d-2fac-487a-a2e5-e09244396aaf", "rel": "self"}, {"href": "https://192.168.101.10:8776/a0cf15f2c1b64f8fa1494047ba758f1c/os-volume-transfer/e428d14d-2fac-487a-a2e5-e09244396aaf", "rel": "bookmark"}], "created_at": "2015-01-06T03:58:03.174942", "volume_id": "a8a8f546-a795-46ac-b9af-441a54906ca4", "id": "e428d14d-2fac-487a-a2e5-e09244396aaf", "name": "test-xfer1"}}

+------------+--------------------------------------+
|  Property  |                Value                 |
+------------+--------------------------------------+
|  auth_key  |           df7aba616293e5bc           |
| created_at |      2015-01-06T03:58:03.174942      |
|     id     | e428d14d-2fac-487a-a2e5-e09244396aaf |
|    name    |              test-xfer1              |
| volume_id  | a8a8f546-a795-46ac-b9af-441a54906ca4 |
+------------+--------------------------------------+

if needed i can post cli output with --debug for rest of the commands as well.

**Comment by gondor** [comment]
This is perfect.  We are about to release 2.0.1 and will target this for 2.0.2 (will be a short release) so expect it real soon.  I will ping you if I have any other questions

**Comment by nirajdp** [comment]
Just wanted to find out when will 2.0.2 come out and know xfer volume api support will be in 2.0.2

**Comment by gondor** [comment]
Thank you for re-surfacing this issue.  I completely forgot about it.  2.0.2 will be out in a week or two.  I'll try to get this feature complete in the next few days so you can test the SNAPSHOT prior to the actual release.

**Comment by nirajdp** [comment]
Thank you... Just let me know which snapshot i can pick and when. Appreciate your help and quick response.

**Comment by gondor** [comment]
@nirajdp Thanks for your patience.  I have added everything to OpenStack4j.  Please test and let me know!  To access all the volume transfer related calls its found under:

```java
os.blockStorage().volumes().transfer().create // etc
```

**Comment by gondor** [comment]
Deploying 2.0.2 Release Tonight - Closing - Re-Open or Comment if issue was not resolved
