### ISSUE TITLE
Error loading HttpExecutorService when running from Jenkins

### ISSUE THREAD

**Issue by naamab** [gondor/openstack4j#193]
I'm trying to authenticate against OpenStack from a Jenkins plugin.
The thread doesn't find any class which implements HttpExecutorService, and fails with a NullPointerException (since LOG is not initialized)
Running the same code from a test app works fine.

**Comment by gondor** [comment]
You need to include a connector with your plugin.  The easiest would be to depend on the -withdeps artifact which includes the connector, etc.    OpenStack4j is flexible allowing you to choose your connector (Jersey 2, RestEasy, HttpClient, OkHttp, etc)

See http://www.openstack4j.com/learn/getting-started/

**Comment by naamab** [comment]
Using 'withdeps' creates many conflicts with other packages I use in my project.
These are the relevant sections from my pom.xml:
        <dependency>
            <groupId>org.pacesys</groupId>
            <artifactId>openstack4j</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.pacesys.openstack4j.connectors</groupId>
            <artifactId>openstack4j-httpclient</artifactId>
            <version>2.0.0</version>
        </dependency>

I still get the same NullPointerException in line 32 of HttpExecutor

**Comment by gondor** [comment]
Ok, I see your issue.  You need your top dependency to be openstack4j-core .  The one your defining pulls in Jersey 2 and then your additional httpclient declaration would conflict.

**Should be:**
```xml
        <dependency>
            <groupId>org.pacesys</groupId>
            <artifactId>openstack4j-core</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.pacesys.openstack4j.connectors</groupId>
            <artifactId>openstack4j-httpclient</artifactId>
            <version>2.0.0</version>
        </dependency>
```

**Comment by gondor** [comment]
@naamab have you had a chance to try my suggestion above ^^ ?

**Comment by gondor** [comment]
Closing this due to length of time and no response.
