### ISSUE TITLE
Connection Timed Out Exception with TryStack

### ISSUE THREAD

**Issue by Shaileshwar551** [gondor/openstack4j#198]
Hi Jeremy,
I've been trying to connect to TryStack like I did with an OpenStack cloud previously at my work place.
Logged into TryStack using my FB credentials.  

But I get this ConnectionException:

![error](https://cloud.githubusercontent.com/assets/10056711/5679579/87eed8d8-9827-11e4-8643-8b20cfa99f28.png)

Am assuming that this is an issue from TryStack side. Please tell me a way to get around this problem.

Thanks,
Shaileshwar

**Comment by gondor** [comment]
It sounds like your defining the endpoint URL wrong.  The connection timeout it pretty low level indicating a firewall, private address behind a public host or invalid URL

**Comment by Shaileshwar551** [comment]
Thanks Jeremy. Got your point. Problem solved. I was not able to access TryStack at my work place. May be firewall was causing this problem. But I can access it now from my home network.
