### ISSUE TITLE
Find a specific Tenant using getByName function raise exception

### ISSUE THREAD

**Issue by sheldonhu** [gondor/openstack4j#201]
Find all Tenants with "os.identity().tenants().list()" works ,but Find a specific Tenant using getByName function raise exception below:Root name 'tenants_links' does not match expected ('tenant') for type [simple type, class org.openstack4j.openstack.identity.domain.KeystoneTenant]
 at [Source: org.jboss.resteasy.client.core.SelfExpandingBufferredInputStream@6e6989d7; line: 1, column: 2]
	at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:469)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:377)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:350)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:344)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.readEntity(HttpResponseImpl.java:113)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:73)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:61)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:164)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:158)
	at org.openstack4j.openstack.identity.internal.TenantServiceImpl.getByName(TenantServiceImpl.java:34)
	at org.inspur.test.OpenstackNetwork.main(OpenstackNetwork.java:31).

did i do something wrong ?

**Comment by gondor** [comment]
This is working for me during my tests.  A couple things I'll need first:

1.  What version of OpenStack are you testing this with?
2.  What version of OpenStack4j are you using?
3.  Are you using one of our connector options? ie. something other than the default of Jersey 2 (okhttp, httpclient, etc)

Thanks

**Comment by sheldonhu** [comment]
1. i deploy openstack juno release by using mirantis.
2. i download openstack4j master branch source code, then i compile the project and package the class file into jar with maven tools.
3. i am using resteasy connector other than Jersey 2.  see the picture below,  the lines i comment will raise the exception.



At 2015-01-15 00:45:23, "Jeremy Unruh" <notifications@github.com> wrote:


This is working for me during my tests. A couple things I'll need first:

What version of OpenStack are you testing this with?
What version of OpenStack4j are you using?
Are you using one of our connector options? ie. something other than the default of Jersey 2 (okhttp, httpclient, etc)

Thanks

¡ª

**Comment by gondor** [comment]
Thanks for the info.  I was able to reproduce this.  I will have a fix sometime this evening.

**Comment by gondor** [comment]
Ok fix checked in.  Let me know if this fixes you.

**Comment by e3ky** [comment]
Hi gondor,

Could you tell me how I should declare the maven dependency in order to get this fix that you've just made.

**Comment by gondor** [comment]
Just add the following for example:

```xml
<dependencies>
	<dependency>
		<groupId>org.pacesys</groupId>
		<artifactId>openstack4j-core</artifactId>
		<version>2.0.2-SNAPSHOT</version>
	</dependency>
	<dependency>
		<groupId>org.pacesys.openstack4j.connectors</groupId>
		<artifactId>openstack4j-jersey2</artifactId>
		<version>2.0.2-SNAPSHOT</version>
		<type>jar</type>
	</dependency>
<!-- some other dependencies, etc -->
</dependencies>

<repositories>
    <repository>
      <id>st-snapshots</id>
      <name>sonatype-snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by sheldonhu** [comment]
the problem has been fixed, great job. 3ks


i add maven assembly plugin into pom.xml under openstack4j directory, when i want to push the change to the remote reposity, i get  error like 'git-receive-pack not permitted'.
how could i push this change ? or I just can't !




ÔÚ 2015-01-15 13:21:26£¬"Jeremy Unruh" <notifications@github.com> Ð´µÀ£º


Ok fix checked in. Let me know if this fixes you.

¡ª

**Comment by gondor** [comment]
Great. As far as the pom goes are you talking about OS4j pom?  If the message is correct (you can't push to the global repo) as it's a security violation.   If your trying to push to your local maven server you can either do a mvn install or add your local distribution repository info to your pom.  See maven's website for usage.
