### ISSUE TITLE
support Host aggregates

### ISSUE THREAD

**Issue by liujunpengwork** [gondor/openstack4j#203]
Hi gondor，the openstack4j is very good。
I have a question that when openstack4j support nova host aggegates feature？
How to add new feature in openstack4j,I want to try add new feature to openstack4j or fix bug for openstack4j. Cloud you publish a guideline that how to add new feature，such as nova host aggregates?

**Comment by gondor** [comment]
1. Currently in the process of adding support for Host Aggregates.  Should be done in the next ~4 days. 
2. I currently don't have any documentation about the actual architecture, etc.  You would need to learn the patterns and layout by looking through our existing source.

**Comment by liujunpengwork** [comment]
How contribute my code to openstack4j? Today,I write and test the code that support host Host aggregates。
But when I push to the github I come with the erro "git-receive-pack not permitted" .Do I have the write permission to openstack4j?

**Comment by gondor** [comment]
Pull Request looks great! Great work and thanks for the contribution.
