### ISSUE TITLE
why i use os4j failed

### ISSUE THREAD

**Issue by frank-zera** [gondor/openstack4j#205]
i download 4j at the version of 2.0.1, and use maven build it in eclipse.
the jdk is 1.6.
but when i authenticate ,it error.
my code is: 
		OSClient os1 = OSFactory.builder()
				.endpoint("http://10.9.128.10:5000/v2.0")
				.credentials("admin","13828e45de1f4e36")
				.tenantName("admin")
				.authenticate();

my error is:
java.lang.ExceptionInInitializerError
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:77)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:41)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:84)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:65)

who can help me?

**Comment by gondor** [comment]
Out of the box if your using the default options then Jersey 2 is not compatible with JDK 1.6.  If you must use JDK 1.6 then you should create a project and declare your dependencies like this in your POM.

```xml
<dependency>
			<groupId>org.pacesys</groupId>
			<artifactId>openstack4j-core</artifactId>
			<version>2.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.pacesys.openstack4j.connectors</groupId>
			<artifactId>openstack4j-jersey2-jdk16</artifactId>
			<version>2.0.1</version>
			<type>jar</type>
		</dependency>
```
The above uses an older Jersey 2 connector which is JDK 1.6 compatible.

**Comment by frank-zera** [comment]
gondor,
first thank you for your reply.
but the problem always exist.
when i got the source code, i move the version of 2.0.2-SNAPSHOT to 2.0.1, and move the artifactId of openstack4j-jersey2 to openstack4j-jersey2-jdk16 in my POM.
my openstack is icehourse.  openstack-java-sdk can work well with my openstack. so i don't know why?

**Comment by gondor** [comment]
Well, I believe it's something just simple setup wise.  We have a large community who use this API with great success.  It supports Grizzly, Havanna, IceHouse and Juno so I know it's not an IceHouse issue.  I have no problem trying to get you going but need more information.  

Any chance you could zip up your project and email it to me at jeremybunruh at gmail.com.      

If not  I'll need more code samples and project setup like your POM, etc.

**Comment by frank-zera** [comment]
gondor，

when i call this code it would be error:
OSClient os1 = OSFactory.builder()
.endpoint("http://10.9.128.10:5000/v2.0")
.credentials("admin","13828e45de1f4e36")
.tenantName("admin")
.authenticate();

i edit the code in the project which use openstack-java-sdk, later i will test os4j in a new project. maybe it's the reason

**Comment by frank-zera** [comment]
gondor，
i create a new project to test os4j, all is ok. 
os4j is so cool.

**Comment by gondor** [comment]
Awesome!
