### ISSUE TITLE
NullPointerException: Find Tenant By Name: Openstack4J 2.0.2-SNAPSHOT

### ISSUE THREAD

**Issue by anhdenday** [gondor/openstack4j#211]
Dear Gondor,
With Openstack4j 2.0.1 it's ok. But with 2.0.2-SNAPSHOT it's through NullPointerException.
  OSFactory.enableHttpLoggingFilter(true);
  Tenant tenant = osClient.identity().tenants().getByName("admin");
  System.out.println("Tenant Id: " + tenant.getId());
  System.out.println("Tenant name: " + tenant.getName());
  System.out.println("Tenant desc: " + tenant.getDescription());
The detail result is below: 

<code>
Jan 22, 2015 10:38:17 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > POST http://xxx.xxx.xxx.xxx:5000/v2.0/tokens
1 > Accept: application/json
1 > Content-Type: application/json
1 > OS4J-Auth-Command: Tokens
{
  "auth" : {
    "tenantName" : "admin",
    "passwordCredentials" : {
      "username" : "admin",
      "password" : "nova"
    }
  }
}

Jan 22, 2015 10:38:17 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Client response received on thread main
2 < 200
2 < Connection: keep-alive
2 < Content-Length: 11788
2 < Content-Type: application/json
2 < Date: Thu, 22 Jan 2015 03:32:37 GMT
2 < Vary: X-Auth-Token
{"access": {"token": {"issued_at": "2015-01-22T03:32:37.138279", "expires": "2015-01-22T04:32:37Z", "id": ......
.....
Jan 22, 2015 10:38:17 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Client response received on thread main
2 < 200
2 < Connection: keep-alive
2 < Content-Length: 119
2 < Content-Type: application/json
2 < Date: Thu, 22 Jan 2015 03:32:37 GMT
2 < Vary: X-Auth-Token
{"tenant": {"description": "Admin Tenant", "enabled": true, "id": "3621ef73a70a4dac8843c6763b5389a8", "name": "admin"}}

Exception in thread "main" java.lang.NullPointerException
	at com.vdco.icloud.openstack.web.auth.TestTenant.main(TestTenant.java:65)

</code>

**Comment by sixlo** [comment]
Same issue.

**Comment by gondor** [comment]
Yes, this is more complex.  Some versions of OpenStack are returning a single result and others are returning a collection.  Newer releases (Juno) appear to be returning a collection.

**Comment by sixlo** [comment]
I'm using Icehouse... The weird thing is that with 2.0.1 it's ok :S

**Comment by anhdenday** [comment]
Me too I also use icehouse and with 2.0.1 ok. I think he already changed something from issue: #201

**Comment by gondor** [comment]
So this is my Dilemma.  Moving forward starting from OpenStack Juno they have changed the response.  Icehouse and below it was one return type and Juno is another.  The reason it works in 2.0.1 is because we were broken against Juno.  Making it work with the new OpenStack API (Juno) breaks Icehouse.  

The solution may be to introduce the ability for you to specify your OpenStack version.  IE. I'm authenticating against IceHouse.  This will allow me to put backwards compatible fixes in for older releases and allow OS4j to evolve against the current release of OpenStack.

**Comment by anhdenday** [comment]
It's ok now Gondor, Thanks you
