### ISSUE TITLE
NetworkType enum doesn't support "vxlan" value 

### ISSUE THREAD

**Issue by e3ky** [gondor/openstack4j#220]
Hello,

I am using openstack4j libs in a project where the network is from type "vxlan".

The issue is that I am not able to set that value as the enumeration only contains: "vlan", "gre", "local" and "flat".

For reference from the API docs:
http://developer.openstack.org/api-ref-networking-v2.html

provider:network_type:      The type of physical network that maps to this network resource. Examples are flat, vlan, vxlan, and gre.

I need to use this value pretty soon so I will appreciate if you could add that soon.

Best Regards,
Martin

**Comment by e3ky** [comment]
And there is a bug (just found it).

I am setting this:
nb.networkType(NetworkType.VLAN);

But it generates:
{
  "network" : {
...
    "provider:network_type" : "local",
...
  }
}

and I am getting the following error:
{"NeutronError": {"message": "Invalid input for operation: network_type value 'local' not supported.", "type": "InvalidInput", "detail": ""}}

It set "local" instead "vlan".
I think it always set "local" which is wrong

**Comment by gondor** [comment]
@e3ky What version of OS4j are you running?  I reviewed the code for network and it appears correct.  I might need a larger code example from you showing how your creating the network, etc.

**Comment by e3ky** [comment]
Hi, 

You can ignore the second comment. It was a mistake from my side.

**Comment by gondor** [comment]
Thanks you, Change added and a new SNAPSHOT is being deployed

**Comment by e3ky** [comment]
Hi,

The issue is fixed and now it works perfectly.

Thank you!

**Comment by gondor** [comment]
Great and no problem!
