### ISSUE TITLE
error attempting to boot a server

### ISSUE THREAD

**Issue by downzero** [gondor/openstack4j#221]
I'm trying to use the sample code from here: http://www.openstack4j.com/learn/compute/servers/
to create an instance of a server from an image:
ServerCreate sc = Builders.server().name("TestInstance").flavor(flavorID).image(imageID).build();
I've created a flavor and a grabbed the imageID of a valid image I have.
When I execute:  Server server = os.compute().servers().boot(sc);

I get the error: 
Exception in thread "main" ClientResponseException{message=Multiple possible networks found, use a Network ID to be more specific., status=400, status-code=BAD_REQUEST}

I've been digging thru the docs but it's not clear how I should specify the networkID.

**Comment by octupszhang** [comment]
List<String> networksId = Arrays.asList(’XXXX‘);
ServerCreate sc= Builders.server().name("TestInstance").flavor(flavorID).image(imageID).networks(networksId);.build()
 Server server = os.compute().servers().boot(sc);

**Comment by gondor** [comment]
Closing due to no response and answer provided by community member.
