### ISSUE TITLE
type in "Getting Started" page. 

### ISSUE THREAD

**Issue by mhshams** [gondor/openstack4j#224]
"openstack4j-okhttp" connector is written "openstack-okhttp" (**4j** is missing) in the getting-started page. 

sorry, I couldn't find out how to fork the documentation to fix the typo myself.

**Comment by gondor** [comment]
Good catch.  I haven't had time to document how to update the docs and make it so it's contribute-able.  It's on my list but lower priority. I'll fix this typo on my next site update this week.

**Comment by gondor** [comment]
Site updated.
