### ISSUE TITLE
NullPointerException in HttpExecutor when ServiceLoader finds no HttpExecutorService

### ISSUE THREAD

**Issue by isartcanyameres** [gondor/openstack4j#225]
When [instantiating HttpExecutor.INSTANCE] (https://github.com/gondor/openstack4j/blob/openstack4j-2.0.1/core/src/main/java/org/openstack4j/core/transport/internal/HttpExecutor.java#L20),  in case ServiceLoader finds no HttpExecutorService,
the initService method tries to use the already NOTdefined LOG ([line 32](https://github.com/gondor/openstack4j/blob/openstack4j-2.0.1/core/src/main/java/org/openstack4j/core/transport/internal/HttpExecutor.java#L32)) causing following stack trace:
```
Caused by: java.lang.NullPointerException
    at org.openstack4j.core.transport.internal.HttpExecutor.initService(HttpExecutor.java:32)
    at org.openstack4j.core.transport.internal.HttpExecutor.<init>(HttpExecutor.java:25)
    at org.openstack4j.core.transport.internal.HttpExecutor.<clinit>(HttpExecutor.java:20)
    ... 27 more
```
Instead, failing with ConnectorNotFoundException("No OpenStack4j connector found in classpath") seems to be the desired behaviour.

This issue could be easily fixed by instantiating LOG before INSTANCE (lines 20 and 21).

This issue has been detected in version 2.0.1.

**Comment by gondor** [comment]
Great catch! Thanks for the extra details

**Comment by isartcanyameres** [comment]
Hey! That was a quick fix! :) :+1: 

The error does no longer appear (in master branch) and now org.openstack4j.api.exceptions.ConnectorNotFoundException: No OpenStack4j connector found in classpath
is thrown as expected.
Thank you!
