### ISSUE TITLE
Creating Network on HP Cloud fails

### ISSUE THREAD

**Issue by akanto** [gondor/openstack4j#226]
Hi,
Creation of a network on HP Cloud fails because the Openstack4j generates the  "router:external" into the request and this parameter is not supported by HP Cloud.
Request:
```
{
  "network" : {
    "name" : "sample-net",
    "shared" : false,
    "admin_state_up" : false,
    "router:external" : false
  }
}
```
Response:
```
{"NeutronError": {"message": "Policy doesn't allow create_network to be performed.", "type": "PolicyNotAuthorized", "detail": ""}}
```
Using Boolean instead of boolean in NeutronNetwork.java and Network.java probably avoids the problem.

Kind regards,
Attila

**Comment by gondor** [comment]
Thank you for the detailed analysis.  Your assumptions appear to be correct.  Just made the changes and re-deployed a SNAPSHOT

**Comment by akanto** [comment]
Thanks. I have tested it successfully.
