### ISSUE TITLE
OSFactory.clientFromAccess(access) doesn't fetch admin scoped tenant/users.

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#227]
Hello,
I can successfully fetch all tenants/users with 

               V2 osClient = OSFactory.builder()
                .endpoint(keystoneAuthUrl)
                .credentials(username, password)
                .tenantName(tenantName);
		osClient.perspective(Facing.ADMIN);
		
		return osClient.authenticate();

But when I do this: 
         
         OSClient osClientFromAccess = OSFactory.clientFromAccess(osClient.getAccess());
         System.out.println("Fetching Scoped Tenants List : ");
         List<? extends Tenant> scopedTenantsosClientFromAccess = osClientFromAccess.identity().tenants().list();

I am able to see only 2 tenants.. 

Reason: Case 1: when I authenticate with admin facing, and use the osClient directly, I get correct results..

Case 2: When I use the above osClient, and want to fetch the same from the Factory, it uses the Public port(5000).

My intention is to use the same osClient over the session, so that for admin I can use it to fetch tenants/users. I am storing osClient.getAccess() in my Users object, so that I can fetch the osClient from OSFactory as and when I request.

Could you tell what would be a good approach here? Note: I am using Spring Mvc.

**Comment by gondor** [comment]
The approach your doing is correct for using it with a Session as well as allowing it to be shared between multiple thread.  Based on what your saying it appears that if we preserved the *Perspective* with the Access object (ie.  in your case knew it was associated with the ADMIN perspective) and then re-instate the perspective on the OSFactory.clientFromAccess you would be ok?

**Comment by vishvesh** [comment]
@gondor  : My use-case is simple, I authenticate a user with tenant scoped & with Facing.Admin (if he is an admin).. So once he is authenticated, I simply store the osClient.getAccess() in my User object (since I cannot store the OSClient object - as when I try to re-use it, I see it's null).. So now, for every request in that session, I want to get my Facing/Scoped OSClient object from Access object.. Here is where I lose the ADMIN perspective.. How can I re-instantiate/get the OSClient object with the desired perspective? After fetching OSClient object from OSFactory.clientFromAccess, can I attach a perspective? Please advice. Thanks.

**Comment by gondor** [comment]
Ok perfect.  I'll add a few different constructors to allow you to specify the perspective when creating a client from Access.

**Comment by gondor** [comment]
Ok I've added the following for convenience. You can now specify the perspective when fetching the client from the factory using the Access object *as well* as changing the perspective from on the client at any point in time (prior was only in creating the client).

```java
OSClient os = OSFactory.clientFromAccess(access, Facing.ADMIN);

// or with an existing client
OSClient os = OSFactory.clientFromAccess(access);
os.perspective(Facing.ADMIN);
```

**Comment by vishvesh** [comment]
Perfect.. This works.. Enhancement confirmed.. Thanks @gondor
