### ISSUE TITLE
Restricting permissions to normal users of OpenStack cloud

### ISSUE THREAD

**Issue by Shaileshwar551** [gondor/openstack4j#229]
HI,
     I would like to know if there is any provision where an admin user can restrict normal users from doing certain tasks such as "Creating an instance", "Uploading an image" etc. (With the assumption that admin has already created a tenant and several users under that tenant)

     Generally an admin user can access Project tab and Admin tab in OpenStack. An end user can access Project tab. From the Project tab, he can do the following tasks:

Instances ---> View, launch, create a snapshot from, stop, pause, or reboot instances, or connect to
                       them through VNC.

Volumes ---> View, create, edit, and delete volumes.
                      View, create, edit, and delete volume snapshots.

MY REQUIREMENT IS:
Allow an end user to only view and create a snapshot from the allocated instance and not allow him to create other instances.

Similarly with Volumes and all.

In a nut shell, I want an end user to only access certain things in Project tab.

Please tell me if it is actually possible. Thank you for any help I can get to understand and implement this idea. Correct me if am wrong here.   

![project](https://cloud.githubusercontent.com/assets/10056711/5933312/bb506c16-a6e4-11e4-9067-e79680aed3a6.png)

**Comment by gondor** [comment]
What your asking for is beyond the scope of the API or even OpenStack's Python API.  You need to modify the "policy.json" for the desired layer.  

For example (directory may be different in your setup) /etc/nova/policy.json .    

This policy file has a list of compute actions, etc and allows you to associate roles to those actions.  See the user guide for more info: http://docs.openstack.org/user-guide-admin/content/admin_cli_manage_projects_users.html

**Comment by Shaileshwar551** [comment]
Thanks Jeremy for the information. I just wanted to know if it was really possible to implement. That's the reason why I posted it.
