### ISSUE TITLE
Ability to set criteria on Ceilometer Statistics

### ISSUE THREAD

**Issue by xiaoreqing** [gondor/openstack4j#233]
How do I use this
List<? extends Statistics> stats = os.telemetry().meters().statistics("cpu_util", 320);
Methods according to the resource only check the information that day cycle.
To put this method to optimize?

**Comment by gondor** [comment]
Ok, code checked in and a new SNAPSHOT deployed.  You can now do something like this:

```java
List<? extends Statistics> stats = os.telemetry().meters()
                                                         .statistics("cpu_util", SampleCriteria.create().resource(resourceId), 320));
```
