### ISSUE TITLE
HP Cloud: Failed to create network port

### ISSUE THREAD

**Issue by akanto** [gondor/openstack4j#236]
Hi,

Building network port on HP Cloud fails, when the following code is used:
```
Port port = os.networking()
				.port()
				.create(Builders.port().name(portName)
						.networkId(network.getId()).build());
```

The Openstack4J generates the extra_dhcp_opts inside the JSON which is unrecognised by HP Cloud.
```
POST https://region-a.geo-1.network.hpcloudsvc.com/v2.0/ports
{
  "port" : {
    "name" : "some-port",
    "admin_state_up" : true,
    "network_id" : "*****************",
    "extra_dhcp_opts" : [ ]
  }
}
```

Response from HP Cloud:
```
{"NeutronError": "Unrecognized attribute(s) 'extra_dhcp_opts'"}
```

Could you take a look at this, please?

Thanks.

Kind regards,
Attila

**Comment by gondor** [comment]
Ok, I know the issue.  Will fix it now.  Sonatype (Maven Repo) is having issues so I'll be able to checkin a fix shortly but won't be able to deploy a new snapshot until their services are back online

**Comment by akanto** [comment]
I have changed the  of @JsonProperty("extra_dhcp_opts" private List<NeutronExtraDhcpOptCreate> extraDhcpOptCreates; to lazy. 
Shall I send a pull request?

**Comment by gondor** [comment]
I already checked it in :)  There was no need to create a new list on construction so essentially did the same thing.

**Comment by akanto** [comment]
Thanks. Looks perfect.
