### ISSUE TITLE
Rackspace URL for images are incorrectly determined

### ISSUE THREAD

**Issue by akanto** [gondor/openstack4j#237]
Hi,

The Rackspace authentication returns the following URL:
```
  "name": "cloudImages",
        "endpoints": [
          {
            "region": "IAD",
            "tenantId": "XXXXX",
            "publicURL": "https://iad.images.api.rackspacecloud.com/v2"
          },
         ...
        ],
        "type": "image"
      },
```
The Access Service also holds the following URL:
```
AccessService{name=cloudImages, type=image, endpoints=[KeystoneEndpoint{region=IAD, publicURL=https://iad.images.api.rackspacecloud.com/v2},
```

When the following lines are invoked:
```
osClient.useRegion("IAD");
osClient.images().list();
```
Openstack4J generates this call:
```
INFO: 1 * Sending client request on thread main
1 > GET https://iad.images.api.rackspacecloud.com/v1/images/detail
1 > Accept: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
```

Could you take a look at this, please?

Kind regards,
Attila

**Comment by gondor** [comment]
Checked in a fix.  Let me know.  This one was a little trickier as older versions and some deployments didn't include the version in the endpoint.

**Comment by akanto** [comment]
Hi,

I can confirm that now it uses the correct base URL (with v2) what is returned by Rackspace. But list of images still returns with 404, because according to the Rackspace documentation, the 'account' number shall be included in the URL:
```
https://dfw.servers.api.rackspacecloud.com/v2/$account/images/detail
```
Reference documentation: http://docs.rackspace.com/servers/api/v2/cs-gettingstarted/content/curl_list_images.html

It looks like the Rackspace API is not really compatible with Openstack or HP Cloud...

Kind regards,
Attila

**Comment by gondor** [comment]
As a workaround could you use images via the Nova service?  For example:
```java
os.compute().images().list()
```
