### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by thantsi** [gondor/openstack4j#240]
Well i get the heap dump analysed by  memory eclipse analyser and i get this leak

One instance of "org.glassfish.jersey.client.JerseyClient" loaded by "os4j.openstack4j" occupies 200,026,744 (95.70%) bytes. The memory is accumulated in one instance of "java.util.concurrent.LinkedBlockingDeque" loaded by "<system class loader>".

I make lots of rest api calls during my execution but is there any way to handle this properly?

p.s max heap size memory: 256mb

**Comment by thantsi** [comment]
Also to note down, i'm using openstack4j-2.0.0-20141030.061459-15-withdeps.jar.

Use global Access variable to reauthenticate to the server each time, instead of creating a new OSClient each time.

**Comment by gondor** [comment]
Are all the REST calls to the same tenant/authentication scheme?  We re-use the Jersey Client on a per tenant/auth scheme basis.

**Comment by thantsi** [comment]
Yes there are from the same tenant and i keep reauthenticate to openstack by using one osclient..I use the diagnostics of compute and retrieve the response and extract some information about the vm runtime.

**Comment by thantsi** [comment]
Maybe the LinkedBlockingDeque has to be bounded somehow and not have it eternally loaded...??

**Comment by thantsi** [comment]
I increased the max heap size and it seems is doing a proper gc!! Maybe the LinkedBlockingDeque is that big up to a number that couldn't be handled by small amount of max heap size memory...

**Comment by gondor** [comment]
Good observation and glad that worked.  We don't use that Queue in OpenStack4j but Jersey 2 does for it's listener registration.
