### ISSUE TITLE
Json fault response of Sahara not consistent with other openstack services

### ISSUE THREAD

**Issue by ekasitk** [gondor/openstack4j#245]
While other services use this pattern
<pre>
{
  "error": {
     "message": "The resource could not be found.",
     "code": 404,
     "title": "Not Found"
  }
} 
</pre>

Sahara uses
<pre>
{
    "error_name": "CLUSTER_NAME_ALREADY_EXISTS",
    "error_message": "Cluster with name 'test-cluster' already exists",
    "error_code": 400
}
</pre>

As I'm working to add more Sahara APIs, what is the recommended way to handle this discrepancy?
1)Open an issue to Sahara developer forum?
2)Handle it in openstack4j. What base classes or methods should I override?

**Comment by gondor** [comment]
We need to just re-map the errors and keep OS4j consistent so users don't have differences between their workflows.

*Map:*
error_name to title
error_message to message
error_code to code

Are you ok with this?

**Comment by ekasitk** [comment]
That seems to be OK but I still cannot see how to make it in OS4j. Can you give more details how my Sahara Service remaps the fault response before passing it to the normal OS4j workflow?

**Comment by gondor** [comment]
Do you have any code you could share with me so I can get a visual with where the mapping is needed, etc.  You could dropbox, some other box, push to your fork and and tell me the classes or email me.
