### ISSUE TITLE
QuotaSet getGigabytes method always returns 0 on openstack4j 2.0.1

### ISSUE THREAD

**Issue by lmcdubo** [gondor/openstack4j#246]
Im using a Openstack Icehouse infra and openstack4j to connect a java client.  It seems that the storage quota value return in getGigabytes is always 0, no matter what the real value is on the openstack infra.

Thx,
/Sebastien

**Comment by lmcdubo** [comment]
Anybody has seen this problem?  Any updates?

Thx
/Sebastien

**Comment by gondor** [comment]
Hi, I looked into this and it looks like it's been deprecated since IceHouse.  It's no longer even listed on their public API.  My response in Juno is also not returning the gigabytes in the raw JSON response.

**Comment by lmcdubo** [comment]
Ok fair enough,

  what we are really looking for then is how to get back the total storage quota i.e. the "Total Size of Volumes and Snapshots (GB)" entry in horizon.  Is there a call to do that?

Thx,
/Sebastien

**Comment by gondor** [comment]
I'm not sure where that is located in Horizon.  Could you let me know what page it's found on so I can try to reverse engineer where the data is coming from?

**Comment by lmcdubo** [comment]
Hi,

  The quotas are explained on this page: http://docs.openstack.org/user-guide-admin/content/cli_set_quotas.html

The particular one I am referring to is the "Gigabytes allowed for each tenant", which is explained in the "Manage Block Storage service quotas" section of the page mentionned above.

Thx & BR,
/Sebastien

**Comment by lmcdubo** [comment]
Additional comment

  we tried 2.0.2 release and the get and setGigabytes are both not functional, on both icehouse and Juno.  Now based on what was said above I understand why this is, but is there a way to get/set storage quotas as per the openstack documentation mentionned above 

 http://docs.openstack.org/user-guide-admin/content/cli_set_quotas.html

Thanks and BR,
/Sebastien

**Comment by gondor** [comment]
See Issue #272.  What your looking for is under the block storage API and not under the existing Compute API.  Issue #272 is the enhancement that will add this functionality under the block storage API.
