### ISSUE TITLE
Support to update Quotas for Tenant and Class

### ISSUE THREAD

**Issue by lmcdubo** [gondor/openstack4j#247]
Using version 2.0.1 on icehouse infra.  

It's relatively easy to get the tenant compute quotas (e.g. Cores, Memory, storage) using the QuotaSetService, but I can't seem to figure out how these value can be updated.  Is it possible?  If so, how?

Thanks
/Sebastien

**Comment by gondor** [comment]
Typically quotas and mappings are defined in the the deployment configuration.  i.e. /etc/nova/nova.conf is one example

**Comment by lmcdubo** [comment]
While this is true that default quotas are usually set in the nova config, it is common (at least in my experience) that these quota are overriden at the tenant level.

Our own cloud client (in which we are using openstack4j to integrate with openstack) readily supports setting compute quotas per tenant.  The native nova REST API supports this as well

I take it that this is not supported yet in openstack4j.  This would be a most useful feature for us.  If need be, we can even help in contributing it.

Best Regards,
Sebastien Dubois, eng.

**Comment by gondor** [comment]
Could you post the nova api doc for setting this. I can confirm for sure if we support this or turn it into an enhancement and add this functionality for you.

**Comment by lmcdubo** [comment]
No problem,

There are many API calls to update quotas.  The most interesting ones for us are

PUT/v2/os-quota-class-sets/​{class_id}​ Update quota
Updates quota for a specified class.

PUT/v2/​{tenant_id}​/os-quota-sets/​{tenant_id}​ Update quotas
Updates quotas for a tenant.

 Many others are documented at http://developer.openstack.org/api-ref-compute-v2-ext under the "Quota class" and "Quota sets" sections

Thx
/Sebastien

**Comment by gondor** [comment]
@lmcdubo Support has been added to 2.0.2-SNAPSHOT and code checked in.  Let me know how it works for you

**Comment by lmcdubo** [comment]
Ok many thanks for the quick turnaround.

We'll try it out and I'll give feedback shortly

Thanks again!
Sebastien

**Comment by gondor** [comment]
Deploying 2.0.2 Release Tonight - Closing - Re-Open or Comment if issue was not resolved

**Comment by lmcdubo** [comment]
Hi,

  We verified that the solution works fine for nova quotas (cpu, memory etc.).

However, there is still a problem with getting and setting storage quotas, as I mentioneend in my other post

https://github.com/gondor/openstack4j/issues/246

Thx & BR,
/Sebastien

**Comment by steweddude** [comment]
Hello,
I also would like to see storage quota update functionality.  

Thanks
Brian

**Comment by gondor** [comment]
Have you looked at https://github.com/gondor/openstack4j/issues/272 ?  This was added in 2.0.2 release

**Comment by steweddude** [comment]
No, I had not. Just did.  I will go grab the latest snapshot.  I appreciate the reply.

Thanks
Brian

**Comment by steweddude** [comment]
Hey Jeremy,

Thanks again for pointing me in the right direction.  Got some code working last week.  Wanted to give you a heads up on a couple of things I found.  Below you will see 2 debug statements I put in, notice the gigabytes and ram fields.  Gigabytes always returns 0, but if you use the CLI to show the quota after the update, the gigabytes value is correctly updated.   Same with the ram field.  Not a big deal as the functionality is what’s important.  You may already be aware of this, if so, please ignore this.

Brian

QuotaSet before  NovaQuotaSet{id=922e342c3a084fdcbd720d80d0214dad, metadataItems=400, injectedFileContentBytes=262144, injectedFileContentBytes=262144, injectedFiles=400, gigabytes=0, ram=ram, securityGroups=10, securityGroupRules=20, cores=16, floatingIps=56, instances=16, volumes=0, injectedFilePathBytes=255, keyPairs=100}

QuotaSet  after NovaQuotaSet{metadataItems=300, injectedFileContentBytes=196608, injectedFileContentBytes=196608, injectedFiles=300, gigabytes=0, ram=ram, securityGroups=10, securityGroupRules=20, cores=12, floatingIps=56, instances=12, volumes=0, injectedFilePathBytes=255, keyPairs=100}
