### ISSUE TITLE
Integrating OpenStack Dashboard inside a Web app & Auto Login to OpenStack

### ISSUE THREAD

**Issue by Shaileshwar551** [gondor/openstack4j#250]
Hi Jeremy,
       I have been using OpenStack4j API to access and manage the OpenStack cloud at my work place.

My requirement is to integrate OpenStack with an application (business application to be specific). What I would want to do is allow access to OpenStack cloud through my application (Web application) i.e., When a user logs in to my app, he can see something like a Dashboard tab inside my app (assume). When he clicks on Dashboard, the OpenStack Dashboard after-sign-in page should appear (i.e, we are bypassing the Dashboard log in).

Here we are validating the user with the same credentials (as my app) to allow access to OpenStack cloud. For this, I will store all OpenStack user credentials in the same database as my app. If the log in succeeds (my app user is also an OpenStack user), the Dashboard page should appear in my app itself. By this, the user doesn't need to authenticate himself twice and also the OpenStack Dashboard loads in my app environment and the user feels like he is accessing the cloud from my app.

I want to know if it is actually possible to integrate Dashboard inside my Web app. Does OpenStack support this and please tell me if OS4j has any API to achieve this.

My next query is:
       I would like to know if I can actually modify OpenStack Dashboard code to suit my requirement (i.e., auto login to OpenStack Dashboard from my Web app). That is, can I embed some JavaScript code inside Dashboard source (at a suitable place) that fills in OpenStack username and password (coming from my business app when I redirect to Dashboard page) and clicks on "Sign In" automatically and takes the user to Dashboard-after-sign-in page?? This happens in a span of seconds and the user doesn't really feel this transition between pages.

     Am asking this because the entire OpenStack seems to be written using Python + Django and I find it difficult to identify the exact location to make these changes as the code is huge.

       Sorry if it is a dumb question, but am trying to implement this idea. Looking forward to some help. I have mailed you the same question just a few weeks back.

Thanks,
Shaileshwar

**Comment by sujaisd** [comment]
Hi Shaileshwar,

If you have the username/password one easy way is to use http post from the javascript and do a iframe login. That should solve it for autologin, without any change in openstack. 

The other way is to write horizon plugin (https://github.com/cloudbuilders/simple_horizon_plugin) with that the user can jump back from horizon to your application. Your app can use some single signon with openstack or both can share same single signon.

If you want to have an SSO, check with keystone configuration and play with that there are few options for them.

Regards,
Sujai

**Comment by Shaileshwar551** [comment]
Thanks. It would be of great help to me if you could show some code snippet for an iframe login. As I mentioned in my question, I would want to auto-fill Dashboard credentials when the user clicks on the Dashboard tab in my Web app. I would like you to clarify if this needs any (code) changes on the OpenStack side (I feel it does, am not sure though). I did have a look at the Dashboard code, but it's huge.

I'll certainly go through the SSO mechanism you suggested. But, could you be a little more clearer about iframe login??

Thanks,
Shaileshwar

**Comment by gondor** [comment]
Better suited for our Google Group since it's not related to OS4j specifics.
