### ISSUE TITLE
GlanceImage fetching incorrect size.

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#251]
osClient.images().list();
        GlanceImage{id=a802dfd4-45dd-448b-b51d-0a1f739751cd, name=does-work, status=ACTIVE, diskFormat=RAW, containerFormat=BARE, size=13200896, owner=c0ead066d9e145328a532a6787634274, minRam=0, minDisk=0, created=Tue Feb 24 17:26:34 PST 2015, updated=Tue Feb 24 17:26:36 PST 2015, isPublic=true, isProtected=false, isDeleted=false, propterties={}, 
}

Here, the size returned is '13200896' (13.2 MB) whereas, the actual image size is : 12.5 MB.. This happens to all the images.. (I have double-checked on horizon.. where it displays correctly)..

**Comment by gondor** [comment]
This is correct.  Horizon is converting Bytes to MB.  OpenStack is returning the exact response that your OpenStack deployment is specifying which is in bytes.  If your displaying this in UI I would expect you to convert bytes to MB.

**Comment by vishvesh** [comment]
I'm converting it to MBs.. The actual size of the image in bytes is somewhere around '12500363' which is what was expected.. but, for all the uploaded images, I am seeing about 4-500 kbs more.. Not sure what's going on..

**Comment by gondor** [comment]
Well the amount you posted above (13200896) actually is 12.58mb when converted.  You can see it here: http://www.matisse.net/bitcalc/?input_amount=13200896&input_units=bytes&notation=legacy

**Comment by vishvesh** [comment]
Silly me.. I was setting 1kb=1000bytes for my calculation :D changed it to 1024.. thanks..
