### ISSUE TITLE
Live Migration Exception not caught by Java Exception.

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#253]
Below is the exception caused for Live VM Migration:

          osClient.compute().servers().liveMigrate(serverId, LiveMigrateOptions.create().host(hostname).blockMigration(true).diskOverCommit(false));
          {"badRequest": {"message": "The instance requires a newer hypervisor version than has been provided.", "code": 400}}

Can this be caught by Exception class? (Very similar to the Create Subnet bug you fixed earlier..)..

**Comment by gondor** [comment]
What is being returned now?  ie.  What is the contents of the ActionResponse object?

**Comment by gondor** [comment]
NM, I just tested this by mocking your response above and it appears to be working properly.  Most cases we don't throw exceptions we return the ActionResponse.  Example:

```java
ActionResponse r =  osClient.compute().servers().liveMigrate(serverId, LiveMigrateOptions.create().host(hostname).blockMigration(true).diskOverCommit(false));

if (!r.isSuccess()) {
   // If you wish you can always throw your own exception, like
   throw new Exception(r.getMessage());
}
```
The action response looks like this if I toString it from your JSON you posted above that is being returned:
```
ActionResponse{success=false, fault=The instance requires a newer hypervisor version than has been provided.}
```

Hope this helps.

**Comment by vishvesh** [comment]
Yea I saw it's returning ActionResponse.. I'm now picking up the Fault & using it to do further processing.. Thanks :)
