### ISSUE TITLE
OSFactory.clientFromAccess doesn't provide perspective configuration.

### ISSUE THREAD

**Issue by mhshams** [gondor/openstack4j#254]
Current "clientFromAccess" method in "OSFactory" sets the perspective to "null". So there is no way to reuse the existing, cached, Access object with "Admin" perspective. 

A method with following syntax in OSFactory would be very useful: 
```
OSClient clientFromAccess(Access access, Facing perspective, Config config)
```

**Comment by gondor** [comment]
On "master" and our deployed 2.0.2-SNAPSHOT these signatures were already added.  Someone requested this last month and we added it.  2.0.2 release is scheduled in roughly a week if your waiting for a full release version.

The signatures that are in 2.0.2-SNAPSHOT are:
```java
OSClient clientFromAccess(Access access, Facing perspective, Config config)

OSClient clientFromAccess(Access access, Facing perspective)
```

**Comment by mhshams** [comment]
thanks. I'll wait for it.
