### ISSUE TITLE
Need a connector with java.net.HttpURLConnection

### ISSUE THREAD

**Issue by krishnabrucelee** [gondor/openstack4j#255]
The current set of connectors depend on 3rd party libraries and the dependency chain grows when we need a small implementation. Having a plain implementation with java.net.HttpURLConnection will help for OSGi based apps.

**Comment by gondor** [comment]
@krishnabrucelee thank you for the contribution. I have reviewed your PR and added some comments.  Once you address (re-commit fixes) / answer them I should be able to merge this.  Thanks again!
