### ISSUE TITLE
VM Migration Exception (ActionResponse fault)

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#257]
Hi Gondor,

I am receiving an Exception while migrating a VM.. 
Since I am relying on the exception/fault.. In ActionResponse fault.. can this message be more informative? Can the enum LiveMigrationAction be parsed & sent properly?

       INFO: 2 * Client response received on thread http-bio-80-exec-8
       2 < 409
       2 < Connection: keep-alive
       2 < Content-Length: 117
       2 < Content-Type: application/json; charset=UTF-8
       2 < Date: Sat, 28 Feb 2015 04:14:01 GMT
       2 < X-Compute-Request-Id: req-86d23e74-4afc-43b4-963c-c8aa3b2fe57a
       {"conflictingRequest": {"message": "Cannot 'os-migrateLive' while instance is in task_state migrating", "code": 409}}

       [org.openstack4j.openstack.compute.functions.ToActionResponseFunction] ERROR: 409,Conflict

       VM Migration Failed :: Cannot 'org.openstack4j.openstack.compute.domain.actions.LiveMigrationAction' while instance in in state of org.openstack4j.openstack.compute.domain.actions.LiveMigrationAction

**Comment by gondor** [comment]
Fix added to 2.0.2-SNAPSHOT (master branch) and new SNAPSHOT deployed to maven.

**Comment by vishvesh** [comment]
Thanks for the fix..
