### ISSUE TITLE
reset vm state support

### ISSUE THREAD

**Issue by octupszhang** [gondor/openstack4j#258]
I suggest that openstack4j should give  support for reseting vm state. It's useful to repair vm  when vm change to error state because of the failures of migration,resize...

**Comment by gondor** [comment]
@octupszhang Ok support added to the server service.  Checked into master branch and a new 2.0.2-SNAPSHOT deployed.

Usage:
```java
ActionResponse ar = os.compute().servers().resetState(serverId, Status.ACTIVE);
```

**Comment by octupszhang** [comment]
Thanks for your help.
