### ISSUE TITLE
2.0.2-SNAPSHOT

### ISSUE THREAD

**Issue by e3ky** [gondor/openstack4j#260]
Hi,

I am not reporting a bug, but rather than want to get some information regarding:

1. When version 2.0.2 will be released?

2. I have some troubles with maven dependencies. I am using the following:
 <dependency>
  <groupId>org.pacesys.openstack4j.connectors</groupId>
  <artifactId>openstack4j-jersey2</artifactId>
  <version>2.0.2-SNAPSHOT</version>
</dependency>

When I make a build, based on this dependency ~25 more sub dependencies are gathered as well.
Two of them are:
openstack4j-core-2.0.2-time_stamp_version.jar
openstack4j-jersey2-2.0.2-time_stamp_version.jar

The issue is that above two jar names are keep changing ~every 1-2 weeks.
Because of that I need to make few manual operations in my project.

Is there a way to make the name of these two jars static no matter of the current release:
openstack4j-core-2.0.2-SNAPSHOT.jar
openstack4j-jersey2-2.0.2-SNAPSHOT.jar

BR,
Martin

**Comment by gondor** [comment]
So unfortunately this is just the nature of SNAPSHOTS.  When we are in development and in between releases we want to release snapshots.  Maven timestamps this automatically which is what your seeing.  This is a common approach across most open source projects.  

What I suggest is if you want to be more selective is clone our master branch and build OpenStack4j yourself.  You can do a "mvn install' which will install the snapshots into your local repo.  Then its your call when you want to take new changes, etc.

We are about to release 2.0.2 which in that case will be a release like our others without the -SNAPSHOT and will never change once deployed.

**Comment by e3ky** [comment]
Thanks for the info. You could close the "issue".
