### ISSUE TITLE
Not closing response when 404 happens

### ISSUE THREAD

**Issue by astone282** [gondor/openstack4j#263]
Hi there, Nice library. Many, many months ago I pulled in OS4J-1.0.1 into my project to use for Identity v2.0 API. At the time, we decided to immediately jump to v3.0 API so I used OS4J as my base and built v3.0 API for identity only. Due to things like PATCH support missing from JDK7, I pulled in ApacheHTTPClient and essentially wired up OS4J, my own IdentityV3 Model/Client implementation wrapping OS4J, and Apache HTTP Connector. Unfortunately I can't release the source code I have, but I did find a bug that I can share:

Short Description:

Using a timeout of 0, the class now called org.openstack4j.core.transport.HttpEntityHandler does not close the response data input stream when a 404 happens and so the HTTP session remains active inside the Apache HTTP thread pool, which will be easily maxed out with a default of 2 threads per URL route. The solution is to make sure to call response.close().  This is not seen for a 200K since a call to readEntity() will actually call close() once the entity is read.

            if (response.getStatus() == 404)
            {
                // response.close() should happen here somewhere.
                try
                {
                    if (ListType.class.isAssignableFrom(returnType))
                        return returnType.newInstance();
                }
                catch (Exception e) {
                    e.printStackTrace();
                }
                if (returnType != ActionResponse.class)
                    return null;
            }

Back story:

For the project I'm on, I had the requirement to validate tokens provided to the system. Therefore, I implemented the Validate Token API (http://developer.openstack.org/api-ref-identity-v3.html). We experienced essentially 'locking' after a short period of time when working with Keystone API. Long story short and after much debugging, the call to GET /v3/auth/tokens was the reason for the locking and I could view leased threads within the HTTP client that were never going to be released. As per the API, Keystone will return a 404 not found if the token provided to validate is not a valid token. So therefore, if I provide a bad token to the request then 404 is returned, and HttpEntityHandler does not close the response. If a good token was received, then the message body contains the token with 200 OK, and a call to Jersey to readEntity will eventually close the response. 

Thanks.

**Comment by gondor** [comment]
@astone282 Thank you for the pointing out this oversight and information regarding your usage and history.  With OpenStack4j 2+ we broke out modules and added many connector options so users don't need to wire in their own connector like you were forced to do in 1.0.1.  

Part of the 2+ implementation is common handlers in the core layer regardless of the connector type chosen.  

Your above example gave me an idea to add a close() method to our HttpResponse interface each connector implements.  This will allow our common layer to call close() and each connector module can handle it appropriate to the technology they are adapting to. 

Thanks again for this info!

Jeremy

**Comment by astone282** [comment]
Yep I saw that. I was hoping to throw away my implementation and grab 2.0.2, and probably just add the few additional APIs that probably won't be in it (such as validate token) so I'll be sure to check back every so often =) for now I'll just keeping running a few of my overridden classes. 

Yep, sounds good. It's a pretty safe bet that if the message body contains something, readEntity() will close the stream and for all else just direct call to close().

Glad I could help,
Cheers.

**Comment by gondor** [comment]
Thanks again for the tips!
