### ISSUE TITLE
Keystone v3 Authentication for Project Scope

### ISSUE THREAD

**Issue by llarsson** [gondor/openstack4j#264]
OpenStack Keystone can be set up to emit tokens with the following scopes:
 - default (unscoped)
 - domain
 - project
 - within another token

Of particular interest to me is the project-level scope, but it appears unsupported by openstack4j at this time. Please consider adding it. If any of the other scopes, apart from domain (which is supported), are unsupported, perhaps other tickets can be created to track the implementation of those.

For details, please see [this curl examples page](http://docs.openstack.org/developer/keystone/api_curl_examples.html).

**Comment by gondor** [comment]
Ok thanks for the info.  I ended up adding support for all scopes.

**Project Scope:**
```java
OSClient os = OSFactory.builderV3()
                       .endpoint("http://identity:5000/v3")
                       .credentials("user", "pass", Identifier.byName("default"))
                       .scopeToProject(Identifier.byName("projectName"), Identifier.byName("domainName"))
                       .authenticate();
```
**Domain Scope:**
```java
OSClient os = OSFactory.builderV3()
                       .endpoint("http://identity:5000/v3")
                       .credentials("user", "pass", Identifier.byName("default"))
                       .scopeToDomain(Identifier.byId("2eyab3"))
                       .authenticate();
```
**Getting a token from a token:**
```java
OSClient os = OSFactory.builderV3()
                       .endpoint("http://identity:5000/v3")
                       .token("49f027afe1bc4565b87e0d7359ecb0a0")
                       .authenticate();
```

I have cleaned up the builder as well and deprecated the following.  The methods still exist but will removed in the future.

**Old Way for Scoped / Unscoped (domainId or domainName):**
```java
OSClient os = OSFactory.builderV3()
                       .endpoint("http://identity:5000/v3")
                       .credentials("user", "pass")
                       .domainName("default") // deprecated
                       .domainId("2e3say") // deprecated
                       .authenticate();
```
**New Way for Scoped / Unscoped:**
Since projects, domains, etc can either be "Name" or "Id" for identification purposes I introduced an "Identifier" object which allows you to fluently go *Identifier.byName("name")* or *Identifier.byId("id")*

This makes things more clean and requires less builder options in scopes, etc.
```java
OSClient os = OSFactory.builderV3()
                       .endpoint("http://identity:5000/v3")
                       .credentials("user", "pass", Identifier.byName("default"))
                       .authenticate();
```

**Comment by llarsson** [comment]
@gondor This fix solved the problem I had perfectly, thank you!

Do you have a time estimate for when 2.0.2 will be the new stable?

**Comment by gondor** [comment]
Hoping to cut a release tonight! Just making one final pass at some issues.

**Comment by aniketpol** [comment]
I am new to openstack4J 
I have installed devstack on ubuntu 16.04
I am trying to get authentication using Openstack4j using:
OSClientV3 os = OSFactory.builderV3()
                .endpoint("http://192.168.1.6/identity/v3")
                .credentials("admin", "123456", Identifier.byId("user domain id"))
                .scopeToProject(Identifier.byId("project id"))
                .authenticate());

What shd i mention in user domain id and project id ?
where can i find it?
