### ISSUE TITLE
Hello, I have a question on the tenant quotas?

### ISSUE THREAD

**Issue by benxiaohai1212** [gondor/openstack4j#265]
os.compute().quotaSets().updateForTenant(tenantId, Builders.quotaSet().instances(15).keyPairs(50).volumes(15).build());
QuotaSetServiceImpl:
        return put(NovaQuotaSet.class, uri("/os-quota-sets/%s", tenantId)).entity(qs).execute();

ClientResponseException{message=quota_set not specified, status=400, status-code=BAD_REQUEST}

http://developer.openstack.org/api-ref-compute-v2-ext.html under the "Quota class" and "Quota sets" sections
Updates quotas for a tenant.
PUT/v2/​{tenant_id}​/os-quota-sets/​{tenant_id}​ Update quotas why?

GET /v2/os-quota-class-sets/​{class_id}​  What is class_id?

Thank you very much!

**Comment by gondor** [comment]
@benxiaohai1212 This hasn't been completed yet.  I have only stubbed it out and aim to finish it this week.  See original issue tracking support to update Quotas.  https://github.com/gondor/openstack4j/issues/247
