### ISSUE TITLE
RouterExternal flag missing in NetworkBuilder interface.

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#268]
public interface NetworkBuilder extends Builder<NetworkBuilder, Network> {

	/**
	 * @see Network#getName()
	 */
	NetworkBuilder name(String name);
	
	/**
	 * @see Network#isAdminStateUp()
	 */
	NetworkBuilder adminStateUp(boolean adminStateUp);
	
	/**
	 * @see Network#getNetworkType()
	 */	
	NetworkBuilder networkType(NetworkType networkType);
	
	/**
	 * @see Network#getProviderPhyNet()
	 */
	NetworkBuilder physicalNetwork(String providerPhysicalNetwork);
	
	/**
	 * @see Network#getProviderSegID()
	 */
	NetworkBuilder segmentId(String providerSegmentationId);
	
	/**
	 * @see Network#getTenantId()
	 */
	NetworkBuilder tenantId(String tenantId);

	/**
	 * @see Network#isShared()
	 */
	NetworkBuilder isShared(boolean shared);
}

As you can see NetworkBuilder isRouterExternal(boolean isRouterExternal) is missing..

Also, in NeutronNetwork class.. it's corresponding implementation is missing..
Similar to : 
                    @Override
		   public NetworkBuilder isShared(boolean shared) {
		         	m.shared = shared;
			     return this;
		   }

Can this be added to the API or can I contribute to this fix?

Thanks.

**Comment by gondor** [comment]
Thanks, should be able to get this in shortly

**Comment by gondor** [comment]
@vishvesh Changes checked in and a new 2.0.2-SNAPSHOT was deployed to maven.  Thanks for pointing this out.  Let me know after you have verified to issue closure.

**Comment by vishvesh** [comment]
@gondor Thanks.. I have verified & it works.. Closing issue..
