### ISSUE TITLE
Option to clear gateway once set.

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#277]
Hi @gondor 

Can we clear gateway once set? I don't see any method to do so.. (Similar to Horizon)

    public class NeutronExternalGateway implements ExternalGateway {

	private static final long serialVersionUID = 1L;

	@JsonProperty("network_id")
	private String networkId;
	
	@JsonProperty("enable_snat")
	private boolean enableSnat = true;
	
	public NeutronExternalGateway() { }
	
	public NeutronExternalGateway(String networkId) {
	  this(networkId, Boolean.TRUE);
	}
	
	public NeutronExternalGateway(String networkId, boolean enableSnat) {
		this.networkId = networkId;
		this.enableSnat = enableSnat;
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getNetworkId() {
		return networkId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean isEnableSnat() {
		return enableSnat;
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public String toString() {
		return Objects.toStringHelper(this).omitNullValues()
				    .add("networkId", networkId).add("enable_snat", enableSnat).toString();
	}

}

**Comment by gondor** [comment]
I'm not sure I quite follow.  Can you please show me the OpenStack4j calls your making to set the gateway and an example you'd expect to remove it (the inverse)

**Comment by vishvesh** [comment]
I am making this call to set gateway::
```
osClient.networking().router().update((osClient.networking().router().get(routerId)).toBuilder().externalGateway(networkId).build());
```
So just wanted to clear/remove this gateway once set..

I tried setting ```externalGateway(null)```, but doesn't work..

**Comment by gondor** [comment]
Try calling **externalGateway( (ExternalGateway) null)**     and see if that fixes it.  That method has many variants and the call example I gave by casting should call the appropriate variant setting it to null.

**Comment by vishvesh** [comment]
Do I have to cast ```null``` to ```ExternalGateway```?

**Comment by vishvesh** [comment]
Call is successful, but this is what is invoked, & it doesn't fix it.
```
PUT http://10.10.73.52:9696/v2.0/routers/8cfcfc6c-2f4d-4c93-8644-3c514d96a1fc
{
  "router" : {
    "name" : "router3",
    "admin_state_up" : true
  }
}

```

**Comment by gondor** [comment]
Do you have the CLI client installed and if so do you know if it can clear the gateway?  If so running it with "-debug" I believe will spit out the call being invoked (JSON, etc).  This could give me an idea of what we're missing.

**Comment by vishvesh** [comment]
Alright, I'll check if I can do that with CLI.. Will let you know the respective call being invoked..

**Comment by vishvesh** [comment]
Alright, so I tried setting & clearing gateway via CLI using the following:

```
--> neutron router-gateway-set 31105097-3183-4f38-ad16-161b055c4ac4 f64af5e7-584f-479c-a2ec-515fb49bf1b6

--> neutron router-list
+--------------------------------------+----------------+--------------------------------------------------------+
| id                                   | name           | external_gateway_info                                  |
+--------------------------------------+----------------+--------------------------------------------------------+
| 31105097-3183-4f38-ad16-161b055c4ac4 | router4        | {"network_id": "f64af5e7-584f-479c-a2ec-515fb49bf1b6"} |

--> neutron --debug router-gateway-clear 31105097-3183-4f38-ad16-161b055c4ac4
     ***Above command corresponds to below request (omitting keystone authentication).. 
--> DEBUG: keystoneclient.session REQ: curl -i -X PUT http://10.xx.xx.xx:9696/v2.0/routers/31105097-3183-4f38-ad16-161b055c4ac4.json -H "User-Agent: python-neutronclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}4a616323ae283a4edfc2785de613e617d5b1fb4d" -d '{"router": {"external_gateway_info": {}}}'
```
So looks like the call goes with an empty string.. I'd tried setting externalGateway to empty string, but call doesn't go through..

**Comment by gondor** [comment]
Ok, this is great.  So maybe I misread but did that clear the gateway for you? Setting an empty string?  Since SNAT is a boolean it wouldn't be part of the objects key so would should be a no-op.

**Comment by vishvesh** [comment]
Alright cool.. Looks like my controller died when I invoked this.. Will try this on monday and let you know if it clears :) Thanks..

**Comment by vishvesh** [comment]
Hi @gondor 
I tried setting networkId as ''

```
{
  "router" : {
    "name" : "router1",
    "external_gateway_info" : {
      "network_id" : "",
      "enable_snat" : false
    },
    "admin_state_up" : true
  }
}

Mar 15, 2015 5:31:26 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Client response received on thread http-bio-80-exec-19
2 < 400
2 < Connection: keep-alive
2 < Content-Length: 92
2 < Content-Type: application/json; charset=UTF-8
2 < Date: Mon, 16 Mar 2015 00:31:00 GMT
2 < X-Openstack-Request-Id: req-f818767c-8f43-4187-9aae-0076a3d07b87
{"NeutronError": "Invalid input for external_gateway_info. Reason: '' is not a valid UUID."}
```

So the call doesn't go through & doesn't clear the gateway.. :(

**Comment by vishvesh** [comment]
@gondor : Any clue on this one?

**Comment by vishvesh** [comment]
Hi @gondor : I have also tried using the below command:
```osClient.networking().router().update(
				(osClient.networking().router().get(routerId)).toBuilder().externalGateway(new NeutronExternalGateway(null, (Boolean) null)).build());```

No Luck :\ Any way I could bypass OS4J and invoke the rest manually?

**Comment by gondor** [comment]
Fix checked in and re-deployed.  To clear the gateway do the following. This is based on your example above.

New builder option on Router now available: clearExternalGateway()
```java
osClient.networking().router().update((osClient.networking().router().get(routerId)).toBuilder().clearExternalGateway()).build());
```

Let me know

**Comment by vishvesh** [comment]
@gondor : Awesome.. Thanks for the fix & timely response.. I managed to by-pass OS4J & had it working.. now reverted back to your fix :)

**Comment by gondor** [comment]
Great! :)
