### ISSUE TITLE
Option to fetch Attached Interfaces.

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#278]
Hi @gondor 

Apart from the below API:
Attaching / Detaching External Interfaces

      // Attach an External Interface
      RouterInterface iface = os.networking().router()
                          .attachInterface("routerId", AttachInterfaceType.SUBNET, "subnetId");

       // Detach an External Interface
       RouterInterface iface = os.networking().router()
                          .detachInterface("routerId", "subnetId", null);

I don't see an API to fetch attached interfaces to a Router.. Is it possible to implement one?

**Comment by gondor** [comment]
Reading the API docs it states that this results in a Port.  Have you tried listing ports? I believe the association you created will be within the list.  Let me know your results.

**Comment by vishvesh** [comment]
I was thinking of doing the same.. Just wanted to clarify if I should expect it in the API :) So basically fetching all ports &  then filtering it further down?

**Comment by gondor** [comment]
Well, I kind of need you to verify first.  ie.  Fetch all ports and see if it's there.  If it is then I may be able to add some sort of filtering in the API to make this easier.  Don't want to do this if it's not the solution so just need some verification :)

**Comment by gondor** [comment]
Also to help verify if you find the Port in the listings has the following:

this should be one of the values:  "device_owner":"network:router_interface",
as well as the "device_id" should be the ID of your router when you did the attachment.

If the above holds true I could add filter options on ports so you can get all ports associated with the specified router ID, etc.

**Comment by vishvesh** [comment]
As you mentioned, the device_id should be the ID of the router.. and once of the following values as the filter..
```
"device_owner":"network:router_interface"
"device_owner":"network:router_gateway"
```
Can this be added to the API, or I could help contribute?

**Comment by gondor** [comment]
Yes, I should be able to get this in.  I'm currently re-installing my main deployment so won't be able to test but I should be able to get this in sometime this weekend.  Will need you to test for me once I do.

**Comment by vishvesh** [comment]
FYI: I am already filtering ports for specific network & subnet since it's not in the API..

**Comment by vishvesh** [comment]
Sure I'll do that..

**Comment by vishvesh** [comment]
Any update on this one?

For the time being: I am fetching the ports as following:
```
List<Port> filteredList = Lists.newArrayList();
	for (Port port : osClient.networking().port().list()) {
		if(port.getDeviceId().equalsIgnoreCase(routerId))
			filteredList.add(port);
	}
return filteredList;
```
And then further processing on `deviceOwner`

**Comment by gondor** [comment]
Ok, code checked in and a new maven snapshot deployed.

The advantage with the code I added is the filtering happens on the server (OpenStack) vs within OpenStack4j.

Examples:
```java
// Filter by deviceId (aka routerId, etc)
os.networking().port().list(PortListOptions.create().deviceId("fc8846b1-67ae-46d6-a2f8-6e2ce3c753e7"));

// Filter by other options
os.networking().port().list(PortListOptions.create().deviceOwner("network:floatingip").adminState(true));

// etc.
os.networking().port().list(PortListOptions.create().macAddress(someMac).tenantId(someTenant));
```

**Comment by vishvesh** [comment]
Awesome.. Thanks :)
