### ISSUE TITLE
NullPointerException calling methods on OSClient in clojure

### ISSUE THREAD

**Issue by gonewest818** [gondor/openstack4j#280]
I'm trying to use openstack4j via clojure's java interop as follows:

```
; authenticate and get OSClient
(defn get-osclient []
  (-> (OSFactory/builder)
      (.endpoint "https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/")
      (.tenantName "my-tenant")
      (.credentials "the-login" "the-password")
      (.authenticate)))

(def os (get-osclient))

; and then, e.g. to list containers can do this:
(-> os (.objectStorage) (.containers) (.list))
```

The problem is that, relatively soon afterward, performing operations through 'os' will generate an exception:
```
NullPointerException   org.openstack4j.openstack.internal.BaseOpenStackService.builder (BaseOpenStackService.java:84)
```

When this happens I can re-authenticate and continue forward.  In fact, being lazy I am now doing this every time:
```
; get a fresh token every time, and use it immediately
(-> (get-osclient) (.objectStorage) (.containers) (.list))
```

But that's ugly and it's an extra rest call to keystone that I'd rather not be making unless I actually need to.  Can someone confirm if there is a cleaner way to handle this?

Thanks

**Comment by gondor** [comment]
The scenario's you listed above can be auto seen within Java if your using the same client between threads.   In these situations I have documentation on how to use the existing client in a multi-threaded environment.  

Could this be something your doing in your Clojure code?

**Comment by gonewest818** [comment]
I'll admit this is my first ever experiment in clojure.  I'm not explicitly using futures or any other threading constructs. It's true the entire repl is a separate process from the associated Emacs session but that isn't relevant, I don't think. 

I'll try a standalone repl to be certain...

Thanks

**Comment by gonewest818** [comment]
I've reproduced this by hand in a leiningen repl in exactly the same way.  At the prompt I am simply doing this call 
```
(-> os (.objectStorage) (.containers) (.list))
```
periodically until the NullPointerException is reached.

**Comment by gondor** [comment]
To be honest I've never dabbled in clojure so this will be a little more difficult to see what's needed to address this.  Do you have a sample project you could send me in zip form via email? If so jeremybunruh [at] gmail .   

I can't promise anything but I'll look into it and see if something stands out.

**Comment by gonewest818** [comment]
I will cobble something together for you.

In the meantime I am going to try caching the "Access" object via OSClient.getAccess() and OSFactory.clientFromAccess(), which in clojure works out like this:

```
(defn get-access 
  "get Access object from an instance of OSClient"
  [osclient]
  (.getAccess osclient))

(defn get-client-from-access
  "get OSClient object from an instance of Access"
  [access]
  (OSFactory/clientFromAccess access))

; cache Access as acc
(def acc (get-access (get-osclient)))

; and use acc to list all containers
(-> (get-client-from-access acc) (.objectStorage) (.containers) (.list))
```

**Comment by gondor** [comment]
Actually, thats a good idea.  Clojure may be handling threads differently and the caching and clientFromAccess is what we use in Java with multi-threads.  

Let me know if that fixes the issue.  At the very least it's a workaround I could document against Clojure.

**Comment by gonewest818** [comment]
So far it's working fine.

Incidentally, in the code I sent you I setup log4j and you can see this sort of thing going on in the logs:

```
702882 [nREPL-worker-2] INFO os4clj.core null - foo
713834 [nREPL-worker-2] INFO os4clj.core null - foo
781999 [nREPL-worker-3] DEBUG org.openstack4j.core.transport.internal.HttpExecutor null - Executing Request: https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/ -> /tokens
987351 [nREPL-worker-4] DEBUG org.openstack4j.core.transport.internal.HttpExecutor null - Executing Request: https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/ -> /tokens
```

Where the thread name is "nREPL-worker-#" for some value of #.   So there apparently are multiple threads, something I didn't know about nREPL.  Sorry for the false alarm...

**Comment by gondor** [comment]
So funny you posted this.  I got your email and setup lein and ran your project.  I was too able to reproduce it and then kept going by my gut with the multi-threading an nREPL.  After further reading and realizing that nREPL is just a server it started to make sense.  I started printing the current thread (not with log4j since it was  beyond my scope) and started seeing the worker thread changing when invoked.

Your posting is definitely more elegant and it clearly demonstrates the multi-thread work happing.  No problem and I'm glad you brought this up since it was nice to play with Clojure for a few mins and seeing OS4j running within it.

Jeremy

**Comment by gonewest818** [comment]
Great. I'm back to playing with os4j in clojure. As you've seen, the fluent interface plays out nicely in clojure with the -> macro, nice and readable.

**Comment by gondor** [comment]
I agree.. I'm willing to setup an examples directory in OpenStack4j if you wanted to contribute a base project which sets things up to use Clojure.  This might be nice for the community.  If your willing to do this then let me know and I can tell you where to put it in your fork & future pull request for others.

**Comment by gonewest818** [comment]
Sure, just let me know what directory you need.  Can take that offline in email (the one I used to send the sample code). Meanwhile I'll keep going with what I'm doing and make sure it's working reasonably.
