### ISSUE TITLE
Extending ceilometer alarms functionality

### ISSUE THREAD

**Issue by e3ky** [gondor/openstack4j#284]
Hi,

I've implemented  create alarm and delete alarm functionality for Telemetry Ceilometer alarms.
I don't have rights to add the new source code to github repo.
Could you assist me to push my code ?

PS: The changes are in:
core/src/main/java/org/openstack4j/api/Builders.java
core/src/main/java/org/openstack4j/api/telemetry/AlarmService.java
core/src/main/java/org/openstack4j/model/telemetry/Alarm.java
core/src/main/java/org/openstack4j/openstack/telemetry/domain/CeilometerAlarm.java
core/src/main/java/org/openstack4j/openstack/telemetry/internal/AlarmServiceImpl.java
+ added new file:
org/openstack4j\model\telemetry\builder\AlarmBuilder.java

**Comment by gondor** [comment]
Great Thank you! Can't wait to review.

From your Fork you will want to go to Pull Requests and create a new one.  This will take the changes you've made along with a comment/docs describing the changes and send them to me for approval into this code line.

**Comment by e3ky** [comment]
Hi.,

I've just made a Pull Request.
As it is my first time doing such thing, please check if everything is fine and tell me if something is wrong.

By the way in the Google group there was a guy asking for alarms enhancements from two weeks ago.

**Comment by gondor** [comment]
Hi thank you.  Everything looked great.  Couple formatting issues like no spaces between brackets, etc but nothing I can do in one pass to apply the formatting.    Approved merged and a new maven snapshot has been deployed.
