### ISSUE TITLE
ResetAction not working against a Server

### ISSUE THREAD

**Issue by gondor** [gondor/openstack4j#285]
As noted in Pull Request #283 the ResetStateAction is not liking the capital state when sending a reset action to the server.  I agree with the underlying issue but am in favor of keeping the enum in tact and fixing the marshaling instead.  

This issue address #283 and preserves the initial implementation.

**Comment by gondor** [comment]
@octupszhang Please review.  Should address your findings.

**Comment by octupszhang** [comment]
It work well now and I have closed my pull request.
