### ISSUE TITLE
Error while downloading the object from container

### ISSUE THREAD

**Issue by tajinders** [gondor/openstack4j#286]
I am able to create a container and have added 2 objects to it. However, when I try to fetch the objects present in the container I get errors. I am using objectstack4j library

Print Statements from the Java Code
Container Details : SwiftContainerImpl{name=contentpack, count=2, total size=965}

Object Details:SwiftObjectImpl{name=/my/nested/path, last_modified=Tue Mar 17 22:12:19 EDT 2015, mimeType=application/directory, size_bytes=0, ETag=d41d8cd98f00b204e9800998ecf8427e, directory=true}

Object Details:SwiftObjectImpl{name=tajinder.xml, last_modified=Tue Mar 17 22:23:08 EDT 2015, mimeType=application/octet-stream, size_bytes=965, ETag=29d2343ba76c4793ba3cc46a4b30728a, directory=false}

Code Snippet : 
	List<? extends SwiftObject> swiftObject = openstackSwift.getAllObjects("contentpack");
			if(!swiftObject.isEmpty()){
			for(SwiftObject swiftobj : swiftObject){
					System.out.println("Object Details:"+swiftobj.toString());
					if(!swiftobj.isDirectory())
							swiftobj.download();
					

The statement swiftobj.download(); cause the below error.			
Error: 
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageObjectServiceImpl.download(ObjectStorageObjectServiceImpl.java:177)
	at org.openstack4j.openstack.storage.object.domain.SwiftObjectImpl.download(SwiftObjectImpl.java:102)
	at org.openstack4j.openstack.storage.object.domain.SwiftObjectImpl.download(SwiftObjectImpl.java:97)
	at test.OpenSwift.SwiftOpenStack.main(SwiftOpenStack.java:123)

**Comment by tajinders** [comment]
Any help is highly appreciable. This part is very critical for our project. 
Thanks in Advance.

**Comment by gondor** [comment]
What call is **openstackSwift.getAllObjects("contentpack")** making.  I need to see how it's calling OpenStack4j so a code example would help.

What version of OpenStack4j are you running?

**Comment by tajinders** [comment]
Thanks for your reply!
I am using openstack4j-core-2.0.2-SNAPSHOT. Below are the function calls. 

	public OSClient OSAuthentication() {
	os = OSFactory.builder().useNonStrictSSLClient(true)
				.endpoint("https://xxxxxxxxxxx/v2.0")
				.credentials("xxx","xxxx")
				.tenantName("xxxxxxxxx")
				.authenticate();

		return os;
	}
	public List<? extends SwiftObject> getAllObjects(String containerName)
	{
		List<? extends SwiftObject> objects = os.objectStorage().objects().list(containerName);
		return objects;
	}

	public void addContainer (String containerName){
		os.objectStorage().containers().create(containerName);
	}

	public String addObject(String containerName, String objectName, File  file ){
		String etag = os.objectStorage().objects().put(containerName, objectName, Payloads.create(file));
		return etag;
	}

Maven dependency 

<dependency>
			<groupId>org.pacesys</groupId>
			<artifactId>openstack4j-core</artifactId>
			<version>2.0.2-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.pacesys.openstack4j.connectors</groupId>
			<artifactId>openstack4j-httpclient</artifactId>
			<version>2.0.2-SNAPSHOT</version>
		</dependency>
	</dependencies>

Thanks
Taj

**Comment by gondor** [comment]
Ok I believe I have a workaround until I checkin the fix.  Try this and let me know if it works.

Change:
```java
List<? extends SwiftObject> objects = os.objectStorage().objects().list(containerName)
```
To:
```java
List<? extends SwiftObject> objects = os.objectStorage().objects().list(containerName, ObjectListOptions.create())
```

**Comment by tajinders** [comment]
It worked, thanks a lot :)

**Comment by gondor** [comment]
Great, I'll commit a fix for the other call you were making. Just wanted to verify with you first.

**Comment by gondor** [comment]
Code checked in and a new 2.0.2-SNAPSHOT deployed. Let me know! :)

**Comment by gondor** [comment]
Deploying 2.0.2 Release Tonight - Closing - Re-Open or Comment if issue was not resolved

**Comment by tajinders** [comment]
Thanks. Its working fine.

Have a great weekend.

Thanks.
