### ISSUE TITLE
AbsoluteLimit: `maxServerGroups` and `maxServerGroupMembers` are missing

### ISSUE THREAD

**Issue by da-z** [gondor/openstack4j#289]

**Comment by gondor** [comment]
Code checked in and a new 2.0.2-SNAPSHOT deployed. Let me know! :)

**Comment by gondor** [comment]
Deploying 2.0.2 Release Tonight - Closing - Re-Open or Comment if issue was not resolved

**Comment by da-z** [comment]
Works fine, thank you!
