### ISSUE TITLE
CreatePort command not working properly

### ISSUE THREAD

**Issue by e3ky** [gondor/openstack4j#292]
Hi,

After some functionality has been modified in last week or two, now createPort command is not working as expected.
It is working fine with openstack4j-core-2.0.2-20150206.062619-18.jar but now it doesn't. Now fixed_ips block is missing in the request body:

Source code:
```
PortBuilder pb = new Builders().port();
pb.networkId("some network id");
pb.name("port name");
pb.adminState(true);
pb.fixedIp("10.10.10.10", "some subnet id");
Port port = os.networking().port().create(pb.build());
```
Previous behavior:
```
{
  "port" : {
    "name" : "port name",
    "admin_state_up" : true,
    "fixed_ips" : [ {
      "ip_address" : "10.10.10.10",
      "subnet_id" : "some subnet id"
    } ],
    "network_id" : "some network id"
  }
}
```
Current behavior:
```
{
  "port" : {
    "name" : "port name",
    "admin_state_up" : true,
    "network_id" : "some network id"
  }
}
```
I assume it is good to introduce some unit testing to verify nothing old breaks the old functionality.

**Comment by e3ky** [comment]
I think the bug will be fixed by adding below line in below method:
org.openstack4j.openstack.networking.domain ->


c.fixedIps = (Set<NeutronIP>) port.getFixedIps();

public static NeutronPortCreate fromPort(Port port) {
		NeutronPortCreate c = new NeutronPortCreate();
		c.name = port.getName();
		c.networkId = port.getNetworkId();
		c.adminStateUp = port.isAdminStateUp();
		c.macAddress = port.getMacAddress();
		c.tenantId = port.getTenantId();
		c.securityGroups = port.getSecurityGroups();
		
		return c;
	}

**Comment by gondor** [comment]
Ok, I need a little more info. Your first example is showing a brand new port being created.  Where as your last comment is showing a typical update of an existing port or clone of an existing by doing the *fromPort*.  

I understand the JSON is different but during an update operation you only send what is to be changed vs all elements again.  A create is everything that has a value.   

Which example should I look into (first comment or 2nd) ?

**Comment by e3ky** [comment]
So the code I am executing is always the same:
```
PortBuilder pb = new Builders().port();
pb.networkId("some network id");
pb.name("port name");
pb.adminState(true);
pb.fixedIp("10.10.10.10", "some subnet id");
Port port = os.networking().port().create(pb.build());
```

The difference is the result of this code execution now and before.
I've made some debugging and what I posted in my second post is something that is used in crate command from my first post.

As you can see below, create command is using fromPort method:
```
    public Port create(Port port) {
        checkNotNull(port);
        checkNotNull(port.getNetworkId(), "NetworkId is a required field");
        return post(NeutronPort.class, uri("/ports")).entity(NeutronPortCreate.fromPort(port)).execute();
    }
```

**Comment by e3ky** [comment]
I've tested locally and by adding just that one line, the bug is fixed. 
```
c.fixedIps = (Set<NeutronIP>) port.getFixedIps();
```
in org.openstack4j.openstack.networking.domain -> NeutronPortCreate
```
public static NeutronPortCreate fromPort(Port port) {
        NeutronPortCreate c = new NeutronPortCreate();
        c.name = port.getName();
        c.networkId = port.getNetworkId();
        c.adminStateUp = port.isAdminStateUp();
        c.macAddress = port.getMacAddress();
        c.tenantId = port.getTenantId();
        c.securityGroups = port.getSecurityGroups();

        return c;
    }
```

Can you add it in the code, or I can make a pull request?

**Comment by gondor** [comment]
Sorry, I forgot to flag the checkin yesterday with this issue number.  This was checked in and deployed to maven (2.0.3-SNAPSHOT) yesterday.

See https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPortCreate.java

for changes.

**Comment by e3ky** [comment]
Thank you.

I can confirm that now it works fine.
