### ISSUE TITLE
how can I create “zone” use api？

### ISSUE THREAD

**Issue by houyu533** [gondor/openstack4j#300]
I can get zones from api， but i can not find create zone function. i used version 2.0.1.

**Comment by octupszhang** [comment]
just create hostaggrate with a new zone name,then you will get your zone.

**Comment by octupszhang** [comment]
just create hostaggrate with a new zone name,then you will get your zone.

**Comment by houyu533** [comment]
thank you for your answer, but I can not understand, I hope create a new zone from api.  please give me a example code.

**Comment by octupszhang** [comment]
That's the only way in both openstack and openstack4j,openstack manages zone and hostaggreate together.

**Comment by houyu533** [comment]
thank you @octupszhang , I understand your mean.
