### ISSUE TITLE
how can I get hosts from "nova" zone?

### ISSUE THREAD

**Issue by houyu533** [gondor/openstack4j#301]
nove zone is default and it have not HostAggregate. I hope use api like "nova host-list"  openstack command.

**Comment by octupszhang** [comment]
List<? extends AvailabilityZone> zones = os.compute().zones().list(true);
		Map<String, Map<String, ? extends NovaService>> hosts = null;
		for (AvailabilityZone az : zones) {
			if (az.getZoneName().equals(zoneId)) {
				hosts = az.getHosts();
				break;
			}
		}

**Comment by houyu533** [comment]
thank you very mutch， this function can find zone 's hosts and  I find other function find hosts list.
excample:
           os.compute().hypervisors();
