### ISSUE TITLE
Unable to catch assign floating IP error.

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#307]
![image](https://cloud.githubusercontent.com/assets/1413029/6883850/8a2ce7c6-d57f-11e4-9052-dded02dcbb48.png)

I am only able to catch the bottom error (via OS4J API).. Is there any way I could catch the top error as well (The real reason why adding floating IP failed)?

**Comment by gondor** [comment]
Have you turned on HttpLogging in OS4J to see if we're even receiving the top error your looking for?  If we are then I can definitely capture it but sometimes the rest endpoints in OpenStack don't respond with the same error's as Horizon see's.   If you do see it in the capture can you post it so I can add a fix for you?

Thanks.

**Comment by vishvesh** [comment]
```
1 > POST http://10.xx.xx.xx:8774/v2/84dee99320ad423e9e6ae7601ae27541/servers/0d797266-bc7d-44cc-accc-46557ac8511f/action
{
  "addFloatingIp" : {
    "address" : "99.0.0.2",
    "fixed_address" : "95.0.0.2"
  }
}

Mar 28, 2015 9:57:19 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Client response received on thread http-bio-80-exec-1
2 < 400
2 < Connection: keep-alive
2 < Content-Length: 82
2 < Content-Type: application/json; charset=UTF-8
2 < Date: Sun, 29 Mar 2015 04:56:36 GMT
2 < X-Compute-Request-Id: req-f9148b0c-5ea1-461c-907f-6e614a29f750
{"badRequest": {"message": "Error. Unable to associate floating ip", "code": 400}}
```

I don't see the first message.. So there is not way to capture it?

**Comment by gondor** [comment]
Only thing that comes to mind is you can associate floating ip's through our compute service and network (neutron) service.  Horizon may be using the opposite your trying.  For example if your doing it through OS4J compute then Horizon may be doing it the Neutron route (os.networking().floatingIp().etc).

**Comment by vishvesh** [comment]
Ohh the urls are same for both? Let me give it a try :)

**Comment by vishvesh** [comment]
@gondor : Got it.. After using Neutron API to assign floating ip, it threw the error.. I'll use that one from now.. Cheers :+1:

**Comment by vishvesh** [comment]
@gondor : 
```
osClient.networking().floatingip().associateToPort(floatingIpId, portId)

PUT http://10.10.73.52:9696/v2.0/floatingips/15c5df19-a203-4573-8543-7cc91e81c2d1
{ "floatingip": { "port_id":"76a90c6f-4af6-4732-b81b-df56fb0b5d94" } }

2 < X-Openstack-Request-Id: req-9f9059b9-cbab-45a2-aea0-08cd1d160f91
{"NeutronError": {"message": "External network bf20962a-177a-428f-ae9f-4a306d77185e is not reachable from subnet 0ced334e-b747-496d-87aa-d763258a01c6.  Therefore, cannot associate Port 76a90c6f-4af6-4732-b81b-df56fb0b5d94 with a Floating IP.", "type": "ExternalGatewayForFloatingIPNotFound", "detail": ""}}
```

Can't catch this Exception :( Can it be propagated, or added to ActionResponse (like it is for `ActionResponse response = osClient.compute().floatingIps().addFloatingIP(server, serverFixedIp, ipAddress)` ?

**Comment by gondor** [comment]
Ok I've added the standard propagation (exception thrown) but will need you to test.  If it's not working then the standard 404 isn't being returned by OpenStack so I will need to wire logging trace to propagate it properly.   New snapshot deployed and source checked in.

**Comment by vishvesh** [comment]
Great! It does return the expected error now.. Thanks :+1:
