### ISSUE TITLE
[Feedback / dev request] Missing error codes in ActionResponse

### ISSUE THREAD

**Issue by nmarchev** [gondor/openstack4j#316]
Hello,

I'm using openstack4j for working with IBM Openstack services (ICOS) and I see a potential issue in the way how I have to handle the errors. Many of the operations returns ActionResponse which contains the action status and the error message if it has failed. As some of the errors have to be handled programmatically or are treated as warnings where other must be reported to the end customer the exact error should be recognized in the code. But there is no stable error code, instead there are text messages which could be changed some day.
For example deleting resource which does not exists is not a real error and should be treated not in the same way as if the resource cannot be deleted because it is in use. Currently I check if the error message contains "does not exist" for security groups and rules, "not found" for key pairs and "could not be found" for servers and volumes. Even small change in the wording could invalidate my code and this will happen in a part which is behind the mocks for the automated tests.

Regards,
Nikola

**Comment by vishvesh** [comment]
Why not react to the error code instead of the message itself? I know ActionResponse class does not have a placeholder for error status codes.. But you could always request that if that might help you..

**Comment by gondor** [comment]
I liked the suggestion and this was low impact to add to the ActionResponse.  You can now do a getCode() call from the action response which will return to you the underlying status code (ie. 404, 409, etc)

I have checked in the code and deployed a new 2.0.3-SNAPSHOT to maven.

**Comment by nmarchev** [comment]
I already changed the code to check for 404 when deleting and it works for all resources.
Thank you
