### ISSUE TITLE
Throw exception:"Missing required credential: X-Auth-User" when create stack with autoscalingGroup resource

### ISSUE THREAD

**Issue by dreadbird** [gondor/openstack4j#317]
Hello,@gondor
I have a problem.
When I use the api os.heat().stacks().create(sc) to create a stack with a autoscaling template.
throw a exception  as follow:
=====================================================
ClientResponseException{message=Missing required credential: X-Auth-User, status=400, status-code=BAD_REQUEST}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:98)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:40)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:19)
	at org.openstack4j.connectors.jersey2.HttpResponseImpl.getEntity(HttpResponseImpl.java:62)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:169)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:163)
	at org.openstack4j.openstack.heat.internal.StackServiceImpl.create(StackServiceImpl.java:31)

about the autoscaling template, as follow:
=====================================================
heat_template_version: 2013-05-23
description: AutoScaling Wordpress
parameters:
  image:
    type: string
    description: Image used for servers
  key:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the web servers
  network:
    type: string
    description: The network for the VM
    default: private	
resources:
  asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 10
      resource:
        type: OS::Nova::Server
        properties:
            key_name: { get_param: key }
            image: { get_param: image }
            flavor: { get_param: flavor }
            networks: [{network: {get_param: network} }]
  web_server_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: 1
  web_server_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: -1

heat only validates credentials for the created 
stack in certain circumstances ,specifically if a ScalingPolicy, HARestarter, or 
WaitConditionHandle is contained in the teamplate, see 
https://github.com/openstack/heat/commit/af238fbd
=====================================================
so,in the request header,need 'X-Auth-User' and 'X-Auth-Key'
I find in the org.openstack4j.core.transport.HttpRequest.RequestBuilder.build()
only put the ClientConstants.HEADER_X_AUTH_TOKEN into the headers.

have you found this problem?

**Comment by gondor** [comment]
This is interesting actually since it's not a requirement in the standard OpenStack API documentation and we have many people creating stacks.  Are you using a vendor such as Rackspace, etc or is this an in house private deployment and if so what version of OpenStack?

**Comment by dreadbird** [comment]
I work on the Icehouse,and only OpenStack,not use any other vendor.
You mean,this is a problem on icehouse? and openstack4j can not work on icehouse?

**Comment by gondor** [comment]
Quick google search this appears to be a bug in IceHouse.  I'm currently running Juno where the fix was made and don't see this issue.   https://bugs.launchpad.net/heat/+bug/1302578

**Comment by dreadbird** [comment]
@gondor  thanks for your answer, I will try it on the Jnuo.
And I suggest to describe this problem in the Openstack4j docs or README, that will better for all users.

**Comment by frankiezdh** [comment]
I get this problem too. I use juno. And I find that. When the template using some links, the exception is thrown。Below is the template file. But it's success to create stack in commoand line by using the same template file。
heat_template_version: 2013-05-13
resources:
  myinstance:
    type: http://1.1.1.1/yaml
