### ISSUE TITLE
how do I get the host status?

### ISSUE THREAD

**Issue by alawi** [gondor/openstack4j#320]
Hi, 

I'm trying to get the status of host, similar to what you see in horizon host aggregate page in Horizon (service up/ service down). 

Is there any API for that? if so could you please help me finding it.

Thanks

**Comment by gondor** [comment]
If you do a `os.compute().zones().list(true)` call you'll get back a list of AvailabilityZones.  Each zone has a name, overall state (the available true/false in horizon) and a Map of Hosts to Services.  Horizon is grabbing the map of hosts and iterating through the value of each host (typically a single host) and if they are all true for "active" then "all services up".  Just system out the call above and you'll get an idea of what I'm describing.  Hope this helps.



```java

**Comment by alawi** [comment]
Thank you gondor for responding to my query, that helps.
