### ISSUE TITLE
Option to add headers in requests, esp. 'X-newest' in GET requests in swift

### ISSUE THREAD

**Issue by symcssn** [gondor/openstack4j#321]
I have not seen any way to specify any header name and value pairs other than the ones provided by the "options." I looked inside DownloadOption class and the only headers it specifies are conditionals. I think it would be very useful to allow the user to specify header name/value pairs in requests in case a certain option is not implemented specifically by OS4j. I've run into a situation where I need to GET the most recent object from Swift and I cannot specify through any of the option classes to do that.

If the feature is already implemented I'd appreciate a pointer very much. :)

Thanks!!

**Comment by gondor** [comment]
Ok, option added for any user defined header to be added into the request.

Example:
```java
DownloadOptions.create().header(name, value);
```

**Comment by symcssn** [comment]
Thanks! :)
