### ISSUE TITLE
setting external gateway to router in api returns not authorized, but the same is allowed via CLI

### ISSUE THREAD

**Issue by tyonchev** [gondor/openstack4j#323]
Hi, I am trying to programatically create a router linked to external network. I can do it through CLI, but through openstack4j api calls anything other than simple create router with name returns me "not authorized". For example this works:

   `client.networking().router().create(Builders.router().name("myApiRouter").build())`

But the next gives me `ClientResponseException{message=Policy doesn't allow create_router to be performed., status=403, status-code=FORBIDDEN}` :
        `client.networking().router().create(Builders.router().name("myApiRouter2").externalGateway(publicNetId).build())`

If I try to set the gateway via update call, I get `ClientResponseException{message=Policy doesn't allow update_router to be performed., status=403, status-code=FORBIDDEN}` :
  `client.networking().router().update(Builders.router().id(routerId).externalGateway(publicNetId).build())`

Yet with the same credentials I can do it via command line tools with these commands
  neutron router-create testRouter
  neutron router-gateway-set routerid publicNetId

I saw there is a probably related bug https://github.com/gondor/openstack4j/issues/274 but there is no description, so I do not know if the issue is the same, or in which version it is fixed
I am using openstack4j-core
   Bundle-Version: 2.0.2.SNAPSHOT
   Bnd-LastModified: 1426711180352
with openstack4j-httpclient
  Bundle-Version: 2.0.2.SNAPSHOT
  Bnd-LastModified: 1426711248818

**Comment by tyonchev** [comment]
I also get `"ServerResponseException{message=Internal Server Error, status=500, status-code=INTERNAL_SERVER_ERROR}"`
when executing 
`client.networking().network().create(Builders.network().name(networkName).build())`
with same credentials in CLI this works : `neutron net-create networkName`

**Comment by tyonchev** [comment]
Oh guys, I did some experimenting with vanilla REST calls and found that the correct JSON that works is 
`{
"router" : {
"name" : routername,
"external_gateway_info" : {
"network_id" : networkid
}
    }
}`
hoewever 'client.networking().router().create(Builders.router().name("myApiRouter2").externalGateway(publicNetId).build())'
gets me the following json:
`{
"router" : {
           "name" : "myApiRouter2",
          "external_gateway_info" : {
                "network_id" : publicNetId",
                "enable_snat" : true
           },
           "admin_state_up" : false
     }
}
`
a little further testing showed that the mere existence of the `admin_state_up` alone,  results in error code 500, while if it is in combination with `enable_snat` or  `enable_snat` is alone, result in error code 403.
These parameters are optional and are set to true by default after the call is received by openstack. I guess openstack does not like seeing them in requests by non-admin users, but there is no way to omit them from the JSON through the openstack4j API.

**Comment by gondor** [comment]
Thanks for the extended debugging and documentation you've provided.  Sorry for the late response in the meantime (been a hectic week).  I can definitely fix this for you with your clear prognosis above.

**Comment by gondor** [comment]
Ok, Code checked in and a new Maven snapshot deployed.  You will have to change your dependency to be 2.0.3-SNAPSHOT in order to test.  Thanks again

**Comment by tyonchev** [comment]
Hi, Thanks for the fast reaction! Unfortunately now I am getting a NPE:
java.lang.NullPointerException	at org.openstack4j.openstack.networking.domain.NeutronRouter$RouterConcreteBuilder.externalGateway(NeutronRouter.java:200)	at org.openstack4j.openstack.networking.domain.NeutronRouter$RouterConcreteBuilder.externalGateway(NeutronRouter.java:192

I think is is because of the NeutronExternalGateway constructor, where enableSnat is primitive boolean and it can't handle the null : 
```java
	public NeutronExternalGateway(String networkId, boolean enableSnat) {
		this.networkId = networkId;
		this.enableSnat = enableSnat;
	}
```

**Comment by gondor** [comment]
I apologize, that was sloppy.  I usually test against my deployments but it was late and wanted to get this in for you and of course it back fires :).   Try again.

**Comment by tyonchev** [comment]
Sorry for the late response, I can confirm that now it works :)
Thanks!
