### ISSUE TITLE
Volumes metadata is not set due to wrong parameter name sent from openstack4j

### ISSUE THREAD

**Issue by nmarchev** [gondor/openstack4j#325]
I'm calling create volume passing metadata parameter. 
The json sent from openstack4j to the cloud provider looks like:
{ 
"volume" : { 
          "metaData" : { 
                "tagKey" : "tagValue" 
           }, 
           "size" : 10, 
           "os-vol-mig-status-attr:migstat" : "none" 
     } 
} 
"metaData" is with upper "D" and is not recognized, so the tags are skipped.

According to the openstack documentation this parameter is with lower 'd'
http://developer.openstack.org/api-ref-blockstorage-v2.html

**Comment by gondor** [comment]
Thank you.  Code committed and new 2.0.3-SNAPSHOT deployed.  Let me know if this fixes your issue.

**Comment by nmarchev** [comment]
Checked and working
10x
