### ISSUE TITLE
BlockStorageService availability_zone 

### ISSUE THREAD

**Issue by dr2014** [gondor/openstack4j#326]
Is it possible to get all availability zones for Volume Creation and also be able to create volume in a specific zone?

**Comment by dr2014** [comment]
It seems VolumeBuilder and ConcreteVolumeBuilder need to be updated so that zone information could be assigned to the volume:

https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/model/storage/block/builder/VolumeBuilder.java

https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolume.java#L225

**Comment by dr2014** [comment]
The following additions will fix the issue:

(1) VolumeBuilder.java:

VolumeBuilder zone(String zone);

(2) CinderVolume.ConcreteVolumeBuilder

@Override
public VolumeBuilder zone(String zone) {
    m.zone = zone;
    return this;
}

**Comment by gondor** [comment]
Thanks for the info.  Applied the fix and deployed a new snapshot.

**Comment by dr2014** [comment]
Thanks - the fix is working fine.
