### ISSUE TITLE
[Question] Release date for 2.0.3 ?

### ISSUE THREAD

**Issue by tyonchev** [gondor/openstack4j#328]
I just want to ask if you have a determined release date for 2.0.3 ? I need to know, because I can't use snapshot versions in our project productively. Thanks in advance :)

**Comment by gondor** [comment]
I'm going to be doing a release on Friday which is mainly the recent bug fixes, etc.

**Comment by gondor** [comment]
I just released the 2.0.3 release to Central.  It will take ~24 hours for it to be in the Maven Central catalog.  Master is now 2.0.4-SNAPSHOT.

**Comment by tyonchev** [comment]
Thanks!
