### ISSUE TITLE
how can I "server" mount "volumn"？

### ISSUE THREAD

**Issue by houyu533** [gondor/openstack4j#330]
I try excute "os.compute().servers().attachVolume(serverId,volumnId,device)", but server can not mount volumn and this function return NovaVolumeAttachment object is ok.
I need help.

**Comment by gondor** [comment]
What are you specifying for device?  
What version of OpenStack4j are you using?

Code example would be helpful.

**Comment by houyu533** [comment]
thank you very mutch. it is openstack server error.
