### ISSUE TITLE
Serializable and JsonMapping problems

### ISSUE THREAD

**Issue by cyhbest** [gondor/openstack4j#331]
Q1. 'SecGroupExtension' paramter type in 'ComputeSecurityGroupService' interface is not serializable. Following is stack exception message: 
 java.lang.RuntimeException: Serialized class org.openstack4j.openstack.compute.domain.NovaSecGroupExtension$SecurityGroupRule$RuleIpRange must implement java.io.Serializable
 Java field: private org.openstack4j.openstack.compute.domain.NovaSecGroupExtension$SecurityGroupRule$RuleIpRange org.openstack4j.openstack.compute.domain.NovaSecGroupExtension$SecurityGroupRule.ipRange
 Java field: private java.util.List org.openstack4j.openstack.compute.domain.NovaSecGroupExtension.rules

Q2. JsonMappingException when invoking NetQuotaService.get() method 
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Root name 'quotas' does not match expected ('quota') for type [simple type, class org.openstack4j.openstack.networking.domain.NeutronNetQuota]
 at [Source: UNKNOWN; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
 
ps. using openstack4j version 2.0.1

**Comment by cyhbest** [comment]
ps. using openstack4j version 2.0.1

**Comment by cyhbest** [comment]
The same serializable problem happens when invoking 'Access' interface v2
java.lang.RuntimeException: Serialized class org.openstack4j.openstack.identity.domain.KeystoneAccess$AccessService must implement java.io.Serializable
 Java field: private java.util.List org.openstack4j.openstack.identity.domain.KeystoneAccess.serviceCatalog

**Comment by gondor** [comment]
I'm curious on how your using this in your application?  Some of these classes have been the same since the initial version 1 release with no problems from the community.  Seems like an environment or usage issue.

**Comment by cyhbest** [comment]
When using this in dubbo service which is distributed remote method invocation implemented by alibaba, I have some trouble with Serializable RuntimeException and be confused too.

**Comment by gondor** [comment]
Ok, yes I don't think this will work with RPC without a lot of playing around.  You could sync OS4j source and modify the classes it's complaining about to see if that gets you anywhere.  Even fixing those you may run into other issues.
