### ISSUE TITLE
Refactor HttpClient Connector to use singleton of the Apache HttpClient

### ISSUE THREAD

**Issue by gondor** [gondor/openstack4j#332]
In order to preserve pooling within the Apache HttpClient we need to use the client as a singleton.  Recently configuration options were added for advanced options like MaxConnections, TotalConnections, etc.  In order to honor these preferences we need to retain an existing HttpClient and let it handle the pooling.

**Comment by symcssn** [comment]
:+1:

**Comment by gondor** [comment]
@symcssn Added support and just deployed a new `2.0.4-SNAPSHOT`
