### ISSUE TITLE
Default value set to 0 for NetSecurityGroupRules : port range.

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#333]
@gondor 
Looks like if I don't specify `port_range_min` or `port_range_max` the value is still set to `0` which is unexpected to me. I am trying to add this rule, `ALLOW IPv4 to 0.0.0.0/0`. Can `port_range_min` and `port_range_max` be sent as `null` if they aren't specified?
```
POST http://xx.xx.xx.xx:9696/v2.0/security-group-rules
{
  "security_group_rule" : {
    "security_group_id" : "4f85c4cf-36dc-4522-ae8b-de84b301e27a",
    "direction" : "ingress",
    "port_range_max" : 0,
    "port_range_min" : 0,
    "remote_ip_prefix" : "0.0.0.0/0"
  }
}

{"NeutronError": {"message": "Must also specifiy protocol if port range is given.", "type": "SecurityGroupProtocolRequiredWithPorts", "detail": ""}}

```

**Comment by gondor** [comment]
Thanks for pointing this out.  They should of been "Integer" vs "int".  Modified the interface.  If you don't specify the ranges they won't be included in the payload.  This should fix your issue.  

Deployed a new 2.0.4-SNAPSHOT

**Comment by vishvesh** [comment]
Awesome :+1:  Fixed!
