### ISSUE TITLE
Enhancement Request: ability to fetch ALL metadata for objects/containers

### ISSUE THREAD

**Issue by symcssn** [gondor/openstack4j#337]
I realized that the ```getMetaData()``` methods inside ```ObjectStorageObjectService``` and ```ObjectStorageContainerService``` filters out the metadata created by the server from the ```HEAD``` requests and only returns the user defined metadata. Would it be possible to return all the metadata returned from ```HttpResponse.headers()``` without any filtering inside the above two classes' impls?

Thanks!

**Comment by gondor** [comment]
@symcssn  I'm curious on why you would need every header?  I mean headers like Accept: etc would have no value.   Is there a particular set of headers your trying to access?

**Comment by symcssn** [comment]
You're correct. I don't need headers like 'Accept'. However, at the moment, headers like size, # of objects, ACLs, timestamps, etc are very useful. Having any of these headers returned (via HEAD request) also is a very cheap way to see if a container or object exists. I don't think we need get methods for every single metadata. Returning a map with the keys and values should be good enough.

**Comment by gondor** [comment]
I could allow any -X-** attribute since it appears everything your looking for is under that classification (if that works for you) ?

**Comment by gondor** [comment]
An example.. I have a container with with no metadata.   (i.e. normally I just get back an empty map.).  By allowing the X-* headers in I'm now getting this on my System.out

```json
{X-Storage-Policy=Policy-0, X-Container-Object-Count=1, X-Container-Bytes-Used=60241, X-Trans-Id=tx8fc19bb7bc8644eb8d96e-00553eb8ae, X-Timestamp=1428549384.54381}
```

**Comment by symcssn** [comment]
Yes. Perfect!

**Comment by gondor** [comment]
Ok, I've added the change and re-deployed a new `2.0.4-SNAPSHOT`.   You'll now get the X- attributes included in the Metadata.

**Comment by symcssn** [comment]
Thank you. i'll verify it very shortly

**Comment by symcssn** [comment]
It seems to be working. It's returning metadata with 'X-* ' prefix.
