### ISSUE TITLE
Support for Network Extension: Firewall As a Service (FwaaS)

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#340]
Hi @gondor 
I know that there was a previous issue opened #137. Has there been any implementation for `FwaaS`?
You can find the OpenStack API reference for FwaaS : http://specs.openstack.org/openstack/neutron-specs/specs/api/firewall_as_a_service__fwaas_.html

Are there any plans for implementing? Should I implement/contribute?

`Update`: I am half-way towards completing the API.

`Submitted Pull-Request` #342

**Comment by vishvesh** [comment]
:+1:

**Comment by gondor** [comment]
Awesome, Thanks! Just deployed a new `2.0.4-SNAPSHOT`.

**Comment by vishvesh** [comment]
Awesome :+1: Thanks!
