### ISSUE TITLE
Create OSClient from auth_token

### ISSUE THREAD

**Issue by erikringsmuth** [gondor/openstack4j#358]
Is there a way to get an `OSClient` given an `auth_token`? For example, I authenticate like this to get an `auth_token` which the user will use throughout their session.

```java
String authToken = OSFactory.builder()
                            .endpoint(identityUrl)
                            .credentials(username, password)
                            .authenticate()
                            .getToken()
                            .getId();
```

Then later, given the `auth_token`, I need to create an `OSClient`. I see this method to create a client from an `Access` object.

```java
OSFactory.clientFromAccess(access);
```

Is there a way to build an `Access` object from an `auth_token`, or build an `OSClient` from an `auth_token`?

**Comment by gondor** [comment]
We support this with Identity V3.  I wasn't aware of V2 of Identity (Keystone) supporting this.  It's hard to keep up with all the APIs.  If you can point to a V2 endpoint in OpenStack that allows authenticating with a Token then I don't anticipate this to be much work to add this to our V2 builder (^^^ the one your using above)

**Comment by erikringsmuth** [comment]
Only supporting v3 is understandable. I'm stuck with v2 for now but hopefully that'll change soon.

This is the endpoint I've bene using.

`POST /v2.0/tokens` http://developer.openstack.org/api-ref-identity-v2.html#authenticate-v2.0

This is an example sequence I use to authenticate users.
```
curl -XPOST http://identity-host:port/v2.0/tokens -H 'Content-Type: application/json' \
-d '{"auth":{"passwordCredentials":{"username":"...","password":"..."}}}'

{
  "access": {
    "token": {
      "issued_at": "2015-05-05T20:32:48.903507",
      "expires": "2015-05-05T23:32:48Z",
      "id": "e2fa089baf544764a716681146527197"
    },
    "serviceCatalog": [],
    "user": {
      "username": "username",
      "roles_links": [],
      "id": "0a39a70ab148478b9d6d2b0d967e3663",
      "roles": [],
      "name": "username"
    },
    "metadata": {
      "is_admin": 0,
      "roles": []
    }
  }
}
```

Which I use to get the tenants.
```
curl http://identity-host:port/v2.0/tenants -H 'X-Auth-Token: e2fa089baf544764a716681146527197'

{
  "tenants_links": [],
  "tenants": [
    {
      "description": "",
      "enabled": true,
      "id": "5928b8f7f17949a8a072c84177e5586d",
      "name": "Group 1"
    },
    {
      "description": "",
      "enabled": true,
      "id": "7ab389ba761d4d2aa65b2821ad3ff637",
      "name": "Group 2"
    }
  ]
}
```

Then once the user picks the tenant I can get the complete authentication object.
```
curl -XPOST http://identity-host:port/v2.0/tokens -H 'Content-Type: application/json' \
-d '{"auth":{"tenantName":"Group 1","token":{"id":"e2fa089baf544764a716681146527197"}}}'

{
  "access": {
    "token": {
      "issued_at": "2015-05-05T20:53:33.476028",
      "expires": "2015-05-05T23:32:48Z",
      "id": "b08e3c4e40f9440e93bbdc60a19938b4",
      "tenant": {
        "id": "5928b8f7f17949a8a072c84177e5586d",
        "enabled": true,
        "name": "Group 1",
        "description": ""
      }
    },
    "serviceCatalog": [
      {
        "endpoints": [
          {
            "adminURL": "http://host:port/v2/5928b8f7f17949a8a072c84177e5586d",
            "region": "emea1",
            "internalURL": "http://host:port/v2/5928b8f7f17949a8a072c84177e5586d",
            "id": "36c61f9ccbf140469d8e5bae89c853e4",
            "publicURL": "http://host:port/v2/5928b8f7f17949a8a072c84177e5586d"
          },
...
```

Let me know if you get around to adding v2 support, otherwise I'll be pushing for an upgrade to v3.

Thanks!

**Comment by gondor** [comment]
So basically if I asked for Tenant Name & Token that would satisfy the V2 requirement?  

Example:
```java
OSClient os = OSFactory.builder()
                           .token("token")
                           .tenantName("tenantName")
                           .endpoint(ep)
                           .authenticate();
// If "tenantName" wasn't provided during the "token" route I would fail with a pre-condition failure.
```

Let me know if this is what you were thinking?  It would be hard to handle multi steps like your doing above with our current workflow.

**Comment by erikringsmuth** [comment]
Yep, that'd work well enough.

**Comment by gondor** [comment]
Ok, code checked in and a new maven `2.0.4-SNAPSHOT` deployed.  Exactly what we discussed.  Only difference is you can use `.token("some token")` instead of `.credentials()`.

```java
OSClient os = OSFactory.builder()
                           .token("token")
                           .tenantName("tenantName")
                           .endpoint(ep)
                           .authenticate();
```

Let me know after you try it!

**Comment by erikringsmuth** [comment]
It works! Thanks @gondor!
