### ISSUE TITLE
add user to tenant error

### ISSUE THREAD

**Issue by houyu533** [gondor/openstack4j#361]
I used openstack4j version  2.0.3,   
"tenant.addUser(user.getId(), role.getId())"
console show:
org.glassfish.jersey.client.JerseyInvocation validateHttpMethodAndEntity
warn:Entity must not be null for http method PUT.

thank you!

**Comment by gondor** [comment]
I tested this and couldn't reproduce.  I tested a scenario where the user already had the role in the tenant and one where they didn't.  First test I got the Conflict error which was expected and the second test it added successfully which was also expected.  

I need more logs and full stack trace to see what your seeing.

**Comment by houyu533** [comment]
thank you for your answer. it is only a warn,practical operation is successful。
