### ISSUE TITLE
Compute: Add/Remove SecGroup 500 exception not caught.

### ISSUE THREAD

**Issue by vishvesh** [gondor/openstack4j#365]
Hi @gondor 

This call to Remove Security Group from Instance triggers a 500 exception, but isn't caught by OS4J.
```
1 > POST http://xx.xx.xx.xx:8774/v2/7069831a4bdc485ea0696988b7af81ad/servers/4cda9389-fedf-

{
  "removeSecurityGroup" : {
    "name" : "default"
  }
}

40bb-858b-9694ba3c84b1/action
May 10, 2015 5:15:15 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Client response received on thread http-bio-80-exec-3
2 < 500
2 < Connection: keep-alive
2 < Content-Length: 128
2 < Content-Type: application/json; charset=UTF-8
2 < Date: Mon, 11 May 2015 00:15:44 GMT
2 < X-Compute-Request-Id: req-5d89d50a-8170-4c82-9fe3-6e04b73dc60b
{"computeFault": {"message": "The server has either erred or is incapable of performing the requested operation.", "code": 500}}
```

`toString()` on `ActionResponse` returns `ActionResponse{success=true, code=200}`

When I saw `invokeAction() -> ToActionResponseFunction`'s `apply()` function, the `HttpResponse`'s status code `500` isn't handled.. Should it propagate on 500, or the function needs to handle it explicitly?

**Comment by vishvesh** [comment]
Added implementation to catch this exception from OpenStack. Please review pull request #367

**Comment by gondor** [comment]
Thank you. Pull request approved and a new `2.0.4-SNAPSHOT` deployed.
