### ISSUE TITLE
Identity v3 scoped auth token

### ISSUE THREAD

**Issue by erikringsmuth** [gondor/openstack4j#366]
I found a limitation in `OSClientBuilder` and `KeystoneAuth` when authenticating with auth tokens against the v3 identity service.
- `OSClientBuilder` https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/client/OSClientBuilder.java#L140
- `KeystoneAuth` https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/identity/domain/v3/KeystoneAuth.java#L28

`KeystoneAuth` needs an additional constructor that takes an auth token plus a scope.

This is an example of authenticating with an auth token.

1. Authenticate the user against the default domain without a project scope to get an auth token.

```
curl -XPOST http://identity-host:port/v3/auth/tokens -i -H 'Content-Type: application/json' -d '{
  "auth": {
    "identity": {
      "methods": [
        "password"
      ],
      "password": {
        "user": {
          "name": "...",
          "password": "...",
          "domain": {
            "name": "default"
          }
        }
      }
    }
  }
}'
```

The auth token is in the X-Subject-Token response header.

```
X-Subject-Token: a372151b1f6a488f87b8631fada9b1a7
```

The user is authenticated at this point and you can store the auth token in your application's user session. You can't do much with this token at this point since it doesn't include a catalog. The API docs state you need to re-authenticate the token with a scope to get a catalog. http://developer.openstack.org/api-ref-identity-v3.html#authenticate

2. Exchange the auth token plus a project scope to get another auth token with a catalog.

```
curl -XPOST http://identity-host:port/v3/auth/tokens -i -H 'Content-Type: application/json' -d '{
  "auth": {
    "identity": {
      "methods": [
        "token"
      ],
      "token": {
        "id": "a372151b1f6a488f87b8631fada9b1a7"
      }
    },
    "scope": {
      "project": {
        "name": "...",
        "domain": {
          "name": "default"
        }
      }
    }
  }
}'
```

The response will contain another X-Subject-Token header with a new auth token scoped to your project.

```
X-Subject-Token: c1d6977e58864e49ac5f7edd609ae992
```

You can use this auth token to make requests to other services.

```
curl http://compute-service:port/v2/5928b8f7f17949a8a072c84177e5586d/flavors -H 'X-Auth-Token: c1d6977e58864e49ac5f7edd609ae992'
```

If we add the scope to the `KeystoneAuth` here it should all work.
https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/client/OSClientBuilder.java#L140

**Comment by gondor** [comment]
Do you currently have a fork for OpenStack4j?  Wondering if you just want to make the change, test it and then pull request the fix?  If not I'll look into this and apply it, but with all the great work you've done finding the root cause it makes more sense for you to contribute the change.
