### ISSUE TITLE
unbind router in openstack4j

### ISSUE THREAD

**Issue by lsylamar** [gondor/openstack4j#370]
Hi master,
   I need help for some question about router unbind gateway. I use "os.networking().router().update(Builders.router().id(routerId).externalGateway(networkId).build())"
to binding gateway,but i don't know how to remove gateway.I can't find in Openstack4J.Hope to answer.Thinks.

**Comment by gondor** [comment]
I believe Issue #277 may be what your looking for?  Ability to clear the gateway.

Example:
```java
osClient.networking().router().update((osClient.networking().router().get(routerId)).toBuilder().clearExternalGateway()).build());
```

**Comment by lsylamar** [comment]
thinks for your answer.
