### ISSUE TITLE
Connection leak when using HttpClient connector 

### ISSUE THREAD

**Issue by bsemp** [gondor/openstack4j#373]
In addition to issue #360, the connection leak problem seems to be also present when calling function `compute().floatingIps().deallocateIP`

```java
private static List<String> fips = new ArrayList<>();
    
private void testCreateFloatingIPs() throws Exception {
    for (int i = 1; i <= 10; i++) {
        FloatingIP fip = client.compute().floatingIps().allocateIP("floating");
        System.out.println("Allocating floating IP " + fip.getId() + " : " + fip.getFloatingIpAddress());
        fips.add(fip.getId());
    }
}
    
private void testDeleteFloatingIPs() throws Exception {
    for (String id : fips) {
        boolean success = client.compute().floatingIps().deallocateIP(id).isSuccess();
        System.out.println("Deallocating floating IP " + id + " : " + success);
    }
}
```

    Allocating floating IP 6802e2c0-11eb-4921-adbe-a03198c04965 : 10.238.200.242
    Allocating floating IP 59669d6d-3632-4e0c-ac10-7174ec9e8f92 : 10.238.200.254
    Allocating floating IP f1c70bc9-b2ec-4dc5-87f7-24ffcf8c455b : 10.238.200.138
    Allocating floating IP 4115711e-8be9-454a-b189-a7befbc388c1 : 10.238.200.206
    Allocating floating IP b915076a-ab4c-4d48-9617-b46038fa700e : 10.238.200.243
    Allocating floating IP dd3459bc-3f81-412d-822d-0880208c5f51 : 10.238.200.139
    Allocating floating IP 293a278b-9f1d-4796-a172-a41bfda70fd8 : 10.238.200.207
    Allocating floating IP 6bc3eab1-89cf-461a-847c-0c7060c943c1 : 10.238.200.244
    Allocating floating IP 74a95b62-206c-4894-bc7b-b52b17661b6d : 10.238.200.140
    Allocating floating IP 2a2facbe-4aac-43da-aa16-027d334d41e8 : 10.238.200.208
    Deallocating floating IP 6802e2c0-11eb-4921-adbe-a03198c04965 : true
    Deallocating floating IP 59669d6d-3632-4e0c-ac10-7174ec9e8f92 : true
    [Freeze...]

My understanding is that a certain number of actions do not process response entity and do not properly close the response either resulting in connection leaks. This seems to be the case for at least `ResponseToActionResponse.apply` and `ToActionResponseFunction.apply`.

This bug seems critical for me. Can you please take a look at it ? You should be able to correct it in a cleaner way than me.

**Comment by gondor** [comment]
Thank you Bruno.  I will look into this.

**Comment by gondor** [comment]
Bruno, I looked into this and I believe we can fix it for all scenarios by adding the following in the `ToActionResponseFunction` class.

Try adding the following in your local version (I can do this if it's easier but I believe this will solve what your seeing so it can be tested locally by you).

```java
 public ActionResponse apply(HttpResponse response, String action) {
        try {
            if (response.getStatus() == 409 || response.getStatus() == 500)
            {
                // existing logic says the same
            }
            return ActionResponse.actionSuccess();
        } finally {
            try {
                response.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
}
```

**Comment by bsemp** [comment]
Hi,
I will test it monday, I am out of office until then.
Thank you.

**Comment by bsemp** [comment]
Ok, the fix works great.
I will produce a pull request with this fix and some tests for FloatingIPs that demonstrate that the issue is fixed and will prevent future regression.

However, tests are showing another bug in HttpURL connector only related to deserialization of response 404. I will fill another bug for this.

**Comment by gondor** [comment]
I just fixed the HttpURL connector (your other issue). closing this issue
