### ISSUE TITLE
how can I query network traffic for "macAddr and serverId" ？

### ISSUE THREAD

**Issue by houyu533** [gondor/openstack4j#388]
hi，all
  how can I query network traffic for "macAddr and serverId" ？

I see api have a function, resourceId is "instance-00000271-bf7f360f-77b0-46c5-92e9-d48515b995cd-tapf518a127-8d" ,  but  I can not get "network-card-name", so I can not combination resourceId ：

                SampleCriteria sc = new SampleCriteria();
		sc.resource(resourceId);
      	        List<? extends Sample> samples =           os.telemetry().meters().samples("network.outgoing.packets", sc);

**Comment by gondor** [comment]
I don't see anyway to do this even with OpenStack's python client.  If you know of a way outside of this API then please post the steps and re-open this issue and I can see if we can make it work in OpenStack4j
