### ISSUE TITLE
Support for newest Service Versions

### ISSUE THREAD

**Issue by gondor** [gondor/openstack4j#390]
Currently we always default to Compute V2 but as OpenStack progresses we should automatically select the newest endpoint version (for example V2.1 if it's deployed).

This issue will add support to always use the latest version.  Another issue will be created to allow for more granular control but that will be at a later cycle.

**Comment by bsemp** [comment]
The patch for endpoint latest version selection works as expected but __should not be used for the moment__:

Endpoint latest version selection works:

```java
Server s = client.compute().servers().get("108b91cd-1adc-4799-b467-a7ec6fcd8ee7");
```
    2015/05/29 11:37:26:017 CEST [DEBUG] wire - http-outgoing-1 >> "GET /v2.1/b0b5ed7ae06049688349fe43737796d4/servers/108b91cd-1adc-4799-b467-a7ec6fcd8ee7 HTTP/1.1[\r][\n]"

```java
Volume v = client.blockStorage().volumes().get("8a9287b7-4f4d-4213-8d75-63470f19f27c");
```
    2015/05/29 11:42:36:959 CEST [DEBUG] headers - http-outgoing-1 >> GET /v2/b0b5ed7ae06049688349fe43737796d4/volumes/8a9287b7-4f4d-4213-8d75-63470f19f27c HTTP/1.1


__However, several bugs occurs related to the use of these new endpoints:__

 - Volume information are not complete :
```java
Volume v = client.blockStorage().volumes().get("8a9287b7-4f4d-4213-8d75-63470f19f27c");
System.out.println("Volume name=" + v.getName());
```
    2015/05/29 12:04:47:699 CEST [DEBUG] wire - http-outgoing-1 << "{"volume": {"status": "in-use", [...], "name": "test_vol", [...], "id": "8a9287b7-4f4d-4213-8d75-63470f19f27c", "size": 100}}"
    Volume name=null

 - I haven't tested other fields than volume.name nor other objects images/servers/snapshots so other similar bugs can be present.

 - Compute api 2.1 return HTTP error 500 with my deployment (ok, maybe it's a problem with my deployment, v2 works ok, v2.1 fails) but I ran into __connection leak problem again__...
```java
for (int i=0; i<=5; i++) {
    try {
        Server s = client.compute().servers().get("108b91cd-1adc-4799-b467-a7ec6fcd8ee7");
        System.out.println("Server=" + s);
    } catch (Exception e) {
        System.out.println("Exception occurs: " + e.getMessage());
    }
}
```

    2015/05/29 11:54:18:775 CEST [DEBUG] wire - http-outgoing-1 >> "GET /v2.1/b0b5ed7ae06049688349fe43737796d4/servers/108b91cd-1adc-4799-b467-a7ec6fcd8ee7 HTTP/1.1[\r][\n]"
    [...]
    2015/05/29 11:54:18:892 CEST [DEBUG] wire - http-outgoing-1 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
    2015/05/29 11:54:18:892 CEST [DEBUG] wire - http-outgoing-1 << "{"computeFault": {"message": "The server has either erred or is incapable of performing the requested operation.", "code": 500}}"
    [...]
    2015/05/29 11:54:18:901 CEST [DEBUG] wire - http-outgoing-2 >> "GET /v2.1/b0b5ed7ae06049688349fe43737796d4/servers/108b91cd-1adc-4799-b467-a7ec6fcd8ee7 HTTP/1.1[\r][\n]"
    [...]
    2015/05/29 11:54:18:919 CEST [DEBUG] wire - http-outgoing-2 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
    2015/05/29 11:54:18:920 CEST [DEBUG] wire - http-outgoing-2 << "{"computeFault": {"message": "The server has either erred or is incapable of performing the requested operation.", "code": 500}}"
    [...]
    2015/05/29 11:54:18:921 CEST [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {}->http://example.com:8774][total kept alive: 1; route allocated: 2 of 2; total allocated: 3 of 20]

    [FREEZE..]

**Comment by bsemp** [comment]
Please revert this patch until at least fine grained version control patch is available

**Comment by bsemp** [comment]
The problem with volume.getName() comes from a change in openstack response:
 - in v1:
     "display_name": "vol-test-2",

 - in v2
     "name": "vol-test",

**Comment by bsemp** [comment]
Also, please add a unit test for that endpoint selection feature.

**Comment by gondor** [comment]
Ok, so full support for Auth V2 is now available.  By default it results to the old algorithm of using the older service versions.

Here's some example:

**Using newest versions for all Service types**
```java
OSClient os = OSFactory.builder(
             .endpoint(host)
             .credentials("admin", "admin")
             .tenantName("admin")
             .withConfig(Config.newConfig().withResolver(LatestServiceVersionResolver.INSTANCE))
             // etc
```
**Using Stable (older mechanism)**
This is the default so no need to actual use this but it's an example to show it's available

```java
OSClient os = OSFactory.builder()
        .endpoint(host)
        .credentials("admin", "admin")
        .tenantName("admin")
        .withConfig(Config.newConfig().withResolver(StableServiceVersionResolver.INSTANCE))
        // etc ...
```

**Using a Custom Resolver**
```java
// This can be an inline anonymous implementation or you could create a class implementing the interface
final ServiceVersionResolver resolver = new ServiceVersionResolver() {

    /**
     * In this example we only care about using Compute 2.1, everything else we want Stable (old OpenStack4j)
     * behavior of using earlier version services
     */
    @Override
    public Service resolve(ServiceType type, SortedSet<? extends Service> services) {
        if (type == ServiceType.COMPUTE) {
            for (Service s : services) {
                if (s.getVersion() == 21) {
                    return s;
                }
            }
        }
        // This is sorted by version - .first() would be the earliest version
        return services.first();
    }
};

OSClient os = OSFactory.builder()
        .endpoint(host)
        .credentials("admin", "admin")
        .tenantName("admin")
        .withConfig(Config.newConfig().withResolver(resolver))
        // etc
```

**Comment by bsemp** [comment]
works as expected.
Thanks

**Comment by bsemp** [comment]
I noticed that service version found by resolver mismatch with the one expected from endpoint URL:

```java
    final ServiceVersionResolver resolver = new ServiceVersionResolver() {
            public Service resolve(ServiceType type, SortedSet<? extends Service> services) {
                if (type == ServiceType.COMPUTE) {
                    for (Service s : services) {
                        System.out.println("Service " + s.getName() + ", Type " + s.getType() + ", Version " + s.getVersion());
                    }
                }
                return services.first();
            }
        };
```

Output:

    Service nova, Type compute, Version 1
    Service novav21, Type computev21, Version 21

Actual catalog show default service is V2:

    Service: compute                                                               
    +-------------+----------------------------------------------------------------+
    |   Property  |                                             Value              |
    +-------------+----------------------------------------------------------------+
    |   adminURL  | http://exemple.com:8774/v2/b0b5ed7ae06049688349fe43737796d4    |
    |      id     | 807adfb389bd4480b419ce7bc1e49959                               |
    | internalURL | http://exemple.com:8774/v2/b0b5ed7ae06049688349fe43737796d4    |
    |  publicURL  | http://exemple.com:8774/v2/b0b5ed7ae06049688349fe43737796d4    |
    |    region   | RegionOne                                                      |
    +-------------+----------------------------------------------------------------+
                                                                                   
    Service: computev21                                                            
    +-------------+----------------------------------------------------------------+
    |   Property  |                                              Value             |
    +-------------+----------------------------------------------------------------+
    |   adminURL  | http://exemple.com:8774/v2.1/b0b5ed7ae06049688349fe43737796d4  |
    |      id     | b151e1e6d198491da09098492920a898                               |
    | internalURL | http://exemple.com:8774/v2.1/b0b5ed7ae06049688349fe43737796d4  |
    |  publicURL  | http://exemple.com:8774/v2.1/b0b5ed7ae06049688349fe43737796d4  |
    |    region   | RegionOne                                                      |
    +-------------+----------------------------------------------------------------+

**Comment by gondor** [comment]
This is the correct behavior.  I'm not parsing the URLs but the actual service type.  This is what the OpenStack implementations do as well and I followed the same pattern.  The service name is i.e.. ("compute" or "computev21")  are strong typed within OpenStack at least around their own APIs.  

Since "compute" doesn't have a "v" prefix I default to version 1 and do that for all the "base" services.  Any service that has the "v" will be parsed to the specific version since this will allow for future growth. 

Endpoints are unreliable since the user can change them, etc so the version in the endpoint might not reflect what the actual implementation is.

Does this make sense?

**Comment by bsemp** [comment]
This perfectly make sense.

However, current implementation of resolver for stable services will always
default to "no v" even if a v2 exist:
compute, computev2, computev21

Is it the expected behaviour ? Is the compute without v always considered
as stable and set compute, computev1, computev21 if we ever want to expose
previous version ?
This makes sense to me but do you know the official answer?

--
Bruno Semperlotti

**Comment by gondor** [comment]
You actually bring up some good points on the stable naming, etc.  I'll do some research this weekend and see if I can find anything.  It would be nice if that is the official stance from OpenStack's perspective.  If not, we may have to add another value on the ServiceType enum which sets what we feel is the most stable for the current OpenStack4j release.

**Comment by gondor** [comment]
Will revisit the next time they rev a version

**Comment by sudself** [comment]
` @Override
    public Service resolveV3(ServiceType type, SortedSet<? extends Service> services) {
        Service service = services.first();
        int service_count = services.size();
        /**stable version get last second**/
        if(service_count>1){
            int index = 1;
            for(Service s:services){
                if(index == (service_count-1)){
                    service = s;
                    break;
                }
                index++;
            }
        }
        
        return service;
    }

    @Override
    public Access.Service resolveV2(ServiceType type, SortedSet<? extends Access.Service> services) {
        Access.Service service = services.first();
        
        int count = services.size();
        /**stable version get last second**/
        if(count>1){
            int index = 1;
            for(Access.Service s:services){
                if(index == (count-1)){
                    service = s;
                    break;
                }
                index++;
            }
        }
        
        return service;
    }`

**Comment by sudself** [comment]
`` @Override
    public Service resolveV3(ServiceType type, SortedSet<? extends Service> services) {
        Service service = services.first();
        int service_count = services.size();
        /**stable version get last second**/
        if(service_count>1){
            int index = 1;
            for(Service s:services){
                if(index == (service_count-1)){
                    service = s;
                    break;
                }
                index++;
            }
        }
        
        return service;
    }

    @Override
    public Access.Service resolveV2(ServiceType type, SortedSet<? extends Access.Service> services) {
        Access.Service service = services.first();
        
        int count = services.size();
        /**stable version get last second**/
        if(count>1){
            int index = 1;
            for(Access.Service s:services){
                if(index == (count-1)){
                    service = s;
                    break;
                }
                index++;
            }
        }
        
        return service;
    }
