### ISSUE TITLE
FlavorServiceImpl.getSpec /flavors/%s/os-extra_specs/%s/ uri error

### ISSUE THREAD

**Issue by tangxiaodon89** [gondor/openstack4j#391]
the uri in method FlavorServiceImpl.getSpec should be
'/flavors/%s/os-extra_specs/%s' 
not '/flavors/%s/os-extra_specs/%s/'

**Comment by gondor** [comment]
Thanks, changes made and a new 2.0.4-SNAPSHOT has been deployed.
