### ISSUE TITLE
Allow HttpClient interceptor to allow for custom configuration prior to client creation

### ISSUE THREAD

**Issue by gondor** [gondor/openstack4j#392]
Due to routing, pooling, timeouts, proxy and many other possible customization options with HttpClient it makes sense to allow for interception so enterprise or specific deployments can tweak the client configuration and settings to match their environments.

**Comment by gondor** [comment]
Support has been added for the HttpClientConnector.  

See example on how to register an interceptor:
```java
// Create a class or static class implementing the HttpClientConfigInterceptor
public static class MyInterceptor implements HttpClientConfigInterceptor {

    public void onClientCreate(HttpClientBuilder client, Builder requestConfig, Config config) {
        // Custom configuration here prior to client.build() goes here
    }    
}
// Register the interceptor - NOTE, this only needs to be done one time in the JVM runtime
HttpClientFactory.registerInterceptor(new MyInterceptor());

// Use OS4J like usual, your interceptor will be called whenever a new client needs to be created
OSClient os = OSFactory.builder()
                .endpoint(host)
                .credentials("user", "pass")
                .tenantName("tenant")
                .authenticate(); // etc
```

**Comment by gondor** [comment]
Maven 2.0.4-SNAPSHOT deployed

**Comment by symcssn** [comment]
I have played with the interceptor. It looks good. I've run into some issues w/ the program hanging bcz of potential connection leaks when a request is trying to lease a connection. https://github.com/gondor/openstack4j/issues/400

I've found a work around where the program hangs by configuring the PoolingConnectionManager to have a timeout during the leasing process. However, what i've noticed in my testing is that once I run into this issue, the connection manager is useless. It can never lease a connection (or at least that what i've concluded from my testing). Please look at the above issue with my comments and updates.

Thanks,

symcssn
