### ISSUE TITLE
The FlavorServiceImpl.removeTenantAccess method error

### ISSUE THREAD

**Issue by tangxiaodon89** [gondor/openstack4j#393]
In the method FlavorServiceImpl.removeTenantAccess use 'delete method' to execute.
But the openstack api does not support 'delete method' for this url.
In the compute api it show the method is delete.
![image](https://cloud.githubusercontent.com/assets/11000963/7879841/a1b195ae-0626-11e5-83f7-958f3f03db77.png)
But this use the request body to send the action and tenantId.
![image](https://cloud.githubusercontent.com/assets/11000963/7879876/f33f3f3e-0626-11e5-8ad1-d3367589c763.png)

I have tested that use the post method is ok

@Override
	public void removeTenantAccess(String flavorId, String tenantId) {
		checkNotNull(flavorId);
		checkNotNull(tenantId);
		
		RemoveTenantAccess removeTenantAccess = new RemoveTenantAccess();
		removeTenantAccess.setTenantId(tenantId);
		
		post(FlavorAccesses.class, uri("/flavors/%s/action", flavorId))
				.entity(removeTenantAccess)
				.execute();
	}

**Comment by gondor** [comment]
Thank you for filing this.  Your correct and this is a bug.

**Comment by gondor** [comment]
Ok, changed and a new 2.0.4-SNAPSHOT has been deployed
