### ISSUE TITLE
FloatingIPServiceImpl.create  don't need  floatingIp.getPortId()

### ISSUE THREAD

**Issue by zizhongwei** [gondor/openstack4j#397]
FloatingIPServiceImpl.create(floatingIp)  don't need  floatingIp.getPortId() ,OpenStack API can create   FloatingIP without PortId , so .create(floatingIp)  don't need   checkNotNull(floatingIp.getPortId());

**Comment by gondor** [comment]
What version of OpenStack are you testing against?  Have you tested against the CLI clients?  The reason why I ask, is I just looked up the OpenStack API docs and they list it as a non-optional attribute.

**Comment by zizhongwei** [comment]
Yes the OpenStack API docs  list it as a non-optional attribute ,but i has tested with Networking API v2.0 extensions , find that the PortId is Optional :
![image](https://cloud.githubusercontent.com/assets/12456254/7906742/6746c7ac-0862-11e5-8ef1-df2edd3cfe58.png)

**Comment by gondor** [comment]
Thanks, I also looked at the OpenStack native python client and it is not enforcing the port_id.  I'll make this change to OpenStack4j.

**Comment by gondor** [comment]
Ok, changed and a new 2.0.4-SNAPSHOT has been deployed
