### ISSUE TITLE
NullPointerException from listing operation and authentication operation

### ISSUE THREAD

**Issue by symcssn** [gondor/openstack4j#401]
OS4j throws NPE when trying to list objects in a non-existing container with a prefix.

OS4j throws NPE when trying to authenticate with a bad url:
For example if the proper URL is "http://0.0.0.0/v3" but we use "http://0.0.0.0/v3.0", we get NPE from either OSAuthenticator.authenticateV2 or OSAuthenticator.authenticateV3.

Using 2.0.4-Snapshot

**Comment by gondor** [comment]
Thank you, good catch.  New snapshot deployed.

**Comment by symcssn** [comment]
For bad url the NPE problem is solved.

For the non-existing container listing w/ prefix, I still get NPE.

```
objects.list(containerThatDoesNotExist, ObjectListOptions.create().startsWith(anyPrefix))
```

**Comment by gondor** [comment]
Ok thanks.  Fixed the second scenario

**Comment by symcssn** [comment]
Works now. :)
