### ISSUE TITLE
how  to create instance boot from image（create a new volume）

### ISSUE THREAD

**Issue by CyrusKang** [gondor/openstack4j#410]
how to create instance boot from image。

BlockDeviceMappingBuilder blockDeviceMappingBuilder = Builders.blockDeviceMapping() 
				.sourceType("image")
				.uuid("af134ed8-ea2e-4029-81bb-f7f9c2b83ee3")
				.destinationType("volume")
                                .deviceName("/dev/vda")
                                .bootIndex(0);

Lack of parameter volumeSize

ClientResponseException{message=Images with destination_type 'volume' need to have a non-zero size specified, status=400, status-code=BAD_REQUEST}

thanks！

**Comment by gondor** [comment]
Ok, found the issue.. volume size is needed when the source_type is Image and destination type is Volume in your case.  Added new "volumeSize(int v)" to the existing builder to specify the desired size of the destination volume as per OpenStack Nova's API

New 2.0.5-SNAPSHOT deployed with fix and code checked in

**Comment by gondor** [comment]
@CyrusKang  This was verified by another member in duplicate issue #424 .   Closing as it's fixed in 2.0.5-SNAPSHOT.
