### ISSUE TITLE
Connection leak from usage of BaseOpenStackService.Invocation.executeWithResponse()

### ISSUE THREAD

**Issue by symcssn** [gondor/openstack4j#411]
Some methods that use ```BaseOpenStackService.Invocation.executeWithResponse()``` are not leaking connectionns.

For example: ```ObjectStorageContainerServiceImpl.delete()``` does not properly close/consume the response when the delete returns a 409.

Also, it seems like ```ObjectStorageContainerServiceImpl.getMetadata()``` and ```ObjectStorageContainerServiceImpl.invokeMetadata()```, etc.

I'm primarily looking at object related services. This may hold true for other openstack services as well.

**Comment by gondor** [comment]
Thanks for all the info. Issue fixed and new SNAPSHOT deployed

**Comment by symcssn** [comment]
Hi @gondor 

I plan to start verifying this within a few days. Just wanted to update you.

**Comment by symcssn** [comment]
Hi @gondor 

I was looking at ```ObjectStorageContainerServiceImpl```

```java
 private boolean invokeMetadata(String name, String prefix, Map<String, String> metadata) {
        checkNotNull(name);
        checkNotNull(metadata);
        
        return isResponseSuccess(post(Void.class, URI_SEP, name)
                                    .headers(MetadataToHeadersFunction.create(prefix).apply(metadata))
                                    .executeWithResponse(), 204);
    }
```

The response returned by ```executeWithResponse()``` is not closed.

**Comment by symcssn** [comment]
Hi @gondor 

I was looking at ```ObjectStorageObjectServiceImpl```

```java
  public boolean updateMetadata(ObjectLocation location, Map<String, String> metadata) {
        checkNotNull(location);
        checkNotNull(metadata);

        return isResponseSuccess(post(Void.class, location.getURI())
                  .headers(MetadataToHeadersFunction.create(OBJECT_METADATA_PREFIX).apply(metadata))
                  .executeWithResponse(), 204);
    }
```

The response returned by ```executeWithResponse()``` is not closed.

**Comment by symcssn** [comment]
Hi @gondor 

I was looking at ObjectStorageAccountServiceImpl

```java
 public SwiftAccount get() {
        return ParseAccountFunction.INSTANCE.apply(head(Void.class).executeWithResponse());
    }
```

```java
public boolean updateTemporaryUrlKey(String temporaryUrlKey) {
        checkNotNull(temporaryUrlKey);
        return isResponseSuccess(post(Void.class).header(ACCOUNT_TEMPORARY_URL_KEY, temporaryUrlKey).executeWithResponse(), 204);
    }

```

```java
private boolean invokeMetadata(String prefix, Map<String, String> metadata) {
        return isResponseSuccess(post(Void.class)
                                  .headers(MetadataToHeadersFunction.create(prefix).apply(metadata))
                                  .executeWithResponse(), 204);
    }
```

The response returned by ```executeWithResponse()``` is not closed.

**Comment by symcssn** [comment]
Hi @gondor ,

Any updates on closing the responses above?

In the <a href=https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/storage/object/internal/BaseObjectStorageService.java> ```BaseObjectStorageService``` </a> class, the response is not getting closed. There is a boolean called ```closeResponse```, but it's not really being used to close the response.

Also, is there any update on when 2.0.4 will be released officially?

Thanks,

symcssn
