### ISSUE TITLE
ObjectStorageObjectServiceImpl.get(ObjectLocation) throws NPE

### ISSUE THREAD

**Issue by symcssn** [gondor/openstack4j#413]
Hi,

When the server response is not a 2xx, Calling ```MapWithoutMetaPrefixFunction.INSTANCE.apply(resp.headers())``` will cause a NPE.

**Comment by gondor** [comment]
What version of OS4j are you testing with?

**Comment by symcssn** [comment]
I made a mistake. It's not ```ObjectStorageObjectServiceImpl.getMetaData(ObjectLocation)``` throws NPE, but ObjectStorageObjectServiceImpl.get(ObjectLocation)``` that throws NPE for non 2xx. I haven't tested it yet with ```getMetaData``` 

I am using 2.0.4-Snapshot from June 1.


```
 at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1439)
        at java.text.DateFormat.parse(DateFormat.java:364)
        at org.openstack4j.openstack.internal.Parser.toRFC822DateParse(Parser.java:101)
        at org.openstack4j.openstack.storage.object.functions.ParseObjectFunction.apply(ParseObjectFunction.java:33)
        at org.openstack4j.openstack.storage.object.internal.ObjectStorageObjectServiceImpl.get(ObjectStorageObjectServiceImpl.java:72)
        at org.openstack4j.openstack.storage.object.internal.ObjectStorageObjectServiceImpl.get(ObjectStorageObjectServiceImpl.java:80)
```

I have updated the title of this issue.

**Comment by gondor** [comment]
Thanks for all the info. Issue fixed and new SNAPSHOT deployed

**Comment by symcssn** [comment]
Hi Gondor,

I don't know exactty how to repro this server response quickly/easily. I will have to keep you up to date if this issue comes up again.

Thanks!

**Comment by symcssn** [comment]
Hi @gondor,

I was looking at the code, it seems like it is still possible to get NPE from ObjectStorageObjectServiceImpl.get() for non 2xx and 404 values. Here is the snippet of code:
```java
    @Override
    public SwiftObject get(ObjectLocation location) {
        checkNotNull(location);

        HttpResponse resp = head(Void.class, location.getURI()).executeWithResponse();
        try
        {
            if (resp.getStatus() == 404)
                return null;
            
            return ParseObjectFunction.create(location).apply(resp);
        }
        finally {
            closeQuietly(resp);
        }
    }
```

When ```ParseObjectFunction.apply()``` is called, ```.lastModified(Parser.toRFC822DateParse(resp.header(LAST_MODIFIED)))``` will throw NPE.

https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/storage/object/internal/ObjectStorageObjectServiceImpl.java

**Comment by gondor** [comment]
Have you looked at Line 101 at https://github.com/gondor/openstack4j/blob/ffbda964d2ae43bc11ecc38bb7c998e954515ec7/core/src/main/java/org/openstack4j/openstack/internal/Parser.java

This isn't possible since we do a null check and return null if the header value is null.

**Comment by symcssn** [comment]
Ah yes, you're right. I missed that line of code.  

I do have a design question. So, if I were to receive a non successful response other than 404, I will not know what went wrong. I will always be returned a non-null object. 

I don't know how to generate a server 5xx response, but I can easily reproduce a 412 response by passing an empty string for the container. There is no way for my application to know what went wrong because the server response is being discarded. Hence, it won't know what it needs to do to handle the situation. It also makes it more difficult to debug the application.
