### ISSUE TITLE
FlavorServiceImpl.listExtraSpecs NullPointerException

### ISSUE THREAD

**Issue by tangxiaodon89** [gondor/openstack4j#414]
I found an error of this method org.openstack4j.openstack.compute.internal.FlavorServiceImpl.listExtraSpecs .

When i use an flavorId that has deleted.
get(ExtraSpecsWrapper.class, uri("/flavors/%s/os-extra_specs", flavorId)).execute()
will return a null value, and getExtraSpecs() will throw NullPointerException.

checkNotNull(flavorId);
//		return get(ExtraSpecsWrapper.class, uri("/flavors/%s/os-extra_specs", flavorId)).execute().getExtraSpecs();
		ExtraSpecsWrapper extraSpecsWrapper = get(ExtraSpecsWrapper.class, uri("/flavors/%s/os-extra_specs", flavorId)).execute();
		return extraSpecsWrapper == null ? null : extraSpecsWrapper.getExtraSpecs();

**Comment by gondor** [comment]
Thanks, issue resolved and a new SNAPSHOT deployed
