### ISSUE TITLE
Bugs regarding updating object metadata

### ISSUE THREAD

**Issue by symcssn** [gondor/openstack4j#418]
1. ```ObjectPutOptions.metadata()``` is using the wrong prefix: ```CONTAINER_METADATA_PREFIX```. It should be using the prefix for objects ```OBJECT_METADATA_PREFIX```.
2. ```MetadataToHeadersFunction.apply()``` will append the prefix regardless of whether the user supplied the prefix or not because of: ```if (keyLower.startsWith(prefix))```. It should be: ```if (keyLower.startsWith(prefix.toLowerCase()))```

**Comment by gondor** [comment]
Thanks for the details.  Suggested changes made.

**Comment by hudy1987** [comment]
hello,I have a question have bothers me lang time,I use openstack4j v2.0.3 to create a tenant but it always return null:
OSClient os = OSFactory.builder()
				.endpoint("http://control.openstack.test:5000/v2.0")
				.credentials("admin", "admin")
				.tenantName("admin")
				.authenticate();
Tenant tenant = os.identity().tenants()
                .create(Builders.tenant().name("ABC Corp").description("ABC Corporation Tenant").build());
tenant is null. 
please help me, thank you!

**Comment by symcssn** [comment]
Works well now.
