### ISSUE TITLE
Keystone v2 reauthentication not setting the new token into session 

### ISSUE THREAD

**Issue by symcssn** [gondor/openstack4j#425]
<a href = https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java> ```OSAuthenticator.reauthenticate()``` </a> for keystone v2 has an issue where it calls <a href=https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java#L81> ```authenticatev2() ``` </a> with ```reLinkToExistingSession=true```.

<a href = https://github.com/gondor/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/internal/OSAuthenticator.java#L115> Line 116  </a> will never get called because !true=false.Hence, when reauthentication happens, the new token is not saved into the current session. Every request onward will always try to reauthenticate for every request.

**Comment by gondor** [comment]
This seems to be the correct logic.  See comments

```java
  if (!reLinkToExistingSession) // yes true will not fall in here.. this just creates a new client
            return OSClientSession.createSession(access, perspective, config);
        
        // true will hit here so we grab the existing thread local client and associated the newest "access" which has the new token that we just authenticated to and updates the reference to the new.    Theres no need to create a session aka new client since we previously had one and just need to update to the newest authenticated token via the access object
        OSClientSession current = OSClientSession.getCurrent();
        current.access = access;
        return current;
```
Does the above make sense?

**Comment by symcssn** [comment]
When we make requests, we get the session object by calling ```OSClientSession.getCurrent()```. 

```java
    public static OSClientSession getCurrent() {
        return sessions.get();
    }
```

That session is stored inside the ```ThreadLocal<> ``` object. If my understanding of ThreadLocal is correct, when we originally set the variable inside ```ThreadLocal```, it stores a copy of the object at the point in time when it was put in. So, when we do ```current.access = access```, it is not updating the ```ThreadLocal``` copy w/ the updated version of the ```OSClientSession``` object. When we make requests and call ```OSClientSession.getCurrent()```, it is returning the original version of the session object w/ the outdated token. 

BaseOpenStackService

```java
    private <R> Invocation<R> builder(Class<R> returnType, String path, HttpMethod method) {
        OSClientSession ses = OSClientSession.getCurrent();
        RequestBuilder<R> req = HttpRequest.builder(returnType).endpointTokenProvider(ses).config(ses.getConfig()).method(method).path(path);
        return new Invocation<R>(req, serviceType, endpointFunc);
    }
```

**Comment by gondor** [comment]
Ok so is this still an issue then?  Because the above logic is in place already.

**Comment by symcssn** [comment]
No it's not an issue anymore. Thank you very much.
