### ISSUE TITLE
which openstack version is openstack4j 2.0.3 used

### ISSUE THREAD

**Issue by liuyuzhou** [gondor/openstack4j#426]
I have a question about which openstack version is openstack4j 2.0.3 used

**Comment by gondor** [comment]
Primarily IceHouse and almost all features of Juno were tested during that release.

**Comment by liuyuzhou** [comment]
thank you for your answer,and how about 2.04,is it promote to Juno.

**Comment by liuyuzhou** [comment]
How could I find out which version it use?
Is there offer any official document?

**Comment by gondor** [comment]
As a side note each release try's to support the most current and 3 releases back.   For example 2.0.5 will support Kilo, Juno and IceHouse.
