### ISSUE TITLE
Is openstack4j support multi-tenant?

### ISSUE THREAD

**Issue by liuyuzhou** [gondor/openstack4j#427]
Is openstack4j support multi-tenant
In cloudstack,there have the concept of cluster,so I wonder is there have the same concept of cluster in openstack4j?

**Comment by evanstoner** [comment]
OpenStack itself is multi-tenant, and OpenStack4j supports this:

```
OSClient os = OSFactory.builder()
                  .endpoint("http://127.0.0.1:5000/v2.0")
                  .credentials("admin","sample")
                  .tenantName("admin") // this is where you select the tenant
                  .authenticate();
```

However, CloudStack "clusters" look more like OpenStack "host aggregates."

http://docs.cloudstack.apache.org/en/latest/concepts.html#cloudstack-terminology
http://docs.openstack.org/openstack-ops/content/scaling.html

**Comment by liuyuzhou** [comment]
ok,got it,thank you for your answer!
