### ISSUE TITLE
How to synchronization openstack4j's version with openstack?

### ISSUE THREAD

**Issue by liuyuzhou** [gondor/openstack4j#428]
For openstack release 2 versions each year,how openstack4j  synchronization the version with openstack?
If I use openstack4j 2.0.3,can it support the above version of Juno,if can't,what can I do?
Is there have a big difference between openstack4j 2.0.3 and openstack4j 2.0.4?
If change openstack4j 2.0.3 to openstack4j 2.0.4,is there have a big influence?

**Comment by evanstoner** [comment]
OpenStack4j supports OpenStack API versions, not OpenStack releases. For example, Juno supports both the v2 and v3 APIs, and OpenStack4j knows how to communicate with both. If you install Kilo, it has the same v2 and v3 APIs available, so OpenStack4j will continue to work.

You can compare versions of OpenStack4j here: https://github.com/gondor/openstack4j/blob/master/CHANGELOG.md

**Comment by liuyuzhou** [comment]
ok,got it,thank you for your answer!
