### ISSUE TITLE
Could openstakc4j support Mutil-Hypervisor?

### ISSUE THREAD

**Issue by liuyuzhou** [gondor/openstack4j#429]
Could openstakc4j support Mutil-Hypervisor?
What the name of then?

**Comment by evanstoner** [comment]
OpenStack4j doesn't know about hypervisors, it's just an OpenStack client. This is a question about the OpenStack cloud itself. You might find this summit talk interesting: https://www.openstack.org/summit/openstack-summit-atlanta-2014/session-videos/presentation/deploying-openstack-in-a-multi-hypervisor-enterprise-environment

**Comment by gondor** [comment]
@liuyuzhou - @evanstoner answer was correct.  Not much we can do from an OS4j scenario

**Comment by liuyuzhou** [comment]
thank you for your answer!
