### ISSUE TITLE
Add docker container format for image API

### ISSUE THREAD

**Issue by maseev** [gondor/openstack4j#430]
Hello there!

I've run into the following issue. When I'm creating a new image I'm required to specify the container format. In my case it has to be docker (I use nova-docker driver to run new nova instances from docker images). But I can't set it, because ContainerFormat enum provides only bare, unrecognized, ovf, aki, ari, ami. Bare and unrecognized formats don't work in my case. If I set container format for my image as bare or unrecognized I can't run any nova instances from that image (image goes to an error state immediately).

It'll be great to have a docker value in ContainerFormat enum.

Best regards.

**Comment by gondor** [comment]
Thanks for the info.  I have no problem adding this to the next release.

**Comment by maseev** [comment]
Is it ok if I send you a pull request with that fix?

**Comment by gondor** [comment]
Absolutely.  Thanks

**Comment by maseev** [comment]
I think we can close this issue since the fix was merged into upstream.
