### ISSUE TITLE
Unable to Find Supported Services

### ISSUE THREAD

**Issue by gmarchiny** [gondor/openstack4j#448]
I have a Rackspace account. When trying to use OS4J to list images (or use any other services), I get a 404. Here is my Java:

OSClient client = OSFactory.builder()
                .endpoint("https://identity.api.rackspacecloud.com/v2.0/")
                .tenantName(tenantName)
                .credentials(username, password)
                .authenticate();

client.compute().images().list();

I am able to authenticate, and even get a service catalog with valid services in the response from authentication. However, when I try to reach any of the services, I get a 404: 

Sep 09, 2015 3:27:09 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > GET https://identity.api.rackspacecloud.com/v2.0/images/detail
1 > Accept: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
1 > X-Auth-Token: AACA1bgPAYBqrd9tWWCuDvClErPyIPa02QP4bf96MGPjvbkTQ_-2zV9ZI6S44kU9SmT2O7ZRKF-QX_UV_3s-O3ODaoiP1Rs0GHw1rSTyUJMa-BPtm3Z_n2WjaymRd1h3GrAJyCp9bUv5JA

Sep 09, 2015 3:27:10 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Client response received on thread main
1 < 404
1 < Connection: keep-alive
1 < Content-Type: application/json
1 < Date: Wed, 09 Sep 2015 19:27:10 GMT
1 < Server: nginx
1 < Transfer-Encoding: chunked
1 < vary: Accept, Accept-Encoding, X-Auth-Token
1 < X-NewRelic-App-Data: PxQGUF9aDwETVlhSBQgFVUYdFGQHBDcQUQxLA1tMXV1dORYyVBNFDgFCa04sBkpAVR1BMUdDXggDEWFWAEYiEkAOUQFZTF1dXUcVUR9RH1JKBgdSVlIUHgFIQ1BSAlRSBVQCClsAVVQEBF5AZQ==
{"itemNotFound":{"code":404,"message":"Resource Not Found"}}

I have several separate Rackspace accounts, and each gives me the same issue, leading me to believe this is an OS4J issue. 

Just to be sure, I looked at the list of supported services the client was aware of (by using client.getSupportedServices() ), and the result was [UNKNOWN].

Thoughts?

**Comment by b2sc** [comment]
It's an OS4J issue with v2 image service. The URL used ("images/detail") is not supported in v2. It should be only "images". In my opinion, there should be some version awareness in ImageServiceImpl.

Too bad, I don't understand how this could be done. I would need some help on understanding the structure of the OS4J implementation, please.

**Comment by gondor** [comment]
Ok, this one issue fixed and going forward anyone who wants to contribute can verify the provider in the implementation.  The root cause is Rackspace under the covers is reporting a V1 service but not setting the type as V2 unlike other providers.  I have added a new feature to allow the declaration of a provider (HPCloud, Rackspace, etc) so we can make compatibility decisions based on a providers overrides vs raw versions.

Example to verify fix:
```java
OSClient client = OSFactory.builder()
.endpoint("https://identity.api.rackspacecloud.com/v2.0/")
.tenantName(tenantName)
.credentials(username, password)
.provider(CloudProvider.RACKSPACE) // add this line
.authenticate();
```
