### ISSUE TITLE
Tenant and user id not in Volume?

### ISSUE THREAD

**Issue by Jeff-Jing** [gondor/openstack4j#454]
When I use API to list volume details, tenant and user ids are listed as part of volume information. Also when listing servers, each server contains tenant and user ids. Why does volume not provider tenant and user ids?

**Comment by iviireczech** [comment]
AFAIK volume details response never contains user ID (see http://developer.openstack.org/api-ref-blockstorage-v1.html and http://developer.openstack.org/api-ref-blockstorage-v2.html)

Tenant ID should be supported at least in v2, so I've created pull request for it (https://github.com/gondor/openstack4j/pull/507)
