### ISSUE TITLE
Proper way to terminate instance?

### ISSUE THREAD

**Issue by elenamarkoska** [gondor/openstack4j#464]
Hello,

I'm trying to find a way to properly terminate an instance (server).
I did this: 

ActionResponse r = os.compute().floatingIps().removeFloatingIP(server, ipaddress);
os.compute().servers().action(ID, Action.STOP);

But this seemed to put the instance in a shutoff Power state as I checked from the dashboard. I want to be able to terminate it and have it gone from the dashboard too. Also the floating IP wasn't removed, as r.isSuccesful() is a false...

Next I tried this:

os.compute().servers().delete("serverId");

But this didn't seem to do anything.
What am I missing?

**Comment by elenamarkoska** [comment]
For anyone interested, this is the correct line to terminate:

os.compute().servers().delete("serverId");

While os.compute().floatingIps().removeFloatingIP(server, ipaddress); removes the IP from the server, it does not release it. Anyone have an idea as to how I would go about releasing it?

**Comment by gondor** [comment]
If your looking to release it from the tenant that was associated with the server I believe you will want to use os.compute().floatingIps().deallocateIP(id) after the remove

**Comment by elenamarkoska** [comment]
Thank you. I'll look into that and run a few tests. I made a work around this problem for now. :)
