### ISSUE TITLE
SOLVED: Error uploading file to swift

### ISSUE THREAD

**Issue by gschukin** [gondor/openstack4j#469]
I have a sample app with http client connector that uploads a file to swift

```java
OSClient os = OSFactory.builder()
                .withConfig(Config.newConfig().withSSLVerificationDisabled())
                .endpoint('https://xxxx.xxxx:5000/v2.0')
                .credentials('xxxx', 'xxxx')
                .tenantName('xxxx')
                .authenticate();

os.objectStorage().objects().put('container', 'test', new FilePayload(new File('C:\\Temp\\Test.txt')))
```

unfortunately I'm receiving 411 Content Length Required instead of normal upload.

I've tested Openstack python CLI and there were no problems uploading file.

I'm trying to guess whos fault it is mine or server-side.

Thanks

**Comment by symcssn** [comment]
Which version of OS4j core and connectors are you using?

**Comment by gschukin** [comment]
@symcssn I'm using 2.0.6

**Comment by symcssn** [comment]
Which connector?

**Comment by gschukin** [comment]
Httpclient

**Comment by symcssn** [comment]
@gschukin 

I am unable to reproduce this. 

I used 2.0.6 core and httpclient 2.0.6 as well.

**Comment by gschukin** [comment]
It seems that the problem is on the server side.

Openstack4j doesn't send Content-Length header, setting Transfer-Encoding to chuncked which is 100% legit according to swift api documentation.

While Python CLI sets Content-Length header when uploading a file.

@symcssn Can you please log wire and header log messages from httpclient. I'm contatcting my vendor about this issue.

**Comment by symcssn** [comment]
```
 headers - http-outgoing-3 >> PUT /v1/Account/Container/Object HTTP/1.1
 headers - http-outgoing-3 >> Accept: application/json; charset=utf-8
 headers - http-outgoing-3 >> X-Auth-Token: TOKEN
 headers - http-outgoing-3 >> Transfer-Encoding: chunked
 headers - http-outgoing-3 >> Content-Type: application/octet-stream
 headers - http-outgoing-3 >> Host: x.x.x.x:8080
 headers - http-outgoing-3 >> Connection: Keep-Alive
 headers - http-outgoing-3 >> User-Agent: OpenStack4j-Agent
 headers - http-outgoing-3 >> Expect: 100-continue
 headers - http-outgoing-3 >> Accept-Encoding: gzip,deflate
 headers - http-outgoing-3 << HTTP/1.1 100 Continue
 headers - http-outgoing-3 << HTTP/1.1 201 Created
 headers - http-outgoing-3 << Last-Modified: Fri, 09 Oct 2015 17:48:51 GMT
 headers - http-outgoing-3 << Content-Length: 0
 headers - http-outgoing-3 << Etag: xxx
 headers - http-outgoing-3 << Content-Type: text/html; charset=UTF-8
 headers - http-outgoing-3 << X-Trans-Id: xxx-xxx
 headers - http-outgoing-3 << Date: Fri, 09 Oct 2015 17:48:50 GMT
 headers - http-outgoing-3 << Connection: keep-alive
 ```

**Comment by gschukin** [comment]
This issue can be closed as it installation/vendor specific in Mirantis OpenStack 6.1 and may be other version.

I assume, thus not sure, that this is the cause https://bugs.launchpad.net/mos/+bug/1505273

@symcssn Thank you for your help.

**Comment by gondor** [comment]
Thank you for pointing this out.
