### ISSUE TITLE
Documentation uses domainName, which is deprecated

### ISSUE THREAD

**Issue by rski** [gondor/openstack4j#473]
In the [authentication docs](http://www.openstack4j.com/learn/getting-started/#authenticate), the V3 authentication is done using .domainName("domainName"), which is deprecated. 

From core/src/main/java/org/openstack4j/api/client/IOSClientBuilder.java:

```
* DEPRECATED: Please use {@link #credentials(String, String, Identifier)
* 
* Authenticates against the specified domain name
* 
* @param domainName the domain name to authenticate against
* @return V3
*/
@Deprecated
V3 domainName(String domainName);
```

It seems like authentication should be done using a domain Identifier instead.

**Comment by rski** [comment]
An example like this should work:

```
Identifier domainIdentifier = Identifier.byName("example-domain");
OSClient os = OSFactory.builderV3()
                       .endpoint("http://127.0.0.1:5000/v3")
                       .credentials("admin","sample", domainIdentifier)
                       .authenticate();
```

**Comment by gondor** [comment]
Yep you are correct!  Thank you for pointing out the stale documentation.

**Comment by gondor** [comment]
Ok, website updated with your example.  Thank you
