### ISSUE TITLE
Support for Identity V3

### ISSUE THREAD

**Issue by auhlig** [gondor/openstack4j#479]
Currently the Identity service is available in V2 and partially in V3. 
I’d like to bring proper and full support for Identity (Keystone) V3 to OpenStack4j by enhancing current implementation and ,as a first step, adding proper models according to Identity V3 objects like project, domain, user, token, .. .
I will create more granular issues for coming features, implementations (Project-,Domain-,Group- Model&Service., ) on this path. 

I will follow up with my 1st pull request enabling openstack4j to use above mentioned models to authenticate using user+password,token in V3 with above mentioned models.

**Comment by gondor** [comment]
@auhlig I currently have had another engineer reaching out to me about bringing V3 up to standards. Ironically he's out of Berlin as well.  I'm almost toying with diverging versions by branching.  Current 2x project becomes maintenance and we cut a OS4j v3 which could return a different OSClient interface depending on your authentication choice.  This would allow us to spawn of clearer V3 specific interfaces and have cleaner separation.  

That's just my initial thoughts but it might be worth setting up a group discussion and collaborate efforts.. Thoughts?

**Comment by auhlig** [comment]
@gondor Sounds good. I think so too. A group discussion is a good idea.
