### ISSUE TITLE
Unable to properly connect a machine to a network via serverBuilder()

### ISSUE THREAD

**Issue by Muntaner** [gondor/openstack4j#487]
I'm trying to instantiate a virtual machine and connect it to some networks via the serverBuilder() utility.
This is a code snippet example:

    ServerCreate serverCreate = auth.compute().servers().serverBuilder()
     .name("Machine test")
     .keypairName(key)
     .image(image)
     .flavor("3")
     .networks(networks)
     .build();
    server = auth.compute().servers().bootAndWaitActive(serverCreate, 1000);

After the server creation and boot, I can see the connection of the machine to the networks on the dashboard and also "inside" the VM, because there actually is a NIC for each network that was specified in the "networks" field of the builder. But the problem is that those NICs are not properly configured, since they don't get the IP that Openstack assigned to it.
If the attach to the network happens AFTER the virtual machine has been booted, for example via a Port, the problem does not exist.
I can't understand if this is an issue or my error. The networks have subnets with proper CIDRs and DHCP enabled.

**Comment by Muntaner** [comment]
I'm very sorry, I solved it by myself. I haven't noticed that the "admin state" of the network was DOWN. I turned it UP and everything worked fine.

**Comment by gondor** [comment]
No trouble at all. Glad you solved it!
