### ISSUE TITLE
Telemetry Events API

### ISSUE THREAD

**Issue by iviireczech** [gondor/openstack4j#492]
OpenStack4j currently does not have support for Telemetry Events API as described on http://docs.openstack.org/developer/ceilometer/webapi/v2.html#events-and-traits. This is an enhancement to track the completion of this support.

**Comment by gondor** [comment]
Thanks again for the great contribution.  PR has been merged and a new 2.0.8-SNAPSHOT deployed.  I'm aiming to release 2.0.8 on Friday so this made the cut :)
