### ISSUE TITLE
Use Java 7 as the minimum version for openstack4j v3

### ISSUE THREAD

**Issue by dhague** [gondor/openstack4j#496]
openstack4j 2.x uses Java 1.6 as the minimum version according to pom.xml.

1.6 was EOL in Feb 2013 (see http://www.oracle.com/technetwork/java/eol-135779.html), and openstack4j 3.x will be based on the Identity V3 API, which was released in OpenStack Grizzly in April 2013.

Therefore it makes sense to have a minimum of at least Java 7 for the v3 release, and this would allow us to use the additional features introduced in Java 7 (see http://www.oracle.com/technetwork/java/javase/jdk7-relnotes-418459.html).

**Comment by gondor** [comment]
Good call.  I agree with this change.  As part of this change could you also remove the jersey2-jdk16 connector/module. It was simply there for JDK16 users at the time but going forward won't be needed.
