### ISSUE TITLE
Use Enums instead of String for sourceType and destinationType in block mappings 

### ISSUE THREAD

**Issue by gschukin** [gondor/openstack4j#500]
Currently BlockDeviceMappingBuilder#sourceType and BlockDeviceMappingBuilder#destinationType use string as parameter. According to [documentation](http://docs.openstack.org/developer/nova/block_device_mapping.html)
sourceType can be one of:
* image
* volume
* snapshot
* blank

destinationType can be one of:
* local
* volume

**Comment by gondor** [comment]
Now using Enums
