### ISSUE TITLE
The network docs point to non existing links

### ISSUE THREAD

**Issue by rski** [gondor/openstack4j#505]
In http://www.openstack4j.com/learn/network/ there is a dead link to Havana documentation:
"More information about routers can be found at Neutron Concepts"
The Neutron Concepts link should be changed to this:
http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-concepts.html

Although Juno has not reached EOL, that section is the same for Kilo and Juno so the link might as well be to the Kilo docs.

**Comment by rski** [comment]
Also, some <br> tags have sneaked in the code examples in the lbaas section
 
http://www.openstack4j.com/learn/network/networks-lbaas/

**Comment by gondor** [comment]
Ok thanks, the original issue has been fixed and link updated on the site.  Not sure I under your comment about tags however

**Comment by gondor** [comment]
Awesome, thanks.  Fixed it and site has been updated.  Please close after confirming.

**Comment by rski** [comment]
example of a \<br\> tag that shouldn't be there
![screenshot from 2015-11-13 09 37 06](https://cloud.githubusercontent.com/assets/2960312/11141070/3d92ac28-89ea-11e5-99e1-7503368e5bc8.png)

**Comment by rski** [comment]
looks good, thanks for fixing that.
