### ISSUE TITLE
betamax for tests

### ISSUE THREAD

**Issue by auhlig** [gondor/openstack4j#517]
This issue addresses @dhague's proposal to perform tests using Betamax - http://freeside.co/betamax/. 
That will make testing easier and cleaner as it handles recorded HTTP traffic in one single yaml-file instead of one file per request in currently used mock-tool.

**Comment by gondor** [comment]
:+1:

**Comment by auhlig** [comment]
Unfortunately we discovered a bug  in betamax 1.1.2The HttpClient used by betamax does not support HTTP PATCH method.
