### ISSUE TITLE
listservers testcase failed

### ISSUE THREAD

**Issue by kkxue** [gondor/openstack4j#529]
Hi,
in my openstack of kilo,listservers get ip addresses testcase failed.
<pre>
assertEquals("192.168.0.3", s.getAddresses().getAddresses("private").get(0).getAddr());
</pre>

**Comment by gondor** [comment]
Could you provide more info like the output of `s.getAddresses()`?

**Comment by kkxue** [comment]
HI,soorry for the late.
here is the result sample:

[NovaServer{id=8c04ced5-2705-482e-9414-6170bb4bed71, name=testtest, image={id=71b5d650-8d48-4118-8c90-603342ad9058, links=[{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/images/71b5d650-8d48-4118-8c90-603342ad9058, rel=bookmark}]}, flavor=NovaFlavor{id=2, ephemeral=0, swap=0, rxtx_factor=1.0, is_public=true, links=[GenericLink{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/flavors/2, rel=bookmark}], 
}, status=ACTIVE, diskconfig=MANUAL, userId=cfc07deb58f842bc87c524b9a6f27fca, created=Mon Dec 07 09:29:05 CST 2015, updated=Mon Dec 07 09:37:32 CST 2015, launched at=Mon Dec 07 09:29:14 CST 2015, tenantId=c3abb706c33346bf89f662da4bfe96d0, hostId=5a8c0c40660ef9bc3c69d87d6e3944559bae9b1f4f87a87feccd64af, addresses=NovaAddresses{addresses={int-net-1=[NovaAddress{address=10.0.0.22, type=fixed, version=4, macaddr=fa:16:3e:1f:c9:5f, 
}]}, 
}, hypervisor host=computer-01.com, powerstate=1, instanceName=instance-00000086, vmState=active, metadata={}}, NovaServer{id=eefc8cc3-15aa-4eea-be46-27004df5dc2f, name=test, image={id=71b5d650-8d48-4118-8c90-603342ad9058, links=[{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/images/71b5d650-8d48-4118-8c90-603342ad9058, rel=bookmark}]}, flavor=NovaFlavor{id=2, ephemeral=0, swap=0, rxtx_factor=1.0, is_public=true, links=[GenericLink{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/flavors/2, rel=bookmark}], 
}, status=ACTIVE, diskconfig=MANUAL, userId=cfc07deb58f842bc87c524b9a6f27fca, created=Sat Dec 05 17:54:46 CST 2015, updated=Sat Dec 05 17:54:52 CST 2015, launched at=Sat Dec 05 17:54:52 CST 2015, tenantId=c3abb706c33346bf89f662da4bfe96d0, hostId=6e65fb2683dd5b1faa9078b2f65ca80a04021f98615ca0bb2fceff22, addresses=NovaAddresses{addresses={int-net-1=[NovaAddress{address=10.0.0.21, type=fixed, version=4, macaddr=fa:16:3e:fe:75:2e, 
}]}, 
}, hypervisor host=controller.com, powerstate=1, instanceName=instance-00000085, vmState=active, metadata={}}, NovaServer{id=90acdbac-ca1e-4d88-8f95-273ab869189e, name=a1, image={id=7e1ed145-b758-4ef7-a0e9-080ecba12093, links=[{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/images/7e1ed145-b758-4ef7-a0e9-080ecba12093, rel=bookmark}]}, flavor=NovaFlavor{id=2, ephemeral=0, swap=0, rxtx_factor=1.0, is_public=true, links=[GenericLink{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/flavors/2, rel=bookmark}], 
}, status=ACTIVE, diskconfig=AUTO, userId=cfc07deb58f842bc87c524b9a6f27fca, created=Fri Dec 04 19:53:27 CST 2015, updated=Fri Dec 04 19:53:34 CST 2015, launched at=Fri Dec 04 19:53:34 CST 2015, tenantId=c3abb706c33346bf89f662da4bfe96d0, hostId=5a8c0c40660ef9bc3c69d87d6e3944559bae9b1f4f87a87feccd64af, addresses=NovaAddresses{addresses={net1=[NovaAddress{address=192.170.1.6, type=fixed, version=4, macaddr=fa:16:3e:da:38:fd, 
}]}, 
}, hypervisor host=computer-01.com, powerstate=1, instanceName=instance-00000084, vmState=active, metadata={}}, NovaServer{id=82574b07-f6ca-4497-9641-8d91ad356da4, name=win8_3, image={id=2b1db46f-291c-4178-acd5-7f15f0c9aaf0, links=[{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/images/2b1db46f-291c-4178-acd5-7f15f0c9aaf0, rel=bookmark}]}, flavor=NovaFlavor{id=2, ephemeral=0, swap=0, rxtx_factor=1.0, is_public=true, links=[GenericLink{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/flavors/2, rel=bookmark}], 
}, status=ACTIVE, diskconfig=AUTO, userId=cfc07deb58f842bc87c524b9a6f27fca, created=Fri Dec 04 17:15:24 CST 2015, updated=Fri Dec 04 17:15:30 CST 2015, launched at=Fri Dec 04 17:15:30 CST 2015, tenantId=c3abb706c33346bf89f662da4bfe96d0, hostId=6e65fb2683dd5b1faa9078b2f65ca80a04021f98615ca0bb2fceff22, addresses=NovaAddresses{addresses={int-net-1=[NovaAddress{address=10.0.0.20, type=fixed, version=4, macaddr=fa:16:3e:0c:39:81, 
}]}, 
}, hypervisor host=controller.com, powerstate=1, instanceName=instance-00000083, vmState=active, metadata={}}, NovaServer{id=eaf958da-3174-4ab7-b4ee-502073d9d0e8, name=u3, image={id=7e1ed145-b758-4ef7-a0e9-080ecba12093, links=[{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/images/7e1ed145-b758-4ef7-a0e9-080ecba12093, rel=bookmark}]}, flavor=NovaFlavor{id=2, ephemeral=0, swap=0, rxtx_factor=1.0, is_public=true, links=[GenericLink{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/flavors/2, rel=bookmark}], 
}, status=ACTIVE, diskconfig=AUTO, userId=cfc07deb58f842bc87c524b9a6f27fca, created=Thu Dec 03 15:57:18 CST 2015, updated=Fri Dec 04 13:17:32 CST 2015, launched at=Thu Dec 03 15:57:23 CST 2015, tenantId=c3abb706c33346bf89f662da4bfe96d0, hostId=5a8c0c40660ef9bc3c69d87d6e3944559bae9b1f4f87a87feccd64af, addresses=NovaAddresses{addresses={int-net-1=[NovaAddress{address=10.0.0.18, type=fixed, version=4, macaddr=fa:16:3e:b2:75:be, 
}, NovaAddress{address=192.168.1.96, type=floating, version=4, macaddr=fa:16:3e:b2:75:be, 
}]}, 
}, hypervisor host=computer-01.com, powerstate=1, instanceName=instance-00000081, vmState=active, metadata={}}, NovaServer{id=8d536bf1-b406-44ce-b33a-470619d417a9, name=u1, image={id=7e1ed145-b758-4ef7-a0e9-080ecba12093, links=[{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/images/7e1ed145-b758-4ef7-a0e9-080ecba12093, rel=bookmark}]}, flavor=NovaFlavor{id=2, ephemeral=0, swap=0, rxtx_factor=1.0, is_public=true, links=[GenericLink{href=http://192.168.1.116:8774/c3abb706c33346bf89f662da4bfe96d0/flavors/2, rel=bookmark}], 
}, status=ACTIVE, diskconfig=AUTO, userId=cfc07deb58f842bc87c524b9a6f27fca, created=Thu Dec 03 15:20:18 CST 2015, updated=Fri Dec 04 11:05:17 CST 2015, launched at=Thu Dec 03 15:20:42 CST 2015, tenantId=c3abb706c33346bf89f662da4bfe96d0, hostId=6e65fb2683dd5b1faa9078b2f65ca80a04021f98615ca0bb2fceff22, addresses=NovaAddresses{addresses={int-net-1=[NovaAddress{address=10.0.0.17, type=fixed, version=4, macaddr=fa:16:3e:c9:62:be, 
}, NovaAddress{address=192.168.1.95, type=floating, version=4, macaddr=fa:16:3e:c9:62:be, 
}]}, 
}, hypervisor host=controller.com, powerstate=1, instanceName=instance-0000007f, vmState=active, metadata={}}]

**Comment by gondor** [comment]
It you look at the output you 

a. Don't have a "private" network in the " NovaAddresses output (which is coming from OpenStack).  I only see a "net1" and "int-net-1" networks.  I believe this is a change in your OpenStack deployment as a result of upgrading to Kilo.

**Comment by kkxue** [comment]
maybe i am not speak clearly.
i know your mean,but when i execute the code below:
```
System.out.println(server.getAddresses().getAddresses("net1").get(0).getAddr());
```
NullPointerException happend.
```
NullPointerException occured : null
```

**Comment by kkxue** [comment]
ok,got it
