### ISSUE TITLE
Add initial implementation of V3 ProjectService

### ISSUE THREAD

**Issue by auhlig** [gondor/openstack4j#537]
This issue is for the initial implementation of the project service for identity v3 covering all CRUD operations.
Comes with tests.

**Comment by sjpatil** [comment]
Hi auhlig,

I need v3 authentication feature. Specifically authentication for all scopes i.e. default, domain and project. I also need API to list project that domain users have access to.  
It will be really helpful if you let me know by when code will be added so that I can at least try those APIs very quickly.

**Comment by auhlig** [comment]
Hi @sjpatil,
We're planning on releasing a new version of OpenStack4j, which will support V3 the end of this month.

Currently we're just struggling with the new test and mocking-tool, betamax, we're planning to introduce. After that we will contribute the rest of v3 according to the issues we've raised and release.

**Comment by sjpatil** [comment]
Thanks Arno,
We will try code on v3_collaboration branch

**Comment by vinodborole** [comment]
Hi @auhlig 

I tried to build the code from v3_collaboration branch and i am getting following errors. I have tried this with both java 1.6 and 1.7. any suggestions?


[ERROR] /C:/Users/viborole/Documents/cloudconnector/cirrus/openstack4j-3_collaboration/core/src/main/java/org/openstack4j/model/compute/actions/LiveMigrateOptions.java:[72,19] C:\Users\viborole\Documents\cloudconnector\cirrus\openstack4j-3_collaboration\core\src\main\java\org\openstack4j\model\compute\actions\LiveMigrateOptions.java:72: type parameters of <T>T cannot be determined; no unique maximal instance exists for type variable T with upper bounds boolean,java.lang.Object
[ERROR] /C:/Users/viborole/Documents/cloudconnector/cirrus/openstack4j-3_collaboration/core/src/main/java/org/openstack4j/model/compute/actions/LiveMigrateOptions.java:[76,19] C:\Users\viborole\Documents\cloudconnector\cirrus\openstack4j-3_collaboration\core\src\main\java\org\openstack4j\model\compute\actions\LiveMigrateOptions.java:76: type parameters of <T>T cannot be determined; no unique maximal instance exists for type variable T with upper bounds boolean,java.lang.Object

**Comment by auhlig** [comment]
Hi @vinodborole,

I cannot reproduce that. Also looking at the code section https://github.com/gondor/openstack4j/blob/v3_collaboration/core/src/main/java/org/openstack4j/model/compute/actions/LiveMigrateOptions.java#L71-L76 makes me wonder what could cause that error. 
Could that be related to the environment you're using?

**Comment by vinodborole** [comment]
@auhlig  I modified the class by changing the return type to a 'Boolean' object instead of a primitive 'boolean' type and it worked

    public Boolean getBlockMigration() {
        return get(Option.BLOCK_MIGRATION);
    }
    
    public Boolean getDiskOverCommit() {
        return get(Option.DISK_OVER_COMMIT);
    }


Further it failed in test execution for Jersey connector with major minor version problem, anyways we do not use this connector so i skipped the tests and was able to build the project.

We are using the core library with http as the connector, was wondering if you support backward compatibility on 3.0.0-SNAPSHOT for v2 keystone authentication, surprisingly we do not see the code for this in this branch? In our case we want to use both v2 authentication and v3 authentication as per clients environment as we are building a generic implementation.

**Comment by auhlig** [comment]
@vinodborole

**Comment by vinodborole** [comment]
Hey @auhlig 

That is not a good news for us :-( Don't you think it would difficult to maintain two different versions  of libraries 2.x and 3.x in the long run, also its easy for the consumer to create one generic implementation that can use v2 or v3 with the same library based on the choice of the environment he is using. Can you tell me design wise, how easy or difficult it is to integrate the v2 keystone authentication functionality in 3.x library? may be we can attempt to support our requirement.

For jersey connector following are the exception we see  for test case execution when we build the 3.x SNAPSHOT

			org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project openstack4j-jersey2: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
			org.testng.TestNGException: Cannot instantiate class org.openstack4j.api.compute.FloatingIPTests 
			at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:38)
					
			Caused by: java.lang.UnsupportedClassVersionError: com/squareup/okhttp/mockwebserver/MockWebServer : Unsupported major.minor version 51.0
					
			Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process org.testng.TestNGException: Cannot instantiate class org.openstack4j.api.compute.FloatingIPTests

			Caused by: java.lang.UnsupportedClassVersionError: com/squareup/okhttp/mockwebserver/MockWebServer : Unsupported major.minor version 51.0
			at java.lang.ClassLoader.defineClass1(Native Method)
					
			Caused by: java.lang.RuntimeException: There was an error in the forked process
			org.testng.TestNGException: Cannot instantiate class org.openstack4j.api.compute.FloatingIPTests

			Caused by: java.lang.UnsupportedClassVersionError: com/squareup/okhttp/mockwebserver/MockWebServer : Unsupported major.minor version 51.0
			at java.lang.ClassLoader.defineClass1(Native Method)
