### ISSUE TITLE
[Trystack] OSClient with multi-thread

### ISSUE THREAD

**Issue by Ocelot92** [gondor/openstack4j#550]
Hi, i need to use 1 openstack client between 2 threads for my application.
I found this "http://www.openstack4j.com/learn/threads/" so i coded a simple java application:
Main:
```
	public static void main(String[] args) {
		OSClient OS = OSFactory.builder()
				.endpoint("xxxxxxxx/v2.0")
				[...]
				.authenticate();
		Uploader upl= new Uploader(OS.getAccess());
		Thread t1 = new Thread(upl);
		t1.start();
		[...]
		}
```
Uploader:
```
	public Uploader(Access acs){
		OS = OSFactory.clientFromAccess(acs);
	}
	@Override
	public void run() {
		System.out.println("test1");
		OS.objectStorage().containers().create("Container");
		System.out.println("test2");
	}
```

I get "Unable to retrieve current session. Please verify thread has a current session available.". Any suggestion? Thanks

**Comment by appsdesh** [comment]
Did you try saving the access in uploader and performing  OS = OSFactory.clientFromAccess(acs); in run() ?

**Comment by Ocelot92** [comment]
Thanks! "saving the access in uploader and performing OS = OSFactory.clientFromAccess(acs); in run()" this works indeed! I suggest to adjust the example here: http://www.openstack4j.com/learn/threads/
