### ISSUE TITLE
Support manila

### ISSUE THREAD

**Issue by gonzolino** [gondor/openstack4j#571]
Openstack4J should support the Shared File Systems (Manila) API.

**Comment by gonzolino** [comment]
I would like to work on this issue, so it would be cool if somebody could assign it to me.

**Comment by gondor** [comment]
@gonzolino It's yours.  Unfortunately GitHub doesn't allow assignments on issues unless I made you an admin of this project.  

Please fork, add feature and submit a pull request when complete with the Issue # in the comment.  

Thanks in advance for the contribution.
