### ISSUE TITLE
Cannot create HostAggregate

### ISSUE THREAD

**Issue by Silence803** [gondor/openstack4j#606]
I cannot create new HostAggregate.......

openstack version L.
openstack4j version 2.0.9

my code:

    HostAggregate hostAggregate = osClient.compute().hostAggregates()
                                                        .create(name,availabilityZone);

Getting the following error: 
1 > POST http://192.168.10.36:8774/v2.1/7564acb691704aaca2b2653229959c71/os-aggregates
1 > Accept: application/json
1 > Content-Type: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
1 > X-Auth-Token: fad14589e5b143c1b84b50b56afe95a0
{
  "aggregate" : {
    "deleted" : false,
    "name" : "test",
    "avaiablityZone" : "test",
    "availability_zone" : "test"
  }
}
< 400
2 < Connection: keep-alive
2 < Content-Length: 279
2 < Content-Type: application/json; charset=UTF-8
2 < Date: Tue, 15 Mar 2016 03:01:58 GMT
2 < Vary: X-OpenStack-Nova-API-Version
2 < X-Compute-Request-Id: req-8e9a942f-7534-4328-9843-af9b016416ad
2 < X-Openstack-Nova-Api-Version: 2.1
{"badRequest": {"message": "Invalid input for field/attribute aggregate. Value: {u'deleted': False, u'name': u'test', u'avaiablityZone': u'test', u'availability_zone': u'test'}. Additional properties are not allowed (u'deleted', u'avaiablityZone' were unexpected)", "code": 400}}

**Comment by Cherry522** [comment]
We also encountered this problem, how do you solve the problem?

**Comment by vinodborole** [comment]
@Cherry522 Can you try the latest version, this should not be the case as the create method takes only two parameters name and zone

https://github.com/ContainX/openstack4j/blob/f93d64caeba993aa401681e03ac3e802b7c0af33/core/src/main/java/org/openstack4j/openstack/compute/domain/NovaHostAggregate.java

**Comment by Cherry522** [comment]
I use the version is 3.0.2, is the latest release version. I did run into this problem.Could you create  'HostAggregate' successfully?

**Comment by vinodborole** [comment]
Is it possible for you to try 3.0.3-SNAPSHOT quickly?

**Comment by Cherry522** [comment]
I just tested the 3.0.3-SNAPSHOT version, but it still doesn't solve it.

**Comment by vinodborole** [comment]
Can you please post the full trace log?

**Comment by Cherry522** [comment]
16:00:09.500 [main] DEBUG org.openstack4j.core.transport.internal.HttpExecutor - Executing Request: http://10.42.16.32:5000/v3 -> /auth/tokens
16:00:09.684 [main] DEBUG org.jboss.resteasy.plugins.providers.DocumentProvider - Unable to retrieve config: expandEntityReferences defaults to true
16:00:09.691 [main] DEBUG org.jboss.resteasy.plugins.providers.DocumentProvider - Unable to retrieve config: expandEntityReferences defaults to true
16:00:10.222 [main] DEBUG org.apache.http.impl.conn.BasicClientConnectionManager - Get connection for route {}->http://10.42.16.32:5000
16:00:10.233 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnectionOperator - Connecting to 10.42.16.32:5000
16:00:10.249 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
16:00:10.251 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
16:00:10.251 [main] DEBUG org.apache.http.client.protocol.RequestTargetAuthentication - Target auth state: UNCHALLENGED
16:00:10.252 [main] DEBUG org.apache.http.client.protocol.RequestProxyAuthentication - Proxy auth state: UNCHALLENGED
16:00:10.254 [main] DEBUG org.apache.http.impl.client.DefaultHttpClient - Attempt 1 to execute request
16:00:10.255 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Sending request: POST /v3/auth/tokens HTTP/1.1
16:00:10.255 [main] DEBUG org.apache.http.wire -  >> "POST /v3/auth/tokens HTTP/1.1[\r][\n]"
16:00:10.256 [main] DEBUG org.apache.http.wire -  >> "OS4J-Auth-Command: Tokens[\r][\n]"
16:00:10.256 [main] DEBUG org.apache.http.wire -  >> "Content-Length: 340[\r][\n]"
16:00:10.256 [main] DEBUG org.apache.http.wire -  >> "Content-Type: application/json[\r][\n]"
16:00:10.256 [main] DEBUG org.apache.http.wire -  >> "Host: 10.42.16.32:5000[\r][\n]"
16:00:10.256 [main] DEBUG org.apache.http.wire -  >> "Connection: Keep-Alive[\r][\n]"
16:00:10.256 [main] DEBUG org.apache.http.wire -  >> "[\r][\n]"
16:00:10.256 [main] DEBUG org.apache.http.headers - >> POST /v3/auth/tokens HTTP/1.1
16:00:10.256 [main] DEBUG org.apache.http.headers - >> OS4J-Auth-Command: Tokens
16:00:10.256 [main] DEBUG org.apache.http.headers - >> Content-Length: 340
16:00:10.256 [main] DEBUG org.apache.http.headers - >> Content-Type: application/json
16:00:10.256 [main] DEBUG org.apache.http.headers - >> Host: 10.42.16.32:5000
16:00:10.257 [main] DEBUG org.apache.http.headers - >> Connection: Keep-Alive
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "{[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "  "auth" : {[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "    "identity" : {[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "      "password" : {[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "        "user" : {[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "          "name" : "admin",[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "          "domain" : {[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "            "name" : "Default"[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "          },[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "          "password" : "admin"[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "        }[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "      },[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "      "methods" : [ "password" ][\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "    },[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "    "scope" : {[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "      "domain" : {[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "        "name" : "Default"[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "      }[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "    }[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "  }[\n]"
16:00:10.257 [main] DEBUG org.apache.http.wire -  >> "}"
16:00:10.502 [main] DEBUG org.apache.http.wire -  << "HTTP/1.1 201 Created[\r][\n]"
16:00:10.504 [main] DEBUG org.apache.http.wire -  << "Date: Wed, 21 Sep 2016 08:00:09 GMT[\r][\n]"
16:00:10.504 [main] DEBUG org.apache.http.wire -  << "Server: Apache[\r][\n]"
16:00:10.504 [main] DEBUG org.apache.http.wire -  << "Content-Length: 6596[\r][\n]"
16:00:10.505 [main] DEBUG org.apache.http.wire -  << "X-Subject-Token: gAAAAABX4j4JmcbATZeuz446X1rxfQ7uyLrsuFvnyyeXDh4VMSdgPZWHaWkL_CAdX5zFCAaxIyQaRGm_VLs9_cZQvxhApf_u4MEufNbNJEiuQnOAS5Zq6aFzCpQrSfHYFWdJIPnA3XHV6YvfwUXVcbvCUM3Vex0ZtA[\r][\n]"
16:00:10.505 [main] DEBUG org.apache.http.wire -  << "Vary: X-Auth-Token[\r][\n]"
16:00:10.505 [main] DEBUG org.apache.http.wire -  << "x-openstack-request-id: req-8e023989-f225-4c10-990f-29255fa22ae3[\r][\n]"
16:00:10.505 [main] DEBUG org.apache.http.wire -  << "Connection: close[\r][\n]"
16:00:10.505 [main] DEBUG org.apache.http.wire -  << "Content-Type: application/json[\r][\n]"
16:00:10.505 [main] DEBUG org.apache.http.wire -  << "[\r][\n]"
16:00:10.505 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Receiving response: HTTP/1.1 201 Created
16:00:10.506 [main] DEBUG org.apache.http.headers - << HTTP/1.1 201 Created
16:00:10.506 [main] DEBUG org.apache.http.headers - << Date: Wed, 21 Sep 2016 08:00:09 GMT
16:00:10.506 [main] DEBUG org.apache.http.headers - << Server: Apache
16:00:10.506 [main] DEBUG org.apache.http.headers - << Content-Length: 6596
16:00:10.506 [main] DEBUG org.apache.http.headers - << X-Subject-Token: gAAAAABX4j4JmcbATZeuz446X1rxfQ7uyLrsuFvnyyeXDh4VMSdgPZWHaWkL_CAdX5zFCAaxIyQaRGm_VLs9_cZQvxhApf_u4MEufNbNJEiuQnOAS5Zq6aFzCpQrSfHYFWdJIPnA3XHV6YvfwUXVcbvCUM3Vex0ZtA
16:00:10.506 [main] DEBUG org.apache.http.headers - << Vary: X-Auth-Token
16:00:10.506 [main] DEBUG org.apache.http.headers - << x-openstack-request-id: req-8e023989-f225-4c10-990f-29255fa22ae3
16:00:10.506 [main] DEBUG org.apache.http.headers - << Connection: close
16:00:10.506 [main] DEBUG org.apache.http.headers - << Content-Type: application/json
16:00:10.531 [main] DEBUG org.apache.http.wire -  << "{"token": {"domain": {"id": "default", "name": "Default"}, "methods": ["password"], "roles": [{"id": "f4b121e4ac454e22b7340c757023072d", "name": "admin"}], "expires_at": "2016-09-21T09:00:09.978456Z", "catalog": [{"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.16.32:8082", "region": "RegionOne", "interface": "public", "id": "390279d5a8f445519c876b6082900452"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:8082", "region": "RegionOne", "interface": "admin", "id": "e1df5160d8cd4f1fb5934cdd8e28d49e"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:8082", "region": "RegionOne", "interface": "internal", "id": "f134a65fd3da447f96e6f68f9e23fd79"}], "type": "application-catalog", "id": "02dc2c816492475e95ad77e7eb719627", "name": "murano"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.23.22:8080/swift/v1", "region": "RegionOne", "interface": "admin", "id": "3aa53483963c4685bda4cdd128a7b3f8"}, {"region_id": "RegionOne", "url": "http://10.42.16.32:8080/swift/v1", "region": "Regio"
16:00:10.594 [main] DEBUG org.apache.http.wire -  << "nOne", "interface": "public", "id": "9c9f232f18ff428598f31c68e8a598fc"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:8080/swift/v1", "region": "RegionOne", "interface": "internal", "id": "d545464007154de1af39fa0029c91de9"}], "type": "object-store", "id": "171f69c18f72447cb833a7294bb7b4c9", "name": "swift"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.23.22:8774/v2.1", "region": "RegionOne", "interface": "internal", "id": "0878705e4e6945dcaedf4f891b292373"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:8774/v2.1", "region": "RegionOne", "interface": "admin", "id": "c4d2bd48b4a845f2ba9efd88741f3b7c"}, {"region_id": "RegionOne", "url": "http://10.42.16.32:8774/v2.1", "region": "RegionOne", "interface": "public", "id": "d3a8f2792cad489b8866fa8925469c4c"}], "type": "compute", "id": "1c8d2b3e08e24131be4c46c3fe41096d", "name": "nova"}, {"endpoints": [], "type": "data-processing", "id": "24646b1829e44c1f84fd78d7f698e131", "name": "sahara"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.23.22:8777", "region": "RegionOne", "interface": "admin", "id": "4eb21dd8638d40729f071e3a83c78f49"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:8777", "region": "RegionOne", "interface": "internal", "id": "9db485dc95fd4450be8eea77ea840b97"}, {"region_id": "RegionOne", "url": "http://10.42.16.32:8777", "region": "RegionOne", "interface": "public", "id": "a20f046c239548ebab8cb884d2e0c874"}], "type": "metering", "id": "3c764165264b4025b8705fc4cf111c3a", "name": "ceilometer"}, {"endpoints": [], "type": "orchestration", "id": "42d5e82c2f2b4ab58db2655d4b1cf1bb", "name": "heat"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.23.22:8000/v1", "region": "RegionOne", "interface": "admin", "id": "2b41d08b7aeb468bb0bf2fc8db9a17ca"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:8000/v1", "region": "RegionOne", "interface": "internal", "id": "780e3c747df34996b48227d9849daa13"}, {"region_id": "RegionOne", "url": "http://10.42.16.32:8000/v1", "region": "RegionOne", "interface": "public", "id": "e2f97c0422c2421f80d0ee38893b0cb6"}], "type": "cloudformation", "id": "51b43877d9f24faaa8b5bffcce0368f5", "name": "heat-cfn"}, {"endpoints": [], "type": "volume", "id": "681a48ec86d04277936f59efb5d974a1", "name": "cinder"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.23.22:35357/v3", "region": "RegionOne", "interface": "admin", "id": "046af2d493db4b45b73a48394210fad7"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:5000/v3", "region": "RegionOne", "interface": "internal", "id": "102baeb5fa2d4cb3b96a68087c823066"}, {"region_id": "RegionOne", "url": "http://10.42.16.32:5000/v3", "region": "RegionOne", "interface": "public", "id": "3ed4d24fb33647318b63ecd2ba27b55f"}], "type": "identity", "id": "6b0ba5337c524418a4d9c2fdfe9cdf8f", "name": "keystone"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.23.22:9696", "region": "RegionOne", "interface": "admin", "id": "1d7a6da5e2624b31902e4b060451f246"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:9696", "region": "RegionOne", "interface": "internal", "id": "ac5f49ac1d5441f9aeb07c4396abd20c"}, {"region_id": "RegionOne", "url": "http://10.42.16.32:9696", "region": "RegionOne", "interface": "public", "id": "e710749dc32e482c82f94812f0cfe859"}], "type": "network", "id": "72b02e5cc924409ab4ad3865abef13a6", "name": "neutron"}, {"endpoints": [], "type": "compute_legacy", "id": "79b7908c8ffc4bd1a31187d45314904e", "name": "compute_legacy"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.16.32:8042", "region": "RegionOne", "interface": "public", "id": "3ebcca55236247998d92c3fc7ff2e527"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:8042", "region": "RegionOne", "interface": "admin", "id": "9407771ac0954727beac75bcee8500e8"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:8042", "region": "RegionOne", "interface": "internal", "id": "9833f9ec0b754fb0bffa6924c6c13ac0"}], "type": "alarming", "id": "8255141bf24a459d9a7b26a5d200840a", "name": "aodh"}, {"endpoints": [], "type": "volumev2", "id": "9211ca6a2f334c8ab05be58c84f70c36", "name": "cinderv2"}, {"endpoints": [], "type": "volumev3", "id": "cfef0653145642cb9cae2fe5b9df9f99", "name": "cinderv3"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.23.22:9292", "region": "RegionOne", "interface": "internal", "id": "3f31247709264131a60a3c18b9e956fb"}, {"region_id": "RegionOne", "url": "http://10.42.16.32:9292", "region": "RegionOne", "interface": "public", "id": "4728f13ac4844b35a1c27633eddd01a3"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:9292", "region": "RegionOne", "interface": "admin", "id": "95a2252c98bb47e5ab38e92aebf3fa1b"}], "type": "image", "id": "de305523facd4f87b5f19809b20faebe", "name": "glance"}, {"endpoints": [{"region_id": "RegionOne", "url": "http://10.42.16.32:9494", "region": "RegionOne", "interface": "public", "id": "34351c58617644d896cb3e345df73c07"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:9494", "region": "RegionOne", "interface": "internal", "id": "8fa782a99812415cad348399d922007c"}, {"region_id": "RegionOne", "url": "http://10.42.23.22:9494", "region": "RegionOne", "interface": "admin", "id": "d0094376148141359c66c33ae548b5bb"}], "type": "artifact", "id": "ef1ff29cc4ad41948b07e3bc3c7139b2", "name": "glare"}], "user": {"domain": {"id": "default", "name": "Default"}, "id": "4dda04dbab694cf5afbce05193d95644", "name": "admin"}, "audit_ids": ["5GnrTV5gSyKP9Qm22JYQbg"], "issued_at": "2016-09-21T08:00:09.000000Z"}}"
16:00:10.598 [main] DEBUG org.apache.http.impl.conn.BasicClientConnectionManager - Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@1b2abca6
16:00:10.599 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Connection 0.0.0.0:54815<->10.42.16.32:5000 shut down
16:00:10.693 [main] DEBUG org.openstack4j.core.transport.internal.HttpExecutor - Executing Request: http://10.42.23.22:8774/v2.1 -> /os-aggregates
16:00:10.699 [main] DEBUG org.apache.http.impl.conn.BasicClientConnectionManager - Get connection for route {}->http://10.42.23.22:8774
16:00:10.699 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnectionOperator - Connecting to 10.42.23.22:8774
16:00:10.703 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
16:00:10.703 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
16:00:10.703 [main] DEBUG org.apache.http.client.protocol.RequestTargetAuthentication - Target auth state: UNCHALLENGED
16:00:10.703 [main] DEBUG org.apache.http.client.protocol.RequestProxyAuthentication - Proxy auth state: UNCHALLENGED
16:00:10.703 [main] DEBUG org.apache.http.impl.client.DefaultHttpClient - Attempt 1 to execute request
16:00:10.703 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Sending request: POST /v2.1/os-aggregates HTTP/1.1
16:00:10.703 [main] DEBUG org.apache.http.wire -  >> "POST /v2.1/os-aggregates HTTP/1.1[\r][\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "X-Auth-Token: gAAAAABX4j4JmcbATZeuz446X1rxfQ7uyLrsuFvnyyeXDh4VMSdgPZWHaWkL_CAdX5zFCAaxIyQaRGm_VLs9_cZQvxhApf_u4MEufNbNJEiuQnOAS5Zq6aFzCpQrSfHYFWdJIPnA3XHV6YvfwUXVcbvCUM3Vex0ZtA[\r][\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "User-Agent: OpenStack4j / OpenStack Client[\r][\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "Content-Length: 130[\r][\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "Content-Type: application/json[\r][\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "Host: 10.42.23.22:8774[\r][\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "Connection: Keep-Alive[\r][\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "[\r][\n]"
16:00:10.704 [main] DEBUG org.apache.http.headers - >> POST /v2.1/os-aggregates HTTP/1.1
16:00:10.704 [main] DEBUG org.apache.http.headers - >> X-Auth-Token: gAAAAABX4j4JmcbATZeuz446X1rxfQ7uyLrsuFvnyyeXDh4VMSdgPZWHaWkL_CAdX5zFCAaxIyQaRGm_VLs9_cZQvxhApf_u4MEufNbNJEiuQnOAS5Zq6aFzCpQrSfHYFWdJIPnA3XHV6YvfwUXVcbvCUM3Vex0ZtA
16:00:10.704 [main] DEBUG org.apache.http.headers - >> User-Agent: OpenStack4j / OpenStack Client
16:00:10.704 [main] DEBUG org.apache.http.headers - >> Content-Length: 130
16:00:10.704 [main] DEBUG org.apache.http.headers - >> Content-Type: application/json
16:00:10.704 [main] DEBUG org.apache.http.headers - >> Host: 10.42.23.22:8774
16:00:10.704 [main] DEBUG org.apache.http.headers - >> Connection: Keep-Alive
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "{[\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "  "aggregate" : {[\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "    "deleted" : false,[\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "    "name" : "aaa",[\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "    "avaiablityZone" : "bbb",[\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "    "availability_zone" : "bbb"[\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "  }[\n]"
16:00:10.704 [main] DEBUG org.apache.http.wire -  >> "}"
16:00:10.793 [main] DEBUG org.apache.http.wire -  << "HTTP/1.1 400 Bad Request[\r][\n]"
16:00:10.793 [main] DEBUG org.apache.http.wire -  << "X-Openstack-Nova-Api-Version: 2.1[\r][\n]"
16:00:10.793 [main] DEBUG org.apache.http.wire -  << "Vary: X-OpenStack-Nova-API-Version[\r][\n]"
16:00:10.793 [main] DEBUG org.apache.http.wire -  << "Content-Type: application/json; charset=UTF-8[\r][\n]"
16:00:10.793 [main] DEBUG org.apache.http.wire -  << "Content-Length: 276[\r][\n]"
16:00:10.794 [main] DEBUG org.apache.http.wire -  << "X-Compute-Request-Id: req-91d19b2b-e4c0-4d26-928c-4f74a913864f[\r][\n]"
16:00:10.794 [main] DEBUG org.apache.http.wire -  << "Date: Wed, 21 Sep 2016 08:00:10 GMT[\r][\n]"
16:00:10.794 [main] DEBUG org.apache.http.wire -  << "Connection: close[\r][\n]"
16:00:10.794 [main] DEBUG org.apache.http.wire -  << "[\r][\n]"
16:00:10.794 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Receiving response: HTTP/1.1 400 Bad Request
16:00:10.794 [main] DEBUG org.apache.http.headers - << HTTP/1.1 400 Bad Request
16:00:10.794 [main] DEBUG org.apache.http.headers - << X-Openstack-Nova-Api-Version: 2.1
16:00:10.794 [main] DEBUG org.apache.http.headers - << Vary: X-OpenStack-Nova-API-Version
16:00:10.794 [main] DEBUG org.apache.http.headers - << Content-Type: application/json; charset=UTF-8
16:00:10.794 [main] DEBUG org.apache.http.headers - << Content-Length: 276
16:00:10.794 [main] DEBUG org.apache.http.headers - << X-Compute-Request-Id: req-91d19b2b-e4c0-4d26-928c-4f74a913864f
16:00:10.794 [main] DEBUG org.apache.http.headers - << Date: Wed, 21 Sep 2016 08:00:10 GMT
16:00:10.794 [main] DEBUG org.apache.http.headers - << Connection: close
16:00:10.799 [main] DEBUG org.apache.http.wire -  << "{"badRequest": {"message": "Invalid input for field/attribute aggregate. Value: {u'deleted': False, u'name': u'aaa', u'avaiablityZone': u'bbb', u'availability_zone': u'bbb'}. Additional properties are not allowed (u'deleted', u'avaiablityZone' were unexpected)", "code": 400}}"
16:00:10.802 [main] DEBUG org.apache.http.impl.conn.BasicClientConnectionManager - Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@1f81aa00
16:00:10.802 [main] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Connection 0.0.0.0:54816<->10.42.23.22:8774 shut down

**Comment by Silence803** [comment]
I modified the source code，Can solve this problem。
class:openstack4j-master\core\src\main\java\org\openstack4j\openstack\compute\domain\NovaHostAggregate
change code:
----------------------------------------------------------------------------------------
@JsonProperty("availability_zone")
public String availability_zone;
@JsonIgnore
public boolean deleted;
------------------------------------------------------------------------------------------
old code:
------------------------------------------------------------------------------------------
@JsonProperty("availability_zone")
public String availabilityZone;
public boolean deleted;
-------------------------------------------------------------------------------------------
Hope to help you.

**Comment by Cherry522** [comment]
OK. Thank you!

**Comment by auhlig** [comment]
@Silence803 Do you want to contribute the fix?

**Comment by Silence803** [comment]
@auhlig I'd like to, but what am I going to do?

**Comment by auhlig** [comment]
Hi @Silence803,
Very cool. 
Just fork the repo on github to your account, 
git-clone repo to your computer, 
open project with ide of your choice, 
do the change, 
when using java 8 run the tests using `mvn clean verify` on java7 `mvn clean verify -pl !org.pacesys.openstack4j.connectors:openstack4j-http-connector,!org.pacesys.openstack4j.connectors:openstack4j-jersey2,!org.pacesys:it-jersey2 `, push changes to your github and finally
create the PR.

**Comment by Cherry522** [comment]
@Silence803  I modified the code according to what you said ,but it still doesn't solve it.
@auhlig  I just tested the 3.0.4-SNAPSHOT version, but it still doesn't solve it.
 I modified the source code to solve this problem.
And I commit a pull request.
