### ISSUE TITLE
Tenants and roles empty

### ISSUE THREAD

**Issue by dimazaur** [gondor/openstack4j#616]
I have several bugs:
tenants().create - returns null
tenants().list() - empty list
roles().list() - empty list
users().list() - is working fine

When I use just simple json requests to the Keystone - this functionality working well.
But wanted to use advanced library.
Where could be an issue?
Thanks.

**Comment by babyachievement** [comment]
I find the problem too.  When I try to get the size of services by calling list method of ServiceManagerService with admin user, it return 0. 
```
OSClient os = OSFactory.builder()
                .endpoint("http://10.128.8.90:5000/v2.0")
                .credentials("admin","123456")
                .tenantName("admin")
                .authenticate();
ServiceManagerService sm = os.identity().services();

// List Services
List<? extends org.openstack4j.model.identity.Service> services2 = sm.list();
System.out.println(services2.size());
System.out.println(sm.listEndpoints().size());

```

**Comment by zeyuphoenix** [comment]
I have the same question，used
OSClient os = OSFactory.builder()
                .endpoint("http://10.128.8.90:5000/v2.0")
                .credentials("admin","123456")
                .tenantName("admin")
                .perspective(Facing.ADMIN)
                .authenticate();

**Comment by babyachievement** [comment]
@zeyuphoenix thanks.
