### ISSUE TITLE
 ArrayIndexOutofBoundException for getByName() in V3 Identity Service 

### ISSUE THREAD

**Issue by anneraby** [gondor/openstack4j#625]
In V3.0

Minor issue in the following methods in the case when the User, Project or Service does not exist.

org.openstack4j.openstack.identity.internal.GroupServiceImpl.getByName(String, String)
org.openstack4j.openstack.identity.internal.ProjectServiceImpl.getByName(String, String)
org.openstack4j.openstack.identity.internal.UserServiceImpl.getByName(String, String)

Will throw an ArrayIndexOutofBoundException.

Following the API of other services, I suggest that the Identity services return the entity (User,Project or Service) or null if not found

**Comment by auhlig** [comment]
Closing, because this is fixed by #626.
