### ISSUE TITLE
unable to create tenant

### ISSUE THREAD

**Issue by irfanjs** [gondor/openstack4j#638]
Hello,
I am using openstack4j framework to access and configure our openstack based private cloud. 
I have configured the authentication and getting token successfully.
we are using keystone service version 8.1.0 

However, getting error while creating tenant. following is the exception: I am not sure is it a bug in our implementation OR are we using some old release ? Please suggest  

**Exception in thread "main" ConnectionException{message=Already connected, status=0}
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:58)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:189)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:183)
	at org.openstack4j.openstack.identity.internal.TenantServiceImpl.create(TenantServiceImpl.java:41)
	at tenent.TestTenent.main(TestTenent.java:13)
Caused by: javax.ws.rs.ProcessingException: Already connected
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:233)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:656)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:653)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:653)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:413)
	at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:79)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
	at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	... 6 more
Caused by: java.lang.IllegalStateException: Already connected
	at sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(HttpURLConnection.java:3014)
	at org.glassfish.jersey.client.HttpUrlConnector.setOutboundHeaders(HttpUrlConnector.java:348)
	at org.glassfish.jersey.client.HttpUrlConnector.access$100(HttpUrlConnector.java:87)
	at org.glassfish.jersey.client.HttpUrlConnector$3.getOutputStream(HttpUrlConnector.java:311)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:200)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:194)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:262)
	at org.glassfish.jersey.message.internal.OutboundMessageContext.commitStream(OutboundMessageContext.java:811)
	at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:543)
	at org.glassfish.jersey.client.HttpUrlConnector._apply(HttpUrlConnector.java:315)
	at org.glassfish.jersey.client.HttpUrlConnector.apply(HttpUrlConnector.java:227)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:224)
	... 17 more:
**

**Comment by vinodborole** [comment]
@irfanjs  Check if this helps. https://github.com/gondor/openstack4j/issues/78

**Comment by irfanjs** [comment]
i checked that. as per that post, it talks about the older version of Jersey. As of now , i am using OS4J version 2.11 with following dependencies in the POM.

 <dependencies>
  <dependency>
  <groupId>org.pacesys</groupId>
  <artifactId>openstack4j</artifactId>
  <version>2.11</version>
</dependency>
<dependency>
    <groupId>org.pacesys</groupId>
    <artifactId>openstack4j-core</artifactId>
    <version>2.11</version>
</dependency>
</dependencies>

Please suggest.
Regards

**Comment by irfanjs** [comment]
As per the post #78 we need to use OKHttpConnector. but i am not sure how much this is valid. because, this issue was present in old version of jersey. As i am using OS4J version 2.11 , Jersey might have also upgraded to latest version and this issue was already addressed. Do i need to add any specific version of jersey in POM. ??
further, i dont know know how to use , OKHttpConnector ...
Please suggest 

Regards

**Comment by irfanjs** [comment]
OK. I modified the POM and added the connector details: 
```
<dependency>
    <groupId>org.pacesys.openstack4j.connectors</groupId>
    <artifactId>openstack4j-okhttp</artifactId>
    <version>2.11</version>
</dependency>
```
still the same issue. i red the getting started document and got this info ... but still an issue

**Comment by irfanjs** [comment]
Further, i am not using any VPN, this is just a straight LAN but with different network. 
please suggest 

Regards

**Comment by vinodborole** [comment]
@irfanjs  One thing you can do is, check if you can do same operation using openstack CLI; try to run this in debug mode [--debug] if it is successful then capture the trace and compare it with the debug log from openstack4j [you will need to enable the debug logs here]. 

In both the traces verify the REST call and request parameters.

**Comment by irfanjs** [comment]
thanks. while trying from the command line, was facing issue with credentials and source files. working in that .. once resolved, will resume on this. i agree that from command line, tenant should get created with single authentication. 
 
Regards

**Comment by irfanjs** [comment]
further, modified the code and enabled the httplogging. 
i am getting successful token authentication.

> 
 successfulKeystoneToken{id=f5e902c718dc43cd8b6633ce4a9cbd27, created=Thu Apr 28 10:04:55 IST 2016, expires=Thu Apr 28 10:56:59 IST 2016, tenant=KeystoneTenant{id=28d5644376ba4d3bab3a30e09a0b28d1, name=admin, description=Admin Project, enabled=true}}
> 

however, immediately after that, getting above exception....
Regards

**Comment by irfanjs** [comment]
i am using liberty release and found that , i am able to create project (tenant) using command line.
> 
` openstack project create --domain default --description "xyz" xyz`
> 
so i think there is no any issue while creating tenants from command line. 
when i used the ---debug option , i got very verbose output. 
on the initial, i see that the auth url in the command line output and in the java implementation is differ. 
the endpoint which is being written from java implementation is : 
`http://192.168.103.101:5000/v2.0`
and auth_url from command line is :
`http://controller:35357/v3`

does that seem any relation to my problem ??

**Comment by vinodborole** [comment]
@irfanjs  it seems the token is generated for the public URL. Please get the Admin URL to get the url you need. you can do this by setting the perspective ADMIN 

               os = OSFactory.builderV3().useNonStrictSSLClient(isSSLEnabled).scopeToProject(Identifier.byId(tenantID), Identifier.byName(domain))
                .credentials(username, password, Identifier.byName(domain)).endpoint(authUrl).perspective(Facing.ADMIN)
                .authenticate();

**Comment by irfanjs** [comment]
thanks . let me check and modify

**Comment by irfanjs** [comment]
if i use the endpoint `http://192.168.103.101:5000/v2.0` then i am able to authenticate but if i use the endpoint `http://controller:35357/v3` then i am not.
i am not getting which endpoint is correct . please suggest .

further i changed the code as follows:
`os = OSFactory.builderV3().useNonStrictSSLClient(false).credentials("admin", "admin123")
.scopeToProject(Identifier.byId("28d5644376ba4d3bab3a30e09a0b28d1"), Identifier.byName("default")).endpoint("http://controller:35357/v3").perspective(Facing.ADMIN).authenticate();`

if i use the above code then authentication is not happening because V3 is being used. if i changed it to V2 then authentication is happening but getting exception as above.

dont know know where i am doing wrong ... 
Regards

**Comment by vinodborole** [comment]
@irfanjs 

change your endpoint Url to http://192.168.103.101:5000/v3 the property .perspective(Facing.ADMIN) will internally pick the endpoit for Admin which in your case is http://controller:35357/v3

**Comment by irfanjs** [comment]
ok. if i change theenpoint URL to "http://192.168.103.101:5000/v3" then authentication is not happening ...

`os = OSFactory.builderV3().useNonStrictSSLClient(false).credentials("admin", "admin123")
.scopeToProject(Identifier.byId("28d5644376ba4d3bab3a30e09a0b28d1"), Identifier.byName("default")).endpoint("http://192.168.103.101:5000/v3").perspective(Facing.ADMIN).authenticate();
`
exception is :
`
Apr 28, 2016 5:32:05 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > POST http://192.168.103.101:5000/v3/auth/tokens
1 > Accept: application/json
1 > Content-Type: application/json
1 > OS4J-Auth-Command: Tokens
{
  "auth" : {
    "identity" : {
      "password" : {
        "user" : {
          "id" : "admin",
          "password" : "admin123"
        }
      },
      "methods" : [ "password" ]
    },
    "scope" : {
      "project" : {
        "id" : "28d5644376ba4d3bab3a30e09a0b28d1",
        "domain" : {
          "name" : "default"
        }
      }
    },
    "type" : "CREDENTIALS"
  }
}

Apr 28, 2016 5:32:05 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Client response received on thread main
2 < 401
2 < Connection: Keep-Alive
2 < Content-Length: 114
2 < Content-Type: application/json
2 < Date: Thu, 28 Apr 2016 12:02:10 GMT
2 < Keep-Alive: timeout=5, max=100
2 < Server: Apache/2.4.7 (Ubuntu)
2 < Vary: X-Auth-Token
2 < WWW-Authenticate: Keystone uri="http://192.168.103.101:5000"
2 < X-Distribution: Ubuntu
2 < x-openstack-request-id: req-3f150f78-f9c2-418f-9f4e-c9e5c51f7c68
{"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}

Exception in thread "main" AuthenticationException{message=Unauthorized, status=401}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:36)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:161)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:78)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:163)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:127)
	at tenent.Authentication.getOsClient(Authentication.java:20)
	at tenent.TestTenent.main(TestTenent.java:12)
`

**Comment by vinodborole** [comment]
@irfanjs For a successful authentication can you paste the entire token json that has all the endpoint URI's?

**Comment by irfanjs** [comment]
sorry did not get .. can you please explain ?
do i need to run any command for that ? 
OR through any java method i can get it ?

Regards

**Comment by vinodborole** [comment]
run any command from openstack CLI in debug mode, you would see a token request and its response, paste the response

**Comment by irfanjs** [comment]
i did not able to recognize which actual response we are looking for, so i pasted entire output::
`
root@controller:~/wol_64/usr/bin# openstack user list --debug
START with options: ['user', 'list', '--debug']
options: Namespace(access_token_endpoint='', auth_type='', auth_url='http://controller:35357/v3', cacert='', client_id='', client_secret='***', cloud='', debug=True, default_domain='default', deferred_help=False, domain_id='', domain_name='', endpoint='', identity_provider='', identity_provider_url='', insecure=None, interface='', log_file=None, os_compute_api_version='', os_data_processing_api_version='1.1', os_dns_api_version='', os_identity_api_version='3', os_image_api_version='2', os_network_api_version='', os_object_api_version='', os_project_id=None, os_project_name=None, os_queues_api_version='1.1', os_volume_api_version='', password='***', project_domain_id='default', project_domain_name='', project_id='28d5644376ba4d3bab3a30e09a0b28d1', project_name='admin', protocol='', region_name='RegionOne', scope='', service_provider_endpoint='', timing=False, token='***', trust_id='', url='', user_domain_id='default', user_domain_name='', user_id='', username='admin', verbose_level=3, verify=None)
defaults: {u'auth_type': 'password', u'compute_api_version': u'2', 'key': None, u'database_api_version': u'1.0', 'api_timeout': None, u'baremetal_api_version': u'1', u'image_api_version': u'2', 'cacert': None, u'image_api_use_tasks': False, u'floating_ip_source': u'neutron', u'orchestration_api_version': u'1', u'interface': None, u'network_api_version': u'2', u'image_format': u'qcow2', u'key_manager_api_version': u'v1', u'metering_api_version': u'2', 'verify': True, u'identity_api_version': u'2.0', u'volume_api_version': u'2', 'cert': None, u'secgroup_source': u'neutron', u'container_api_version': u'1', u'dns_api_version': u'2', u'object_store_api_version': u'1', u'disable_vendor_agent': {}}
cloud cfg: {'auth_type': 'password', u'compute_api_version': u'2', u'orchestration_api_version': u'1', u'database_api_version': u'1.0', 'data_processing_api_version': '1.1', u'network_api_version': u'2', u'image_format': u'qcow2', 'queues_api_version': '1.1', 'verify': True, u'dns_api_version': u'2', u'object_store_api_version': u'1', 'verbose_level': 3, 'region_name': 'RegionOne', 'api_timeout': None, u'baremetal_api_version': u'1', u'image_api_version': '2', 'auth': {'username': 'admin', 'password': '***', 'project_name': 'admin', 'user_domain_id': 'default', 'auth_url': 'http://controller:35357/v3', 'project_id': '28d5644376ba4d3bab3a30e09a0b28d1', 'project_domain_id': 'default'}, 'default_domain': 'default', u'container_api_version': u'1', u'image_api_use_tasks': False, u'floating_ip_source': u'neutron', 'key': None, 'timing': False, 'cacert': None, u'key_manager_api_version': u'v1', u'metering_api_version': u'2', 'deferred_help': False, u'identity_api_version': '3', u'volume_api_version': u'2', 'cert': None, u'secgroup_source': u'neutron', 'debug': True, u'interface': None, u'disable_vendor_agent': {}}
compute API version 2, cmd group openstack.compute.v2
network API version 2, cmd group openstack.network.v2
image API version 2, cmd group openstack.image.v2
volume API version 2, cmd group openstack.volume.v2
identity API version 3, cmd group openstack.identity.v3
object_store API version 1, cmd group openstack.object_store.v1
dns API version 2, cmd group openstack.dns.v2
data_processing API version 1.1, cmd group openstack.data_processing.v1
messaging API version 1.1, cmd group openstack.messaging.v1
command: user list -> openstackclient.identity.v3.user.ListUser
Auth plugin password selected
auth_type: password
Using auth plugin: password
Using parameters {'username': 'admin', 'project_id': '28d5644376ba4d3bab3a30e09a0b28d1', 'project_name': 'admin', 'auth_url': 'http://controller:35357/v3', 'user_domain_id': 'default', 'password': '***', 'project_domain_id': 'default'}
Get auth_ref
REQ: curl -g -i -X GET http://controller:35357/v3 -H "Accept: application/json" -H "User-Agent: python-openstackclient keystoneauth1/2.3.0 python-requests/2.9.1 CPython/2.7.6"
Starting new HTTP connection (1): controller
"GET /v3 HTTP/1.1" 200 250
RESP: [200] Content-Length: 250 Vary: X-Auth-Token Keep-Alive: timeout=5, max=100 Server: Apache/2.4.7 (Ubuntu) Connection: Keep-Alive Date: Thu, 28 Apr 2016 17:44:59 GMT x-openstack-request-id: req-2c060276-6bb0-4903-a287-699275f416e8 Content-Type: application/json X-Distribution: Ubuntu
RESP BODY: {"version": {"status": "stable", "updated": "2015-03-30T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}], "id": "v3.4", "links": [{"href": "http://controller:35357/v3/", "rel": "self"}]}}

Making authentication request to http://controller:35357/v3/auth/tokens
"POST /v3/auth/tokens HTTP/1.1" 201 5115
run(Namespace(columns=[], domain=None, formatter='table', group=None, long=False, max_width=0, noindent=False, project=None, quote_mode='nonnumeric'))
Instantiating identity client: <class 'keystoneclient.v3.client.Client'>
Making authentication request to http://controller:35357/v3/auth/tokens
"POST /v3/auth/tokens HTTP/1.1" 201 5115
REQ: curl -g -i -X GET http://controller:35357/ -H "Accept: application/json" -H "User-Agent: python-openstackclient keystoneauth1/2.3.0 python-requests/2.9.1 CPython/2.7.6"
"GET / HTTP/1.1" 300 591
RESP: [300] Content-Length: 591 Vary: X-Auth-Token Keep-Alive: timeout=5, max=97 Server: Apache/2.4.7 (Ubuntu) Connection: Keep-Alive Date: Thu, 28 Apr 2016 17:44:59 GMT Content-Type: application/json X-Distribution: Ubuntu
RESP BODY: {"versions": {"values": [{"status": "stable", "updated": "2015-03-30T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}], "id": "v3.4", "links": [{"href": "http://controller:35357/v3/", "rel": "self"}]}, {"status": "stable", "updated": "2014-04-17T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v2.0+json"}], "id": "v2.0", "links": [{"href": "http://controller:35357/v2.0/", "rel": "self"}, {"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}]}]}}

REQ: curl -g -i -X GET http://controller:35357/v3/users -H "User-Agent: python-keystoneclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}6170fb59ebae4dc904facb172266253f832e5cd8"
"GET /v3/users HTTP/1.1" 200 3922
RESP: [200] Content-Length: 3922 Vary: X-Auth-Token Keep-Alive: timeout=5, max=96 Server: Apache/2.4.7 (Ubuntu) Connection: Keep-Alive Date: Thu, 28 Apr 2016 17:44:59 GMT x-openstack-request-id: req-18fcf3cf-0648-4806-94e6-f7b9fd033aa0 Content-Type: application/json X-Distribution: Ubuntu
RESP BODY: {"users": [{"name": "pb26", "links": {"self": "http://controller:35357/v3/users/1c42563acef64efdb8a53d880c8d968e"}, "enabled": true, "email": "pb@gmail.com", "default_project_id": "144514d652214caab5375336dbfeb720", "id": "1c42563acef64efdb8a53d880c8d968e", "domain_id": "default", "description": "pb user"}, {"name": "pb", "links": {"self": "http://controller:35357/v3/users/29e3bc72ce324ec49cac574877536613"}, "enabled": true, "email": "pb@gmail.com", "default_project_id": "a80a08057f5043a58f2487872488d1db", "id": "29e3bc72ce324ec49cac574877536613", "domain_id": "ccbdd968722b4ac89467873bfe1c0318", "description": "pb user"}, {"name": "pb_project", "links": {"self": "http://controller:35357/v3/users/3edf55ebb1b2405780902c5a0546e30e"}, "enabled": true, "email": "pb@gmail.com", "default_project_id": "a80a08057f5043a58f2487872488d1db", "id": "3edf55ebb1b2405780902c5a0546e30e", "domain_id": "ccbdd968722b4ac89467873bfe1c0318", "description": "pb user"}, {"links": {"self": "http://controller:35357/v3/users/44ba9b0c98e24be9a7dab8782b23953b"}, "description": "\"Developer Use Purpose\"", "name": "dev", "domain_id": "default", "enabled": true, "id": "44ba9b0c98e24be9a7dab8782b23953b", "default_project_id": "36350fc1209b48418728faaaf6d706c4"}, {"name": "admin", "links": {"self": "http://controller:35357/v3/users/5c50e3803049470283f7a9d18e871096"}, "enabled": true, "id": "5c50e3803049470283f7a9d18e871096", "domain_id": "default"}, {"name": "pb2", "links": {"self": "http://controller:35357/v3/users/5fee32b5e1ec48818579db414f36fae0"}, "enabled": true, "email": "pb@gmail.com", "default_project_id": "36350fc1209b48418728faaaf6d706c4", "id": "5fee32b5e1ec48818579db414f36fae0", "domain_id": "ccbdd968722b4ac89467873bfe1c0318", "description": "pb user"}, {"name": "glance", "links": {"self": "http://controller:35357/v3/users/680232118b554deca52deb8d2d832f2c"}, "enabled": true, "id": "680232118b554deca52deb8d2d832f2c", "domain_id": "default"}, {"name": "mdeore", "links": {"self": "http://controller:35357/v3/users/92a3e8d6cd684145a51f5c7c2fba7072"}, "enabled": true, "id": "92a3e8d6cd684145a51f5c7c2fba7072", "domain_id": "default"}, {"name": "ceilometer", "links": {"self": "http://controller:35357/v3/users/986ad8fec9394eb4b27a3d4f3c9a7d55"}, "enabled": true, "id": "986ad8fec9394eb4b27a3d4f3c9a7d55", "domain_id": "default"}, {"links": {"self": "http://controller:35357/v3/users/a1df3395882f498fa53e6e52899dbbd0"}, "description": "\"QA User\"", "name": "QA", "domain_id": "default", "enabled": true, "id": "a1df3395882f498fa53e6e52899dbbd0", "default_project_id": "60be105a45a645d298f8abb03690a94f"}, {"name": "demo", "links": {"self": "http://controller:35357/v3/users/cdbb75884dab495e80b07e9bcb82bf62"}, "enabled": true, "id": "cdbb75884dab495e80b07e9bcb82bf62", "domain_id": "default"}, {"name": "nova", "links": {"self": "http://controller:35357/v3/users/d2151bf252004ee28a13641fe54b5f7c"}, "enabled": true, "id": "d2151bf252004ee28a13641fe54b5f7c", "domain_id": "default"}, {"name": "ironic", "links": {"self": "http://controller:35357/v3/users/d267923efdc84c4089e6489165d67f96"}, "domain_id": "default", "enabled": true, "email": "irfan.sayed@msystechnologies.com", "id": "d267923efdc84c4089e6489165d67f96"}, {"name": "heat", "links": {"self": "http://controller:35357/v3/users/db0aa0dc6f71442a93a96c9445ceb1a8"}, "enabled": true, "id": "db0aa0dc6f71442a93a96c9445ceb1a8", "domain_id": "default"}, {"name": "heat_domain_admin", "links": {"self": "http://controller:35357/v3/users/ed83ddadf3934ad1a3c19c8d7a257a84"}, "enabled": true, "id": "ed83ddadf3934ad1a3c19c8d7a257a84", "domain_id": "6d061400c2be4550a8a803383819af59"}, {"name": "neutron", "links": {"self": "http://controller:35357/v3/users/ff70ee1719d74b41a943b9c003107b3f"}, "enabled": true, "id": "ff70ee1719d74b41a943b9c003107b3f", "domain_id": "default"}], "links": {"self": "http://controller:35357/v3/users", "previous": null, "next": null}}

+----------------------------------+-------------------+
| ID                               | Name              |
+----------------------------------+-------------------+
| 1c42563acef64efdb8a53d880c8d968e | pb26              |
| 29e3bc72ce324ec49cac574877536613 | pb                |
| 3edf55ebb1b2405780902c5a0546e30e | pb_project        |
| 44ba9b0c98e24be9a7dab8782b23953b | dev               |
| 5c50e3803049470283f7a9d18e871096 | admin             |
| 5fee32b5e1ec48818579db414f36fae0 | pb2               |
| 680232118b554deca52deb8d2d832f2c | glance            |
| 92a3e8d6cd684145a51f5c7c2fba7072 | mdeore            |
| 986ad8fec9394eb4b27a3d4f3c9a7d55 | ceilometer        |
| a1df3395882f498fa53e6e52899dbbd0 | QA                |
| cdbb75884dab495e80b07e9bcb82bf62 | demo              |
| d2151bf252004ee28a13641fe54b5f7c | nova              |
| d267923efdc84c4089e6489165d67f96 | ironic            |
| db0aa0dc6f71442a93a96c9445ceb1a8 | heat              |
| ed83ddadf3934ad1a3c19c8d7a257a84 | heat_domain_admin |
| ff70ee1719d74b41a943b9c003107b3f | neutron           |
+----------------------------------+-------------------+
clean_up ListUser:
END return value: 0
`

**Comment by vinodborole** [comment]
All i see are the v3 auth url's and no v2 auth urls but when mentioned your authentication worked with v2 url before and not with v3; how is this possible. Anyways, your end point url should be the same as in your source file that you used to create tenant from command line. Please try that with and without perspective as ADMIN.

**Comment by irfanjs** [comment]
same story again.
let me paste you the actual code ... 

regards

**Comment by irfanjs** [comment]
http://pastebin.com/QDru3DDy
please have a look

Regards

**Comment by irfanjs** [comment]
Can you please suggest. I am not getting where am i doing wrong.

**Comment by vinodborole** [comment]
@irfanjs i do not see any issue with your code, did you try other operations on the Identity service to be sure its nothing to do with your code?

**Comment by irfanjs** [comment]
No i did not. actually, i was keen on tenant creation operation only. 
ok lets narrow down the problem.
if i am able to create tenant from command line , it means no issue on the openstack infrastructure.
either there is some issue in the code OR may be some issue with OS4J. 

so what you suggest ? 
Regards

**Comment by irfanjs** [comment]
further, using the code, i am able to get the list of all tenants but while creating new tenants , getting following error:
`
Apr 30, 2016 3:18:06 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Client response received on thread main
2 < 404
2 < Connection: Keep-Alive
2 < Content-Length: 93
2 < Content-Type: application/json
2 < Date: Sat, 30 Apr 2016 09:48:11 GMT
2 < Keep-Alive: timeout=5, max=100
2 < Server: Apache/2.4.7 (Ubuntu)
2 < Vary: X-Auth-Token
2 < X-Distribution: Ubuntu
2 < x-openstack-request-id: req-9bd7186c-c37d-411d-a907-3a789de1f88e
{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}
`

i dont know , why there is error : 

> resource could not be found

>

**Comment by irfanjs** [comment]
@gondor : do you feel my issue is related to openstack release. ?
till now, i am able to authenticate and list down the available tenants. but cant create new tenants. 
setting up different version/release of openstack seems very time consuming and long route.

Can you please suggest ?
Regards

**Comment by irfanjs** [comment]
@gondor @vinodborole 
can you please suggest ? I am stuck totally and need to sort it out asap 
please help 

regards

**Comment by vinodborole** [comment]
@irfanjs  I have Juno installed and i can create/update/delete tenant with o4j. I could reproduce the error you get in case where i try to authenticate the user without the ADMIN perspective. If i switch the token to ADMIN perspective i could execute all the operations. In your code you shared you are not setting the perspective as ADMIN. 

      OSFactory.builder().endpoint(authURL).credentials(username, password).tenantId(tenantID).useNonStrictSSLClient(true).perspective(Facing.ADMIN).authenticate();

**Comment by irfanjs** [comment]
Awesome !!!! 
Its resolved. I am able to create tenants now ....  it was so nice
really appreciate.

Regards

**Comment by vinodborole** [comment]
@irfanjs  please close the issue.
